import { c as create_ssr_component } from '../../../chunks/index.js';

const _layout_svelte_svelte_type_style_lang = '';

/* src/routes/house-rules/+layout.svelte generated by Svelte v3.55.0 */

const css = {
	code: "section.svelte-6hoghh{max-width:75ch;margin:auto}",
	map: null
};

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<aside></aside>
<section class="${"house-rules svelte-6hoghh"}">${slots.default ? slots.default({}) : ``}
</section>`;
});

export { Layout as default };
