import { c as create_ssr_component, g as escape } from '../../../chunks/index.js';
import { s as siteTitle } from '../../../chunks/config.js';

/* src/routes/house-rules/+page.md generated by Svelte v3.55.0 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${($$result.head += '<!-- HEAD_svelte-cnbvpd_START -->' + `${($$result.title = `<title>${escape(siteTitle)}</title>`, "")}` + '<!-- HEAD_svelte-cnbvpd_END -->', "")}


<h1 id="${"house-rules"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#house-rules"}"><span class="${"icon icon-link"}"></span></a>House Rules</h1>
<h2 id="${"daily-schedule"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#daily-schedule"}"><span class="${"icon icon-link"}"></span></a>Daily Schedule</h2>
<ol><li>Class begins 8am sharp in Zoom for all courses, except:<ul><li>CPNT 264: Career and Consulting Essentials<ul><li>Dasa will email you with details</li></ul></li>
<li>CPLN 240: Guest Speaker Day<ul><li>SAIT admin will send you details?</li></ul></li></ul></li>
<li>Lunch from 11:30am - 12:30pm<ul><li>There will also be multiple breaks throughout the day.</li></ul></li>
<li>There will be opportunities to earn late starts and early dismissals! Ask your instructors for details.</li></ol>
<h2 id="${"one-on-ones-with-instructors"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#one-on-ones-with-instructors"}"><span class="${"icon icon-link"}"></span></a>One-on-ones with Instructors</h2>
<p>Direct Message (DM) an Instructor/Facilitator anytime if you have a private <strong>non-coding</strong> concern or question.</p>
<p>But, for <strong>coding help</strong>, it’s encouraged you (in this order):</p>
<ol><li>Spend an honest amount of effort toward solving the problem yourself;</li>
<li>Post your question for help in the <code>#fall-2022</code> channel on Slack;</li>
<li>Ask your instructor/classmate during Open Lab time (most afternoons).</li></ol>`;
});

export { Page as default };
