import { c as create_ssr_component, b as subscribe, d as add_attribute, e as add_classes, v as validate_component, f as each, g as escape } from '../../chunks/index.js';
import { n as navItems, s as siteTitle, a as siteAuthor } from '../../chunks/config.js';
import { w as writable } from '../../chunks/index3.js';

const global = '';

const currentPage = writable('');
const isMenuOpen = writable(false);

/* src/lib/components/NavItem.svelte generated by Svelte v3.55.0 */

const NavItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let isCurrentPage;
	let $currentPage, $$unsubscribe_currentPage;
	$$unsubscribe_currentPage = subscribe(currentPage, value => $currentPage = value);
	let { href } = $$props;

	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	isCurrentPage = $currentPage.startsWith(href);
	$$unsubscribe_currentPage();
	return `<li><a${add_attribute("href", href, 0)}${add_attribute("aria-current", isCurrentPage ? 'page' : false, 0)}${add_classes((isCurrentPage ? "active" : "").trim())}>${slots.default ? slots.default({}) : ``}</a></li>`;
});

/* src/lib/components/svg/HamburgerSVG.svelte generated by Svelte v3.55.0 */

const HamburgerSVG = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<svg viewBox="${"0 0 128 128"}" version="${"1.1"}" style="${"fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"}"><g><rect x="${"0"}" y="${"12.48"}" width="${"128"}" height="${"18.688"}"></rect></g><g><rect x="${"0"}" y="${"96.832"}" width="${"128"}" height="${"18.688"}"></rect></g><g><rect x="${"0"}" y="${"54.656"}" width="${"128"}" height="${"18.688"}"></rect></g></svg>`;
});

/* src/lib/components/svg/XSVG.svelte generated by Svelte v3.55.0 */

const XSVG = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<svg viewBox="${"0 0 128 128"}" version="${"1.1"}" style="${"fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"}"><path d="${"M64,48.496l-48.496,-48.496l-15.504,15.504l48.496,48.496l-48.496,48.496l15.504,15.504l48.496,-48.496l48.496,48.496l15.504,-15.504l-48.496,-48.496l48.496,-48.496l-15.504,-15.504l-48.496,48.496Z"}"></path></svg>`;
});

/* src/lib/components/HamburgerMenuButton.svelte generated by Svelte v3.55.0 */

const HamburgerMenuButton = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $isMenuOpen, $$unsubscribe_isMenuOpen;
	$$unsubscribe_isMenuOpen = subscribe(isMenuOpen, value => $isMenuOpen = value);
	let { closeOnly } = $$props;

	if ($$props.closeOnly === void 0 && $$bindings.closeOnly && closeOnly !== void 0) $$bindings.closeOnly(closeOnly);
	$$unsubscribe_isMenuOpen();

	return `<button${add_attribute("aria-pressed", $isMenuOpen, 0)} class="${"menu-button"}"${add_attribute("tabindex", $isMenuOpen || !closeOnly ? '0' : '-1', 0)}><span class="${"sr-only"}">Toggle hamburger menu</span>
	${closeOnly
	? `${validate_component(XSVG, "XSVG").$$render($$result, {}, {}, {})}`
	: `${validate_component(HamburgerSVG, "HamburgerSVG").$$render($$result, {}, {}, {})}`}</button>`;
});

/* src/lib/components/MainNav.svelte generated by Svelte v3.55.0 */

const MainNav = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $isMenuOpen, $$unsubscribe_isMenuOpen;
	$$unsubscribe_isMenuOpen = subscribe(isMenuOpen, value => $isMenuOpen = value);
	$$unsubscribe_isMenuOpen();

	return `
<nav class="${["main-nav", $isMenuOpen ? "open" : ""].join(' ').trim()}"><ul>${each(navItems, page => {
		return `${validate_component(NavItem, "NavItem").$$render($$result, { href: page.route }, {}, {
			default: () => {
				return `${escape(page.title)}
		`;
			}
		})}`;
	})}</ul>
	${validate_component(HamburgerMenuButton, "HamburgerMenuButton").$$render($$result, { closeOnly: "true" }, {}, {})}</nav>`;
});

/* src/lib/components/Header.svelte generated by Svelte v3.55.0 */

const Header = create_ssr_component(($$result, $$props, $$bindings, slots) => {

	return `<header><a class="${"skip-to-content-link"}" href="${"#main"}">Skip to main content
	</a>
	
	<a href="${"/"}" class="${"logo"}"><img src="${"/images/sait-logo.png"}" alt="${"SAIT Logo"}">
		<div><span class="${"site-title"}">${escape(siteTitle)}</span><br>
			<span class="${"semester"}">Fall 2022</span></div></a>
	
	${validate_component(HamburgerMenuButton, "HamburgerMenuButton").$$render($$result, {}, {}, {})}
	${validate_component(MainNav, "MainNav").$$render($$result, {}, {}, {})}</header>`;
});

/* src/lib/components/Footer.svelte generated by Svelte v3.55.0 */

const Footer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<footer>${validate_component(MainNav, "MainNav").$$render($$result, {}, {}, {})}

	<nav><ul><li><a href="${"/api/rss.xml"}" rel="${"external"}">RSS</a></li>
			<li><a href="${"/"}">Home</a></li></ul></nav>

	<p>©${escape(new Date().getFullYear())} ${escape(siteAuthor)}</p></footer>`;
});

const _layout_svelte_svelte_type_style_lang = '';

/* src/routes/+layout.svelte generated by Svelte v3.55.0 */

const css = {
	code: "main.svelte-dn2bsh{max-width:150ch}",
	map: null
};

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $isMenuOpen, $$unsubscribe_isMenuOpen;
	$$unsubscribe_isMenuOpen = subscribe(isMenuOpen, value => $isMenuOpen = value);
	let { data } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);

	{
		currentPage.set(data.path);
	}

	$$unsubscribe_isMenuOpen();

	return `




<div class="${["layout", $isMenuOpen ? "open" : ""].join(' ').trim()}">${validate_component(Header, "Header").$$render($$result, {}, {}, {})}
	<main id="${"main"}" tabindex="${"-1"}" class="${"svelte-dn2bsh"}">${slots.default ? slots.default({}) : ``}</main>
	${validate_component(Footer, "Footer").$$render($$result, {}, {}, {})}
</div>`;
});

export { Layout as default };
