import { c as create_ssr_component, b as subscribe, f as each, g as escape, i as null_to_empty, v as validate_component } from '../../chunks/index.js';
import { s as siteTitle } from '../../chunks/config.js';
import { s as schedule } from '../../chunks/stores2.js';
import dayjs from 'dayjs';

const Schedule_svelte_svelte_type_style_lang = '';

/* src/lib/components/Schedule.svelte generated by Svelte v3.55.0 */

const css$1 = {
	code: "time.svelte-pkdlok.svelte-pkdlok{font-weight:bold}a.svelte-pkdlok.svelte-pkdlok{text-decoration:none}article.svelte-pkdlok.svelte-pkdlok{color:hsl(var(--hue), 20%, 10%);background:hsl(var(--hue), 25%, 93%);border:3px solid hsl(var(--hue), 20%, 50%);margin:1rem 2rem;padding:1rem;border-radius:.5rem;box-shadow:0px 1px 1px rgba(0,0,0,0.05),\n    0px 2px 2px rgba(0,0,0,0.05),\n    0px 4px 4px rgba(0,0,0,0.05),\n    0px 8px 8px rgba(0,0,0,0.05)}a.svelte-pkdlok:hover article.svelte-pkdlok{border:3px solid hsl(var(--hue), 50%, 50%);box-shadow:0px 1px 1px rgba(0,0,0,0.1),\n    0px 2px 2px rgba(0,0,0,0.1),\n    0px 4px 4px rgba(0,0,0,0.1),\n    0px 8px 8px rgba(0,0,0,0.1)}article.svelte-pkdlok h3.svelte-pkdlok{margin:1rem 0}article.holiday.svelte-pkdlok.svelte-pkdlok,article.unpublished.svelte-pkdlok.svelte-pkdlok{color:black;background:#ddd;box-shadow:initial}article.cpnt-264.svelte-pkdlok.svelte-pkdlok,article.cpln-240.svelte-pkdlok.svelte-pkdlok{color:hsl(0, 0%, 10%);background:hsl(0, 0%, 90%);border:3px solid hsl(0, 0%, 50%)}a.svelte-pkdlok:hover article.cpnt-264.svelte-pkdlok,a.svelte-pkdlok:hover article.cpln-240.svelte-pkdlok{border:3px solid hsl(0, 0%, 20%);box-shadow:0px 1px 1px rgba(0,0,0,0.1),\n    0px 2px 2px rgba(0,0,0,0.1),\n    0px 4px 4px rgba(0,0,0,0.1),\n    0px 8px 8px rgba(0,0,0,0.1)}article.dsgn-270.svelte-pkdlok.svelte-pkdlok{--hue:270}article.cpnt-201.svelte-pkdlok.svelte-pkdlok{--hue:30}article.cpnt-260.svelte-pkdlok.svelte-pkdlok{--hue:90}article.cpnt-262.svelte-pkdlok.svelte-pkdlok{--hue:180}article.cpnt-200.svelte-pkdlok.svelte-pkdlok{--hue:230}article.cpnt-265.svelte-pkdlok.svelte-pkdlok{--hue:360}",
	map: null
};

const Schedule = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $schedule, $$unsubscribe_schedule;
	$$unsubscribe_schedule = subscribe(schedule, value => $schedule = value);
	$$result.css.add(css$1);
	$$unsubscribe_schedule();

	return `${each($schedule, (week, index) => {
		return `<section class="${"week"}"><h2 id="${"week-" + escape(index + 1, true)}">Week ${escape(index + 1)}</h2>
  ${each(week, day => {
			return `${day.type === 'lesson' && day.status != 'draft'
			? `<time class="${"svelte-pkdlok"}">${escape(dayjs(day.date).format('dddd, MMM D'))}</time>
    <a href="${"courses/" + escape(day.code, true) + "/day-" + escape(day.day, true)}" class="${"svelte-pkdlok"}"><article class="${escape(day.code, true) + " lesson" + " svelte-pkdlok"}"><p>${escape(day.codeLabel)} - Day ${escape(day.day)}</p>
        <h3 class="${"svelte-pkdlok"}">${escape(day.title)}</h3></article>
    </a>`
			: `${day.status === 'draft'
				? `<time class="${"svelte-pkdlok"}">${escape(dayjs(day.date).format('dddd, MMM D'))}</time>
    <article class="${escape(day.code, true) + " unpublished" + " svelte-pkdlok"}"><p>${escape(day.codeLabel)} - Day ${escape(day.day)}</p>
      <h3 class="${escape(null_to_empty(day.code), true) + " svelte-pkdlok"}">${escape(day.codeLabel)} - ${escape(day.title)}</h3>
    </article>`
				: `<time class="${"svelte-pkdlok"}">${escape(dayjs(day.date).format('dddd, MMM D'))}</time>
    <article class="${"holiday svelte-pkdlok"}"><h3 class="${"holiday svelte-pkdlok"}">${escape(day.label)}</h3>
    </article>`}`}`;
		})}
</section>`;
	})}`;
});

const _page_svelte_svelte_type_style_lang = '';

/* src/routes/+page.svelte generated by Svelte v3.55.0 */

const css = {
	code: "section.svelte-6hoghh{max-width:75ch;margin:auto}",
	map: null
};

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `${($$result.head += '<!-- HEAD_svelte-cnbvpd_START -->' + `${($$result.title = `<title>${escape(siteTitle)}</title>`, "")}` + '<!-- HEAD_svelte-cnbvpd_END -->', "")}
<section class="${"schedule svelte-6hoghh"}"><h1>Program Schedule</h1>
  ${validate_component(Schedule, "Schedule").$$render($$result, {}, {}, {})}
</section>`;
});

export { Page as default };
