import { c as create_ssr_component } from '../../../chunks/index.js';

/* src/routes/assessments/+page.md generated by Svelte v3.55.0 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h1 id="${"assessments-used-in-this-program"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assessments-used-in-this-program"}"><span class="${"icon icon-link"}"></span></a>Assessments used in this program</h1>
<h2 id="${"1-daily-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-daily-achievements"}"><span class="${"icon icon-link"}"></span></a>1. Daily Achievements</h2>
<ul><li>Low bar but you must prove that you’re not wasting the opportunity of this [program course] gives you.</li>
<li>Brightspace submissions will be due at 5pm most days.</li>
<li>You are encouraged to experiment.</li></ul>
<h2 id="${"2-assignments"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-assignments"}"><span class="${"icon icon-link"}"></span></a>2. Assignments</h2>
<ul><li>Project-based</li>
<li>Late penalties: 10%/day</li>
<li>Submissions will not be accepted after 3 days late</li>
<li>Extensions will not be given the day an assignment is due</li>
<li>Marks will be returned within 10 days of submission<ul><li>Delays may occur if some students have not submitted due to extensions.</li></ul></li></ul>
<h2 id="${"3-stage-work"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-stage-work"}"><span class="${"icon icon-link"}"></span></a>3. Stage work</h2>
<ul><li>Show the class what you’ve built.</li>
<li>Teach the class something you’ve learned.</li>
<li>Help put on a great show!</li></ul>`;
});

export { Page as default };
