import { c as create_ssr_component, b as subscribe, g as escape, d as add_attribute } from '../../../../../chunks/index.js';
import { p as page } from '../../../../../chunks/stores.js';
import { l as lessonsById } from '../../../../../chunks/stores2.js';
import dayjs from 'dayjs';

const _page_svelte_svelte_type_style_lang = '';

/* src/routes/courses/[code]/day-[day]/+page.svelte generated by Svelte v3.55.0 */

const css = {
	code: "nav.svelte-1dczepf ul.svelte-1dczepf{display:flex;justify-content:space-between;list-style:none;padding-left:0}nav.svelte-1dczepf a.svelte-1dczepf{display:block;background:lightgrey;padding:.5rem 1.75rem;border-radius:0.5rem;text-decoration:none}nav.svelte-1dczepf a.svelte-1dczepf:hover{background:var(--lightAccent)}nav.svelte-1dczepf span.svelte-1dczepf{display:block;padding:1rem 1.5rem}nav.svelte-1dczepf time.svelte-1dczepf{display:block;font-size:1.5rem;font-weight:bold;padding:.5rem;color:grey}",
	map: null
};

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $page, $$unsubscribe_page;
	let $lessonsById, $$unsubscribe_lessonsById;
	$$unsubscribe_page = subscribe(page, value => $page = value);
	$$unsubscribe_lessonsById = subscribe(lessonsById, value => $lessonsById = value);
	let { data } = $$props;
	const lesson = $lessonsById[`${$page.params.code}/${$page.params.day}`];
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);
	$$unsubscribe_page();
	$$unsubscribe_lessonsById();

	return `<nav class="${"page-nav svelte-1dczepf"}"><ul class="${"svelte-1dczepf"}">${lesson.prev
	? `<li><a href="${"/courses/" + escape(lesson.prev, true)}" class="${"svelte-1dczepf"}">Prev</a></li>`
	: `<li><span class="${"svelte-1dczepf"}">Prev</span></li>`}
    <li><time${add_attribute("datetime", lesson.date, 0)} class="${"svelte-1dczepf"}">${escape(dayjs(lesson.date).format('dddd, MMM D'))}</time></li>
    ${lesson.next
	? `<li><a href="${"/courses/" + escape(lesson.next, true)}" class="${"svelte-1dczepf"}">Next</a></li>`
	: `<li><span class="${"svelte-1dczepf"}">Next</span></li>`}</ul></nav>


<h1>${escape(lesson.title)}</h1>


${lesson.status === 'draft'
	? `<p>This lesson has not been released.</p>`
	: `<!-- HTML_TAG_START -->${data.lessonContent}<!-- HTML_TAG_END -->`}`;
});

export { Page as default };
