import { c as create_ssr_component, g as escape, d as add_attribute } from '../../../../../../chunks/index.js';

/* src/routes/courses/[code]/assessments/[slug]/+page.svelte generated by Svelte v3.55.0 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `<h1>${escape(data.meta.title)}</h1>
<p>Weight: ${escape(data.meta.points)}%</p>
${data.meta.due
	? `<p>Due: <time${add_attribute("datetime", data.meta.due, 0)}>${escape(data.meta.due)}</time></p>`
	: `<p>Due: TBA</p>`}

${data.meta.status === 'draft'
	? `<p>This assessment has not been released.</p>`
	: `<!-- HTML_TAG_START -->${data.content}<!-- HTML_TAG_END -->`}`;
});

export { Page as default };
