import { c as create_ssr_component, b as subscribe, f as each, g as escape } from '../../../chunks/index.js';
import { c as courses } from '../../../chunks/stores2.js';

/* src/routes/courses/+page.svelte generated by Svelte v3.55.0 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $courses, $$unsubscribe_courses;
	$$unsubscribe_courses = subscribe(courses, value => $courses = value);
	$$unsubscribe_courses();

	return `${($$result.head += '<!-- HEAD_svelte-187c5u2_START -->' + `${($$result.title = `<title>Courses</title>`, "")}` + '<!-- HEAD_svelte-187c5u2_END -->', "")}

<h1>Courses</h1>
<section class="${"course-list"}">${each($courses, course => {
		return `${course.type === 'technical'
		? `<a href="${"courses/" + escape(course.code, true)}"><article class="${"course"}"><h2>${escape(course.code.toUpperCase().replace('-', ' '))}</h2>
			<h3>${escape(course.title)}</h3>
			<p>Days: ${escape(course.days)}</p></article>
	</a>`
		: ``}`;
	})}</section>`;
});

export { Page as default };
