import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpln-240/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Guest Speaker Day",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _01_day_1 as default, metadata };
