import { c as create_ssr_component, v as validate_component } from './index.js';

/* src/lib/components/Homework.svelte generated by Svelte v3.55.0 */

const Homework = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { status } = $$props;
	if ($$props.status === void 0 && $$bindings.status && status !== void 0) $$bindings.status(status);

	return `<section class="${"homework"}">${status === 'announced' || status === 'published'
	? `${slots.default ? slots.default({}) : ``}`
	: ``}</section>`;
});

/* src/lib/components/LessonPlan.svelte generated by Svelte v3.55.0 */

const LessonPlan = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { status } = $$props;
	if ($$props.status === void 0 && $$bindings.status && status !== void 0) $$bindings.status(status);

	return `<section class="${"lesson-plan"}">${status == 'published'
	? `${slots.default ? slots.default({}) : ``}`
	: ``}</section>`;
});

/* src/lib/components/LabTime.svelte generated by Svelte v3.55.0 */

const LabTime = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { status } = $$props;
	if ($$props.status === void 0 && $$bindings.status && status !== void 0) $$bindings.status(status);

	return `<section class="${"lab-time"}">${status === 'announced' || status === 'published'
	? `${slots.default ? slots.default({}) : ``}`
	: ``}</section>`;
});

/* src/lib/content/courses/cpnt-260/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Introduction to HTML and CSS",
	"excerpt": null,
	"status": "draft"
};

const { title, excerpt, status } = metadata;

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${validate_component(LabTime, "LabTime").$$render($$result, { status }, {}, {
		default: () => {
			return `<h2 id="${"daily-achievement"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#daily-achievement"}"><span class="${"icon icon-link"}"></span></a>Daily Achievement</h2>
<p>Blah, blah, blah.</p>`;
		}
	})}
${validate_component(LessonPlan, "LessonPlan").$$render($$result, { status }, {}, {
		default: () => {
			return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>How Tony takes attendance</li>
<li><a href="${"/courses/cpnt-260/assessments/assignment-1"}">Assignment 1: Text column</a></li>
<li><a href="${"/courses/cpnt-260/assessments/achievements-1"}">Achievements Round 1</a><ul><li>Issue 1: We need more Above and Beyonds!</li>
<li>Issue 2: Project Board instructions missing</li>
<li>Issue 3: Moodboard instructions missing</li></ul></li>
<li><a href="${"https://codepen.io/"}" rel="${"nofollow"}">Create Codepen account</a></li></ul>
<hr>
<h2 id="${"1-installing-ssh-keys"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-installing-ssh-keys"}"><span class="${"icon icon-link"}"></span></a>1. Installing SSH Keys</h2>
<ul><li>See: <a href="${"/courses/cpnt-201/day-3"}">Previous Day</a><ul><li><a href="${"https://gist.github.com/acidtone/dd9ae11a238e9f14ad0b066298f35dc5"}" rel="${"nofollow"}">Connecting to GitHub using SSH</a></li></ul></li></ul>
<hr>
<h2 id="${"2-finding-help-information-and-inspiration"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-finding-help-information-and-inspiration"}"><span class="${"icon icon-link"}"></span></a>2. Finding help, information and inspiration</h2>
<p>The Web is your friend.</p>
<h3 id="${"breakout-discussion"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#breakout-discussion"}"><span class="${"icon icon-link"}"></span></a>Breakout discussion</h3>
<p>In groups of 3-4, take turns discussing the video/article that interested you (aka. your homework):</p>
<ul><li>Why did this video/article interest you?</li>
<li>When was it published? Does it matter?</li>
<li>How do you know the author is credible?</li></ul>
<p><strong>Top Picks</strong></p>
<ol><li>Take turns presenting your choice of video/article;</li>
<li>Discuss it with the group by asking the guiding questions above;</li>
<li>As a group vote on the top ranked video/article;</li>
<li>Nominate a group member to present your top picks!</li></ol>
<p><strong>Watch party nominations!</strong>
We’ll add the top picks to Slack and vote on the best of the best for the Watch Party this afternoon!</p>
<hr>
<h2 id="${"3-slides-building-a-better-search-phrase"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-slides-building-a-better-search-phrase"}"><span class="${"icon icon-link"}"></span></a>3. Slides: Building a better search phrase</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/better-search-phrases.html"}" rel="${"nofollow"}"><img src="${"/images/slides/better-search-phrases.png"}" alt="${"Better Search Phrase Slides"}"></a></p>
<h3 id="${"breakout-discussion-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#breakout-discussion-1"}"><span class="${"icon icon-link"}"></span></a>Breakout discussion</h3>
<p>In groups of 3-4, discuss some search phrases you’ve used to find helpful resources in this program so far.</p>
<ul><li>Were any words specific to the industry of web development? What were they?</li>
<li>How many words did you use?</li>
<li>What problem were you trying to solve?</li></ul>
<hr>
<h2 id="${"watch-party"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-party"}"><span class="${"icon icon-link"}"></span></a>Watch party!</h2>
<p>Vote on the day’s top ranked video(s) in Slack (eventually).</p>`;
		}
	})}
${validate_component(Homework, "Homework").$$render($$result, { status }, {}, {
		default: () => {
			return `<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<p>Find a video (&gt; 10 mins) or article (&gt; 350 words) about HTML/CSS that interests you. It should be current, helpful and come from a credible source.</p>
<p>You will be presenting your video-article to your classmates and will be asked:</p>
<ul><li>Why does this video/article interest you?</li>
<li>Given the date of publication, is it still relevant?</li>
<li>How do you know the author is credible?</li></ul>`;
		}
	})}`;
});

export { _01_day_1 as default, metadata };
