import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-200/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Intro to Headless CMSs",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>9am start for the duration of CPNT 200; back to 8am starts for CPNT 262;</li>
<li>Extension for CPNT 262 Inidividual Project: Friday, November 4th @ 11:59pm;</li></ul>
<hr>
<h2 id="${"1-intro-to-headless-cmss"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-intro-to-headless-cmss"}"><span class="${"icon icon-link"}"></span></a>1. Intro to headless CMSs</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-200/side-gigs.html"}" rel="${"nofollow"}"><img src="${"/images/slides/side-gigs.png"}" alt="${"Slides - Side Gigs"}"></a></p>
<hr>
<h2 id="${"2-overview-of-strapi-admin-panel"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-overview-of-strapi-admin-panel"}"><span class="${"icon icon-link"}"></span></a>2. Overview of Strapi Admin Panel</h2>
<ul><li><a href="${"https://docs.strapi.io/user-docs/latest/getting-started/introduction.html"}" rel="${"nofollow"}">User Guide</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html"}" rel="${"nofollow"}">Developer Documentation</a></li></ul>
<p><strong>Installation</strong></p>
<ol><li>Create new Strapi project:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">$ npx create-strapi-app@latest my-project --quickstart</code>`}<!-- HTML_TAG_END --></pre></li>
<li>In the admin panel, create your admin user<ul><li>Name or user handle</li>
<li>Email: user your real email</li>
<li>Password: must contain a capital letter and number</li></ul></li></ol>
<hr>
<h2 id="${"3-assessment-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-assessment-overview"}"><span class="${"icon icon-link"}"></span></a>3. Assessment Overview</h2>
<ul><li><a href="${"/courses/cpnt-200/assessments/achievements"}">CPNT 200 Content Achievements</a></li>
<li><a href="${"/courses/cpnt-200/assessments/assignment-1"}">CPNT 200 Assignment 1</a></li></ul>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<ul><li>CPNT 262 Individual Project</li>
<li><a href="${"/courses/cpnt-200/assessments/achievements"}">CPNT 200 Content Achievements</a></li>
<li><a href="${"/courses/cpnt-200/assessments/assignment-1"}">CPNT 200 Assignment 1</a></li></ul>`;
});

export { _01_day_1 as default, metadata };
