import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 1 Orientation & DSGN 270 Setup",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"orientation"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#orientation"}"><span class="${"icon icon-link"}"></span></a>Orientation</h2>
<h3 id="${"instructor-information"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructor-information"}"><span class="${"icon icon-link"}"></span></a>Instructor Information</h3>
<p><em>Methods of Contacting Ashlyn Knox and Tony Grimes</em></p>
<h4 id="${"ashlyn-knox"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#ashlyn-knox"}"><span class="${"icon icon-link"}"></span></a>Ashlyn Knox</h4>
<ul><li>Slack DM (preferred method of contact)</li>
<li>Text: (587)-832-5669</li>
<li>Email: <a href="${"mailto:ashlyn.knox@sait.ca"}">ashlyn.knox@sait.ca</a></li></ul>
<h4 id="${"tony-grimes"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tony-grimes"}"><span class="${"icon icon-link"}"></span></a>Tony Grimes</h4>
<ul><li>Slack DM (preferred method of contact)</li>
<li>Text: (403)-710-3836</li>
<li>Email: <a href="${"mailto:tony.grimes@sait.ca"}">tony.grimes@sait.ca</a></li></ul>
<h3 id="${"impromptu-speed-networking"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#impromptu-speed-networking"}"><span class="${"icon icon-link"}"></span></a>Impromptu Speed Networking</h3>
<ul><li><a href="${"https://gamestorming.com/impromptu-speed-networking/"}" rel="${"nofollow"}">Gamestorming game</a></li>
<li>Time: 20* minutes</li>
<li><strong>Question</strong>: What do you want to create/build while you’re in this program? (alternative: What about web development interests you?)</li>
<li>Game Rules:<ul><li>5 minute 1 on 1 sessions (assigned at random)</li>
<li>3 rounds</li>
<li>Discuss the things that you’d like to create</li></ul></li></ul>
<h3 id="${"what-to-expect"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#what-to-expect"}"><span class="${"icon icon-link"}"></span></a>What to Expect</h3>
<ul><li>A strong horizontal base of web development skills</li>
<li>Experience using modern development tools</li>
<li>Work together in development teams</li>
<li>Find your core strengths and interests to establish your foundation</li></ul>
<h3 id="${"software-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#software-overview"}"><span class="${"icon icon-link"}"></span></a>Software Overview</h3>
<p>You will be responsible for maintaining your development environment for each course in this program. The specific requirements will change from course to course but the following software will be required for the entire program.</p>
<ul><li>Design Software (DSGN-270):<ul><li><a href="${"https://figma.com"}" rel="${"nofollow"}">Figma</a>: Basic Vector Editing and UI Design</li>
<li><a href="${"https://www.figma.com/figjam/"}" rel="${"nofollow"}">Figjam</a>: Whiteboarding Collaboration Software </li>
<li><a href="${"https://www.gimp.org/"}" rel="${"nofollow"}">Gimp</a>: Raster Image Editing</li></ul></li>
<li>Messaging Software:<ul><li><a href="${"https://slack.com/intl/en-ca/downloads/"}" rel="${"nofollow"}">Slack</a><ul><li>Send an email to Tony (<a href="${"mailto:tony.grimes@sait.ca"}">tony.grimes@sait.ca</a>) from the email address you’d like your Slack invite sent to. Keep in mind that your SAIT email will eventually be retired after graduation. </li></ul></li></ul></li>
<li>Programming Software (starting CPNT-201):<ul><li><a href="${"https://code.visualstudio.com/"}" rel="${"nofollow"}">Vscode</a>: Desktop Code Editor</li>
<li><a href="${"https://codepen.io"}" rel="${"nofollow"}">Codepen</a> Browser Based HTML, CSS, JS Editor</li>
<li><a href="${"https://github.com"}" rel="${"nofollow"}">Github</a> Git Version Control Software</li></ul></li></ul>
<h2 id="${"dsgn-270-introduction"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#dsgn-270-introduction"}"><span class="${"icon icon-link"}"></span></a>DSGN 270 Introduction</h2>
<p>DSGN 270 is all about User Experience (UX) and User Interface (UI) design for Developers. We will take a practical approach to learning the theory and application of design in web development.</p>
<h3 id="${"software-setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#software-setup"}"><span class="${"icon icon-link"}"></span></a>Software Setup</h3>
<ul><li>Set up a Figma Account</li></ul>
<h3 id="${"affinity-map-activity"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#affinity-map-activity"}"><span class="${"icon icon-link"}"></span></a>Affinity Map Activity</h3>
<ul><li><a href="${"https://gamestorming.com/?s=affinity+map"}" rel="${"nofollow"}">Gamestorming Affinity Map Activity</a></li>
<li>Time: 30* minutes</li>
<li>In Figjam we will collaboratively write down ideas that stood out in our networking session</li>
<li>Then we will take a few minutes to group them into clusters</li>
<li>This is a useful strategy early on in a project. It helps:<ul><li>Find patterns</li>
<li>See which ideas are common in a group</li>
<li>Break out of ruts</li></ul></li></ul>
<h2 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h2>
<ul><li>Read: <a href="${"https://www.nngroup.com/articles/usability-101-introduction-to-usability/"}" rel="${"nofollow"}">Usability 101: NN Group</a></li>
<li>Watch: <a href="${"https://www.youtube.com/watch?v=9gM8K4ooavY"}" rel="${"nofollow"}">UX Design Basics: Mental Models</a></li>
<li>Skim Chapters 1, 2, 3 of “Don’t Make Me Think” by Steve Krug</li>
<li>Find an item in your house that represents either good or bad design (we will be discussing these in class tomorrow)</li></ul>`;
});

export { _01_day_1 as default, metadata };
