import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-201/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 1 - Markdown, Kanban, and Project Organization",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"introduction-to-markdown"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#introduction-to-markdown"}"><span class="${"icon icon-link"}"></span></a>Introduction to Markdown</h2>
<p>Markdown is a simple markup language used by developers around the world. It’s used to write README files, documentation, notes, and even some parts of websites (all of the lesson material in this course is written in markdown).</p>
<ul><li><a href="${"https://www.markdownguide.org/"}" rel="${"nofollow"}">Markdown Guide</a></li></ul>
<p>It is also used in many project boards to add text formatting. Some examples of project boards that use markdown are: </p>
<ul><li><a href="${"https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects"}" rel="${"nofollow"}">Github Projects</a></li>
<li><a href="${"https://trello.com"}" rel="${"nofollow"}">Trello</a></li>
<li><a href="${"https://docs.gitlab.com/ee/user/project/issue_board.html"}" rel="${"nofollow"}">Gitlab Boards</a>. </li></ul>
<p><strong>For this course we use github projects as your code will be hosted on github</strong></p>
<h3 id="${"markdown-basics"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#markdown-basics"}"><span class="${"icon icon-link"}"></span></a>Markdown basics</h3>
<ul><li><a href="${"https://www.markdownguide.org/basic-syntax/"}" rel="${"nofollow"}">Basic Syntax Guide</a></li>
<li>Use markdown for formatting:<ul><li>headings</li>
<li>body text (bold, italics, underline…)</li>
<li>lists (ordered, unordered)</li>
<li>hyperlinks</li>
<li>images</li>
<li><strong>adding visual hierarchy to a document</strong></li></ul></li></ul>
<h3 id="${"review-and-walkthrough-of-markdown-syntax"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#review-and-walkthrough-of-markdown-syntax"}"><span class="${"icon icon-link"}"></span></a>Review and Walkthrough of Markdown Syntax</h3>
<ul><li>Answer Questions</li>
<li>Go over examples</li></ul>
<h3 id="${"collaborative-markdown"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#collaborative-markdown"}"><span class="${"icon icon-link"}"></span></a>Collaborative Markdown</h3>
<ul><li>We can write documents together in real time with markdown using tools like <a href="${"https://hackmd.io"}" rel="${"nofollow"}">Hackmd</a> <ul><li>Hackmd is great because it can push directly to a github repo, it can be shared, edited, and read by many people</li></ul></li>
<li>Sign up on hackmd for some of our activities today</li></ul>
<h3 id="${"in-class-activity-10-minutes"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#in-class-activity-10-minutes"}"><span class="${"icon icon-link"}"></span></a>In class activity (10 minutes)</h3>
<ul><li>Think of a job, game, sport, task, something that you have a lot of experience doing (you’ll be using this in a paired activity later)</li>
<li>Create a new document and add the following (rely on the basic syntax guide linked above)<ul><li>An h1 heading <code># Name of activity</code></li>
<li>A very short description of the activity (just write)</li>
<li>An h2 heading <code>## Task List</code></li>
<li>A list of steps involved in your task <strong>or</strong> your task’s responsibilities (ordered with numbers or unordered with dashes)</li>
<li>Include a link to a website that relates to your activity in some way <code>[text that is seen](https://pathtosite.org)</code></li></ul></li></ul>
<h3 id="${"break-15-min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-min"}"><span class="${"icon icon-link"}"></span></a>Break 15 Min</h3>
<h2 id="${"welcome-to-my-world-activity"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#welcome-to-my-world-activity"}"><span class="${"icon icon-link"}"></span></a><a href="${"https://gist.github.com/lilyx13/2a352a7516c9ce8cb6addb1afec15217"}" rel="${"nofollow"}">Welcome to My World Activity</a></h2>
<ul><li>time: 20 minutes</li>
<li>Teams: Work in pairs</li>
<li>Goals:<ul><li>Practice markdown syntax</li>
<li>Visualize jobs in a series of steps</li></ul></li></ul>
<h3 id="${"debrief"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ul><li>Did you have a fairly different interpretation of your team members job breakdown?</li></ul>
<h3 id="${"break"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break"}"><span class="${"icon icon-link"}"></span></a>Break</h3>
<h2 id="${"kanban-and-github-project-boards"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#kanban-and-github-project-boards"}"><span class="${"icon icon-link"}"></span></a>Kanban and Github Project Boards</h2>
<p>Kanban boards are used to organize projects. They are used in <a href="${"https://project-management.com/agile-project-management/"}" rel="${"nofollow"}">Agile Project Management</a> among others. You can simply use them to keep track of your own project without being in a formal team structure (which is how we will start using kanban boards).</p>
<h3 id="${"basics-of-your-project-board"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#basics-of-your-project-board"}"><span class="${"icon icon-link"}"></span></a>Basics of Your Project Board</h3>
<ol><li>Status States<ul><li>TODO </li>
<li>Doing</li>
<li>Done</li>
<li>Blocked</li></ul></li>
<li>Issues<ul><li>Tasks, bugs, action items etc.</li>
<li>Comprised of (at minimum):<ul><li>A title</li>
<li>A description</li>
<li>A comment section</li></ul></li>
<li>Organize based on status in your kanban board</li></ul></li>
<li>Labels<ul><li>Use labels to group types of tasks. Ie:<ul><li>bug</li>
<li>priority levels</li>
<li>enhancement</li>
<li>documentation</li>
<li>easyfix</li></ul></li></ul></li></ol>
<h4 id="${"things-to-include-in-issues"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#things-to-include-in-issues"}"><span class="${"icon icon-link"}"></span></a>Things to include in issues</h4>
<ul><li>Context: describe the issue and necessary background information</li>
<li>Definition of Done: the things that need to be accomplished for the issue to be considered resolved</li></ul>
<h3 id="${"examples-from-ashlyns-projects"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#examples-from-ashlyns-projects"}"><span class="${"icon icon-link"}"></span></a>Examples from Ashlyn’s Projects</h3>
<ul><li><a href="${"https://github.com/users/lilyx13/projects/2"}" rel="${"nofollow"}">Ashlyn’s Website on Github</a></li>
<li><a href="${"https://gitlab.com/groups/fedora/websites-apps/fedora-websites/-/boards/4623394"}" rel="${"nofollow"}">Fedora Linux Website Revamp Project Board on Gitlab</a></li></ul>
<h2 id="${"activity-kanban-pizza-party"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-kanban-pizza-party"}"><span class="${"icon icon-link"}"></span></a>Activity: <a href="${"https://gist.github.com/lilyx13/87b993df6d5127bb91d9d946991a36f6"}" rel="${"nofollow"}">Kanban Pizza Party</a></h2>
<ul><li>Duration: 30* minutes</li>
<li>Team Size: 4</li>
<li>Goal: Build a project board in github that shows how to make a pizza</li>
<li>Submit a link to your github project by the end of the day for a late start on tuesday</li></ul>`;
});

export { _01_day_1 as default, metadata };
