import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-264/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Career and Consulting Services",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p>Dasa Chadwick will email you with meeting details. Assignments for CPNT 264 can be found in Brightspace.</p>`;
});

export { _01_day_1 as default, metadata };
