import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Business of the Web (Final Projects)",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Double points (10 points) if you submit your Card Info by 3 pm today.</li></ul>
<hr>
<h2 id="${"1-cpnt-265-course-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-cpnt-265-course-overview"}"><span class="${"icon icon-link"}"></span></a>1. CPNT 265 Course Overview</h2>
<ul><li><a href="${"/courses/cpnt-265/assessments"}">Course Assessments</a><ul><li><a href="${"/courses/cpnt-265/assessments/final-project/"}">Final Project presentation</a><ul><li>Weight: 30% of final course mark</li>
<li>Held Friday, December 16th @ 9am</li>
<li>See: <a href="${"https://sait-wbdv.github.io/"}" rel="${"nofollow"}">Last semesters presentation agenda</a></li></ul></li>
<li><a href="${"/courses/cpnt-265/assessments/achievements-1"}">Achievements Round 1</a><ul><li>Weight: 25% of final course mark</li>
<li>Due: Thursday, December 8th @ 11:59pm</li>
<li>These achievements are flexible. If you find a potential achievement that is not listed, ask one of the Instructors/Facilitators if it can be added to the list!</li></ul></li>
<li>DRAFT - <a href="${"/courses/cpnt-265/assessments/achievements-2"}">Achievements Round 2</a><ul><li>Announced Wednesday</li>
<li>Weight: 45% of final course mark</li>
<li>Due: Wednesday, December 14th @ 11:59pm</li>
<li>Round 1 Achievements will be eligible for this Round</li></ul></li></ul></li></ul>
<hr>
<h2 id="${"2-call-for-sessions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-call-for-sessions"}"><span class="${"icon icon-link"}"></span></a>2. Call for Sessions</h2>
<p>There are no set lessons for this course. Tony will teach/demo/review any topics you need to complete your final project. Let him know what you’d like to see and he’ll try his best.</p>
<h3 id="${"previous-sessions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#previous-sessions"}"><span class="${"icon icon-link"}"></span></a>Previous sessions</h3>
<ul><li>Authenticated GitHub API</li>
<li>Svelte</li>
<li>Contracting as a Developer</li>
<li>E-commerce platforms</li>
<li>Pull Requests</li>
<li>UX: User Stories and Task Flows</li>
<li>Wordpress</li>
<li>MySQL</li></ul>
<hr>
<h2 id="${"3-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-lab-time"}"><span class="${"icon icon-link"}"></span></a>3. Lab Time</h2>
<p>Breakout rooms will be opened after Course Overview and questions, comments, discussion.</p>
<hr>
<h2 id="${"notes-for-tony"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#notes-for-tony"}"><span class="${"icon icon-link"}"></span></a>Notes for Tony</h2>
<h3 id="${"262-group-assignments"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#262-group-assignments"}"><span class="${"icon icon-link"}"></span></a>262 Group Assignments</h3>
<ol><li>Eli - Lucas</li>
<li>Rustu - Darryl</li>
<li>May - Jesse</li>
<li>Ashley - Myka</li>
<li>Jian - Cordelle</li>
<li>Akash - Dohyeong</li>
<li>Deoj - Mesut - Preetpal</li></ol>`;
});

export { _01_day_1 as default, metadata };
