import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/01-day-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Introduction to Javascript",
	"excerpt": null,
	"status": "draft"
};

const _01_day_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>CPNT 260 marks returned for:<ul><li>Achievements Round 2</li>
<li>Assignment 3: Sticky Footers</li></ul></li>
<li>CPNT 260 Assignment 4 returned tomorrow;</li></ul>
<hr>
<h2 id="${"1-sticky-footer-walk-through"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-sticky-footer-walk-through"}"><span class="${"icon icon-link"}"></span></a>1. Sticky footer walk-through</h2>
<ul><li><a href="${"https://github.com/sait-wbdv/f22-spoilers-cpnt260-a3/"}" rel="${"nofollow"}">GitHub repo</a></li>
<li><a href="${"https://sait-wbdv.github.io/f22-spoilers-cpnt260-a3/"}" rel="${"nofollow"}">Live site</a></li></ul>
<hr>
<h2 id="${"2-slides-introduction-to-javascript"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-slides-introduction-to-javascript"}"><span class="${"icon icon-link"}"></span></a>2. Slides: Introduction to Javascript</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-introduction.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-intro.png"}" alt="${"Introduction to Javascript"}"></a></p>
<h3 id="${"demo-installing-a-js-library-revealjs-using-a-cdn"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-installing-a-js-library-revealjs-using-a-cdn"}"><span class="${"icon icon-link"}"></span></a>Demo: Installing a JS library (RevealJS) using a CDN</h3>
<ul><li><a href="${"https://revealjs.com/installation/"}" rel="${"nofollow"}">Installation</a><ul><li>Note: these instructions don’t include the CDN method;</li></ul></li>
<li><a href="${"https://revealjs.com/demo/"}" rel="${"nofollow"}">Live Demo</a></li>
<li><a href="${"https://revealjs.com/markup/"}" rel="${"nofollow"}">Marking up Slides</a></li>
<li><a href="${"https://revealjs.com/config/"}" rel="${"nofollow"}">Config Options</a></li></ul>
<hr>
<h2 id="${"3-activity-group-project-slide-deck"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-activity-group-project-slide-deck"}"><span class="${"icon icon-link"}"></span></a>3. Activity: Group project slide deck</h2>
<p><em>Not for marks</em></p>
<p><a href="${"https://gist.github.com/acidtone/5ade98e682f62f8fafd34d24dca03066"}" rel="${"nofollow"}"><img src="${"https://gist.githubusercontent.com/acidtone/5ade98e682f62f8fafd34d24dca03066/raw/8803ef4375bdd9aad7e8f0a0e41d5eb9186458cc/revealjs-logo.png"}" alt="${"Install RevealJS"}"></a></p>
<p>In your 260 groups, use RevealJS to build a slide deck about your project (don’t worry, there’s no presentation with this project).</p>
<p><strong>Popular configurations</strong>:</p>
<ul><li>Set <code>hash</code> to <code>true</code> to be able to link to individual slides;</li>
<li>Set <code>controls</code> to <code>false</code> to turn off arrows in bottom right corner;<ul><li>Or set <code>controlsLayout</code> to move the controls to another part of the screen;</li></ul></li>
<li>Set <code>history</code> to <code>true</code> to add slide changes to browser history;</li>
<li>Set <code>autoSlide</code> to <code>true</code> to auto advance slides;</li>
<li>Set <code>transition</code> to pick a slide transition (options: <code>none</code>/<code>fade</code>/<code>slide</code>/<code>convex</code>/<code>concave</code>/<code>zoom</code>);</li></ul>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<h3 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h3>
<ul><li><a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk"}" rel="${"nofollow"}">Learn JavaScript in 1 Hour</a> by Mosh</li>
<li>Exercises: <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#basic-javascript"}" rel="${"nofollow"}">Javascript basics</a> on Free Code Camp</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch List</h3>
<p>We’ll be jumping around quite a bit but this is a great introduction to JS that covers most of the topics we’ll be covering.</p>
<ul><li><a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk"}" rel="${"nofollow"}">Learn JavaScript in 1 Hour</a> by Mosh<ul><li>00:00 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk"}" rel="${"nofollow"}">What is JavaScript</a></li>
<li>04:41 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=281s"}" rel="${"nofollow"}">Setting Up the Development Environment</a></li>
<li>07:52 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=472s"}" rel="${"nofollow"}">JavaScript in Browsers</a></li>
<li>11:41 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=701s"}" rel="${"nofollow"}">Separation of Concerns</a></li>
<li>13:47 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=827s"}" rel="${"nofollow"}">JavaScript in Node</a></li>
<li>16:11 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=971s"}" rel="${"nofollow"}">Variables</a></li>
<li>21:49 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=1309s"}" rel="${"nofollow"}">Constants</a></li>
<li>23:35 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=1415s"}" rel="${"nofollow"}">Primitive Types</a></li>
<li>26:47 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=1607s"}" rel="${"nofollow"}">Dynamic Typing </a></li>
<li>30:06 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=1806s"}" rel="${"nofollow"}">Objects</a></li>
<li>35:22 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2122s"}" rel="${"nofollow"}">Arrays</a></li>
<li>39:41 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2122s"}" rel="${"nofollow"}">Functions</a></li>
<li>44:22 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2662s"}" rel="${"nofollow"}">Types of Functions</a></li></ul></li></ul>
<h3 id="${"optional-other-courses-and-resources"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#optional-other-courses-and-resources"}"><span class="${"icon icon-link"}"></span></a>Optional: Other courses and resources</h3>
<p>There are a lot of free courses and textbooks that you can also refer to. Some favourites from past students:</p>
<ul><li>Freecode Camp: <ul><li><a href="${"https://www.freecodecamp.org/news/full-javascript-course-for-beginners/"}" rel="${"nofollow"}">Full JavaScript Course for Beginners</a></li>
<li>Exercises: <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#basic-javascript"}" rel="${"nofollow"}">Javascript basics</a></li></ul></li>
<li>Code Academy: <a href="${"https://www.codecademy.com/learn/introduction-to-javascript"}" rel="${"nofollow"}">Introduction to Javascript</a></li>
<li>Online textbook: <a href="${"https://eloquentjavascript.net/"}" rel="${"nofollow"}">Eloquent Javascript</a> by Marijn Haverbeke</li></ul>`;
});

export { _01_day_1 as default, metadata };
