import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/02-day-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 2 - Usability and Design",
	"excerpt": null,
	"status": "draft"
};

const _02_day_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"assignment-1-moodboard"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignment-1-moodboard"}"><span class="${"icon icon-link"}"></span></a>Assignment 1: Moodboard</h2>
<ul><li>Due: <strong>Friday September 9</strong></li>
<li>Objective: Create a Moodboard for a website in Figjam</li>
<li>Important Content:<ul><li>Design Concept</li>
<li>Color themes</li>
<li>Screenshots of UI elements for inspiration</li>
<li>Visual hierarchy used in moodboard to show ideas</li></ul></li></ul>
<h2 id="${"morning-activity-graphic-jam"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#morning-activity-graphic-jam"}"><span class="${"icon icon-link"}"></span></a>Morning Activity: <a href="${"https://gist.github.com/lilyx13/0e34897d7f01f96f68666438de00d347"}" rel="${"nofollow"}">Graphic Jam</a></h2>
<ul><li>Time: 45 minutes to 1 hour</li>
<li>1 full class run through with 3 participants</li>
<li>Structure: 3 groups of 8* (1 person will act as facilitator)</li>
<li>Tool: Figjam</li></ul>
<h3 id="${"debrief-20-min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief-20-min"}"><span class="${"icon icon-link"}"></span></a>Debrief (20* min)</h3>
<ul><li>Each team will get a chance to talk about their favourite board<ul><li>Facilitator screen shares</li>
<li>Team members talk about their images</li></ul></li></ul>
<h3 id="${"break-15-min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-min"}"><span class="${"icon icon-link"}"></span></a>Break 15 Min</h3>
<h2 id="${"what-is-a-moodboard"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#what-is-a-moodboard"}"><span class="${"icon icon-link"}"></span></a>What is a Moodboard?</h2>
<ul><li><a href="${"https://www.freecodecamp.org/news/what-is-a-moodboard/"}" rel="${"nofollow"}">What is a Moodboard: Freecodecamp Article</a></li>
<li>Ways to establish a design concept</li>
<li>Find inspiration for color, typefaces, tone, imagery, emotion, identity…</li>
<li>Moodboards are used to communicate with clients, to establish a base pattern of styles, to gather stock content, and to brainstorm</li>
<li>Tools commonly used:<ul><li>Figma or Figjam</li>
<li>Pinterest (great for getting your client to drop ideas into a space for you to look at)</li>
<li>Any other whiteboarding software could work</li>
<li>Manually with pen, paper, and images</li></ul></li></ul>
<h3 id="${"go-over-assignment-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#go-over-assignment-1"}"><span class="${"icon icon-link"}"></span></a>Go over Assignment 1</h3>
<ul><li>Questions</li></ul>
<h3 id="${"break"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break"}"><span class="${"icon icon-link"}"></span></a>Break</h3>
<hr>
<h2 id="${"usability"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#usability"}"><span class="${"icon icon-link"}"></span></a>Usability</h2>
<p><em>How we make information easy to access in web space</em></p>
<h3 id="${"activity-usability-and-goodbad-design-of-items-from-home"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-usability-and-goodbad-design-of-items-from-home"}"><span class="${"icon icon-link"}"></span></a>Activity: Usability and good/bad design of items from home</h3>
<ul><li>In small groups, talk about the items that you found around your house<ul><li>In what way are they good or bad design</li>
<li>Are there any mental models or metaphors at play with your item? or is that item the basis for a digital metaphor (think about the mental models video)</li></ul></li>
<li>After about 15 minutes discuss items as a class (1 or 2 from each group)<ul><li>If you didn’t participate in the first debrief, participate in this one</li></ul></li></ul>
<h3 id="${"terminology"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#terminology"}"><span class="${"icon icon-link"}"></span></a>Terminology</h3>
<ul><li>Usability : A quality attribute that assesses how easy user interfaces are to use. The word “usability” also refers to methods for improving ease-of-use during the design process.</li>
<li>Information Hierarchy : A discipline that focuses on organizing, structuring, and labeling content in an effective and sustainable way. </li>
<li>Satisfice : When a user chooses the first reasonable option instead of the best option.</li>
<li>Interaction Cost : The sum of efforts — mental and physical — that the users must deploy in interacting with a site in order to reach their goals.</li></ul>
<h3 id="${"satisficing"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#satisficing"}"><span class="${"icon icon-link"}"></span></a>Satisficing</h3>
<p>Unless faced with life-changing information, most site visitors won’t read all of the content provided but settle for a “good-enough” answer. Better sorting and clearer writing satisfy users without exhausting the limited time they’re willing to spend on a website.</p>
<p>How we really use the web:</p>
<ol><li>We don’t read pages. we scan them.</li></ol>
<ul><li><a href="${"https://www.nngroup.com/articles/text-scanning-patterns-eyetracking/"}" rel="${"nofollow"}">Text Scanning Patterns: Eyetracking Evidence</a></li></ul>
<ol start="${"2"}"><li>We don’t make optimal choices. We satisfice.
<a href="${"https://www.nngroup.com/articles/satisficing/"}" rel="${"nofollow"}">Satisficing</a></li>
<li>We don’t figure out how things work. We muddle through.
<a href="${"https://www.nngroup.com/articles/information-foraging/"}" rel="${"nofollow"}">Information foraging</a>
<em>Source: Don’t Make Me Think by Steve Krug</em></li></ol>
<h3 id="${"usable-sitesapps-minimize-interaction-cost"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#usable-sitesapps-minimize-interaction-cost"}"><span class="${"icon icon-link"}"></span></a>Usable sites/apps minimize Interaction Cost</h3>
<p>Throughout this program we will be making design decisions that will (hopefully) maximize the usability of our websites and applications by minimizing interaction costs for the user. We do this by <strong><em><em>minimizing</em></em></strong>:</p>
<ul><li><strong>Reading</strong><ul><li><a href="${"https://www.nngroup.com/articles/inverted-pyramid/"}" rel="${"nofollow"}">Inverted Pyramid: Writing for Comprehension</a></li>
<li><a href="${"https://www.nngroup.com/articles/plain-language-experts/"}" rel="${"nofollow"}">Plain Language Is for Everyone, Even Experts</a></li></ul></li>
<li><strong>Scrolling</strong><ul><li><a href="${"https://www.nngroup.com/articles/scrolling-and-attention/"}" rel="${"nofollow"}">Scrolling and Attention</a></li>
<li>Video: <a href="${"https://www.nngroup.com/videos/fold-manifesto/"}" rel="${"nofollow"}">The Fold Manifesto: How to Encourage Scrolling</a></li></ul></li>
<li><strong>Looking around in order to find relevant information</strong><ul><li><a href="${"https://www.nngroup.com/articles/information-foraging/"}" rel="${"nofollow"}">Information foraging</a></li></ul></li>
<li><strong>Comprehending information presented to you</strong><ul><li><a href="${"https://www.nngroup.com/articles/get-started/"}" rel="${"nofollow"}">Don’t use “Read more”, “Get started”…</a></li></ul></li>
<li><strong>Clicking or touching (without making mistakes)</strong><ul><li><a href="${"https://www.nngroup.com/articles/clickable-elements/"}" rel="${"nofollow"}">Making Clickable Elements Recognizable</a></li></ul></li>
<li><strong>Typing</strong><ul><li><a href="${"https://www.nngroup.com/articles/web-form-design/"}" rel="${"nofollow"}">Website Forms Usability: Top 10 Recommendations</a></li></ul></li>
<li><strong>Page loads and waiting times</strong><ul><li><a href="${"https://www.nngroup.com/articles/the-need-for-speed/"}" rel="${"nofollow"}">The Need for Speed, 23 Years Later</a></li></ul></li>
<li><strong>Attention switches</strong><ul><li><a href="${"https://www.nngroup.com/articles/attention-economy/"}" rel="${"nofollow"}">Attention Economy</a></li></ul></li>
<li><strong>Memory load</strong> ­— the information that users must remember in order to complete their task.<ul><li>Video: <a href="${"https://www.nngroup.com/videos/magical-number-7-ux/"}" rel="${"nofollow"}">The Magical Number 7 and UX</a></li>
<li><a href="${"https://www.nngroup.com/articles/chunking/"}" rel="${"nofollow"}">How Chunking Helps Content Processing</a></li></ul></li></ul>
<h3 id="${"break-15-minutes"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-minutes"}"><span class="${"icon icon-link"}"></span></a>Break 15 Minutes</h3>
<h2 id="${"common-ui-elements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#common-ui-elements"}"><span class="${"icon icon-link"}"></span></a>Common UI Elements</h2>
<p>To make content <strong>scannable</strong> and hierarchically organized, we use a variety of UI elements to organize content.</p>
<p>For your assignment 1, you will be finding screenshots of UI elements that you like and fit your design concept for inspiration</p>
<h3 id="${"important-elements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#important-elements"}"><span class="${"icon icon-link"}"></span></a>Important Elements</h3>
<ul><li>Headers</li>
<li>Navigation (a class of elements in it’s own)</li>
<li>Lists</li>
<li>Cards</li>
<li>Footers</li>
<li>Hero Sections</li></ul>
<h4 id="${"small-group-activity"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#small-group-activity"}"><span class="${"icon icon-link"}"></span></a>Small Group Activity</h4>
<ul><li>Navigate to: <a href="${"https://ui-patterns.com/patterns"}" rel="${"nofollow"}">Ui-Patterns</a></li>
<li>Search through different elements</li>
<li>Discuss your preferences and instances that you recognize from your favourite websites</li>
<li>Debrief:<ul><li>As a class, each group will talk about 1 element and show one site that reflects that element</li></ul></li></ul>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Work on Assignment 1</li></ul>
<h2 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h2>
<ul><li>Read <a href="${"https://gist.github.com/acidtone/6f8b416c4c409c60148581f7ec806c46"}" rel="${"nofollow"}">Agile User Stories</a></li>
<li>Read <a href="${"https://careerfoundry.com/en/blog/ux-design/what-are-user-flows/"}" rel="${"nofollow"}">What are User FLows in UX Design</a></li>
<li>Watch parts 1,2,3,6 <a href="${"https://www.youtube.com/playlist?list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4"}" rel="${"nofollow"}">New to Figma</a></li>
<li>Review Interaction Cost Links Above</li></ul>`;
});

export { _02_day_2 as default, metadata };
