import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-201/02-day-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 2 The Command Line",
	"excerpt": null,
	"status": "draft"
};

const _02_day_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"kanban-pizza-party-step-2"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#kanban-pizza-party-step-2"}"><span class="${"icon icon-link"}"></span></a>Kanban Pizza Party Step 2</h2>
<ul><li>20 Minutes of trying one another’s kanban Pizza Boards</li></ul>
<h2 id="${"assignment-1-github-project-board"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignment-1-github-project-board"}"><span class="${"icon icon-link"}"></span></a>Assignment 1: Github Project Board</h2>
<ul><li>Due: Friday September 16</li>
<li>Outcome: Practice using github projects, markdown, and the github UI</li></ul>
<h3 id="${"break-15-min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-min"}"><span class="${"icon icon-link"}"></span></a>Break 15 Min</h3>
<h2 id="${"setting-up-your-workspace"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#setting-up-your-workspace"}"><span class="${"icon icon-link"}"></span></a>Setting up your Workspace</h2>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://gist.github.com/acidtone/d77059ec1851eff266339a3df70f6984"}" rel="${"nofollow"}">Files, directories and naming conventions</a></li></ul>
<h2 id="${"vs-code-setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#vs-code-setup"}"><span class="${"icon icon-link"}"></span></a>VS Code setup</h2>
<h3 id="${"materials-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials-1"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://github.com/sait-wbdv/winter-2022/blob/main/content/library/tools/vscode.md"}" rel="${"nofollow"}">VS Code Summary</a></li></ul>
<h3 id="${"activity-vs-code-project-setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-vs-code-project-setup"}"><span class="${"icon icon-link"}"></span></a>Activity <a href="${"https://gist.github.com/lilyx13/37e1bde51175f934eb0b87f87933cc7c"}" rel="${"nofollow"}">VS Code Project Setup</a></h3>
<ul><li>approx 10 minutes</li>
<li>Do Stage 1 of this activity</li></ul>
<h3 id="${"break-and-vim-adventures"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-and-vim-adventures"}"><span class="${"icon icon-link"}"></span></a>Break and Vim Adventures</h3>
<ul><li>1 hour lunch</li>
<li>Afterwards Play <a href="${"https://vim-adventures.com"}" rel="${"nofollow"}">Vim Adventures</a></li>
<li>We will reconvene at 12:30</li></ul>
<h2 id="${"3-command-line-basics"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-command-line-basics"}"><span class="${"icon icon-link"}"></span></a>3. Command line basics</h2>
<p>Command line is very powerful and it’s really helpful for a developer to be familiar with it. There are GUI tools that allow you to work without it as well, but knowing how your computer organizes files, and how to get around from a code perspective is an asset.</p>
<h3 id="${"materials-2"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials-2"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://gist.github.com/acidtone/316d2bd9cf59f841684dbd68ffc3ee95"}" rel="${"nofollow"}">Navigating the file system</a></li></ul>
<h3 id="${"notes"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#notes"}"><span class="${"icon icon-link"}"></span></a>Notes</h3>
<ul><li>Windows users: The Command Prompt is the default terminal application for Windows. Please use Git Bash instead.</li></ul>
<h3 id="${"activity-vs-code-and-command-line-practice"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-vs-code-and-command-line-practice"}"><span class="${"icon icon-link"}"></span></a>Activity: <a href="${"https://gist.github.com/lilyx13/37e1bde51175f934eb0b87f87933cc7c"}" rel="${"nofollow"}">VS Code and Command Line Practice</a></h3>
<ul><li>Do stage 2 of this activity</li></ul>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Work on assignments</li></ul>
<h2 id="${"extras"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#extras"}"><span class="${"icon icon-link"}"></span></a>Extras</h2>
<ul><li><a href="${"https://www.zsh.org/"}" rel="${"nofollow"}">Zsh</a> for a nicer, more configurable shell</li>
<li><a href="${"https://ohmyz.sh/"}" rel="${"nofollow"}">oh-my-zsh</a> to enhance Zsh even further</li></ul>`;
});

export { _02_day_2 as default, metadata };
