import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/02-day-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _02_day_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _02_day_2 as default, metadata };
