import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/02-day-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Numbers, Math and Errors",
	"excerpt": null,
	"status": "draft"
};

const _02_day_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>CPNT 260 Assignment 4 release after lunch</li></ul>
<hr>
<h2 id="${"1-declaring-and-assigning-variables"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-declaring-and-assigning-variables"}"><span class="${"icon icon-link"}"></span></a>1. Declaring and assigning variables</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-variables.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-variables.png"}" alt="${"Slides - declaring and assigning variables"}"></a></p>
<h3 id="${"demo-math-in-javascript"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-math-in-javascript"}"><span class="${"icon icon-link"}"></span></a>Demo: Math in Javascript</h3>
<p><strong>Materials</strong>:</p>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"}" rel="${"nofollow"}">Number</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math"}" rel="${"nofollow"}">Arithmetic operators</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals"}" rel="${"nofollow"}">Template literals</a></li></ul>
<h3 id="${"activity-tip-calculator-refactor"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-tip-calculator-refactor"}"><span class="${"icon icon-link"}"></span></a>Activity: Tip Calculator Refactor</h3>
<p>In pairs, add functionality to the Tip Calculator:</p>
<ul><li><a href="${"https://gist.github.com/acidtone/5c13ec3ff2ea53b7f75ae3692ca944d1"}" rel="${"nofollow"}">Sample code and instructions</a></li></ul>
<hr>
<h2 id="${"2-handling-errors"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-handling-errors"}"><span class="${"icon icon-link"}"></span></a>2. Handling Errors</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-errors.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-errors.png"}" alt="${"Slides - handling errors"}"></a></p>
<h3 id="${"activity-fixing-errors"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-fixing-errors"}"><span class="${"icon icon-link"}"></span></a>Activity: Fixing errors</h3>
<p>In pairs, complete the following activities:</p>
<ul><li>Beginner: <a href="${"https://gist.github.com/acidtone/b9aaf4228a903796a6d8532ffb36d9d7"}" rel="${"nofollow"}">Bug hunt - syntax errors</a></li>
<li>More advanced: <a href="${"https://gist.github.com/acidtone/b4ceaf48115f553c4845b9fb86ad2bb2"}" rel="${"nofollow"}">Fix syntax errors in adding machine</a></li></ul>
<hr>
<h2 id="${"3-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-lab-time"}"><span class="${"icon icon-link"}"></span></a>3. Lab Time</h2>
<ul><li>Finish activities from this morning;</li>
<li>Assignments;</li>
<li>Exercises: <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#basic-javascript"}" rel="${"nofollow"}">Javascript basics</a> on Free Code Camp</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"system-requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#system-requirements"}"><span class="${"icon icon-link"}"></span></a>System Requirements</h3>
<ul><li>Install <a href="${"https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint"}" rel="${"nofollow"}">ES Lint for VS Code</a>, or similar extension.<ul><li>See: <a href="${"https://www.robinwieruch.de/prettier-eslint/"}" rel="${"nofollow"}">How to use Prettier with ESLint</a></li></ul></li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<p>MDN: </p>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"}" rel="${"nofollow"}">Number</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math"}" rel="${"nofollow"}">Arithmetic operators</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals"}" rel="${"nofollow"}">Template literals</a></li></ul>
<h3 id="${"recommended-exercises"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#recommended-exercises"}"><span class="${"icon icon-link"}"></span></a>Recommended exercises</h3>
<ul><li><a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#basic-javascript"}" rel="${"nofollow"}">Javascript basics</a>: Exercises 1-8<ul><li>Start: <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code"}" rel="${"nofollow"}">Comment Your JavaScript Code</a></li>
<li>Complete and Stop (or not): <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-case-sensitivity-in-variables"}" rel="${"nofollow"}">Understanding Case Sensitivity in Variables</a></li></ul></li></ul>`;
});

export { _02_day_2 as default, metadata };
