import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/02-day-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Box Developer Fast Track",
	"excerpt": "In this session we will introduce the three Browser Triad technologies (HTML, CSS, JS) and the Box Model.",
	"status": "draft"
};

const _02_day_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li><a href="${"https://www.youtube.com/watch?v=aHUtMbJw8iA"}" rel="${"nofollow"}">Why is CSS so Weird?</a> by Miriam Suzanne</li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web"}" rel="${"nofollow"}">Getting started with the web</a><ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics"}" rel="${"nofollow"}">HTML Basics</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics"}" rel="${"nofollow"}">CSS Basics</a></li></ul></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“the box model”</li>
<li>“codepen getting started”</li></ul>
<hr>
<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-201/assessments/assignment-2"}">CPNT 201 - Assignment 2</a> is due tonight<ul><li>We’ll review the <code>git add</code>, <code>commit</code> and <code>push</code> process after lunch</li></ul></li>
<li>Late Penalties on Assignments:<ul><li>10% deduction per day;</li>
<li>Assignments will be accepted up to 3 days late.</li></ul></li></ul>
<hr>
<h2 id="${"1-slides-the-browser-triad"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-slides-the-browser-triad"}"><span class="${"icon icon-link"}"></span></a>1. Slides: The Browser Triad</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/browser-triad.html"}" rel="${"nofollow"}"><img src="${"/images/slides/browser-triad.png"}" alt="${"The Browser Triad"}"></a></p>
<h3 id="${"quiz-time-ui-icons-and-the-triad"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#quiz-time-ui-icons-and-the-triad"}"><span class="${"icon icon-link"}"></span></a>Quiz time: UI Icons and the Triad</h3>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/ui-triad-quiz.html"}" rel="${"nofollow"}"><img src="${"/images/slides/ui-quiz.png"}" alt="${"UI Quiz Slides"}"></a>
In groups of 3-4: </p>
<ol><li>Discuss each of the User Interface icons listed in the above;</li>
<li>Decide on which Triad technology (HTML, CSS, JS) the icon is most associated;</li>
<li>Report your answers in the main room.</li></ol>
<hr>
<h2 id="${"2-codepen-tour"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-codepen-tour"}"><span class="${"icon icon-link"}"></span></a>2. Codepen tour</h2>
<ul><li>Create a <a href="${"https://codepen.io/"}" rel="${"nofollow"}">Codepen</a> account.</li>
<li>Search: ”<code>codepen tutorial</code>” or similar</li></ul>
<h3 id="${"lab-pair-coding"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-pair-coding"}"><span class="${"icon icon-link"}"></span></a>Lab: Pair-coding</h3>
<p>In groups of two, decide on which lab you’d like to collab on.</p>
<p>See: <a href="${"https://gist.github.com/acidtone/caa20b2520814a94240043c40301024a"}" rel="${"nofollow"}">Introduction to Pair Programming</a> with Fiona and Semira</p>
<p><strong>Wiki markup</strong>
Use openly licensed text of your choice from Wikipedia or similar service. Code it in HTML using Codepen. Start with the following HTML tags:</p>
<ul><li><code>h1</code>-<code>h3</code>: headings</li>
<li><code>p</code>: paragraphs</li>
<li><code>a</code>: links</li>
<li><code>strong</code>, <code>em</code>: bold and italicize</li>
<li><code>ul</code> and/or <code>ol</code>: unordered and ordered lists</li></ul>
<hr>
<h2 id="${"3-setting-up-dailies-projects-and-assignments-directories"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-setting-up-dailies-projects-and-assignments-directories"}"><span class="${"icon icon-link"}"></span></a>3. Setting up <code>dailies</code>, <code>projects</code> and <code>assignments</code> directories</h2>
<p>It’s recommended that you set up the following directories in your workspace:</p>
<ol><li><code>dailies</code> for day-to-day code as one repo:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">/dailies
    /2022-09-19-box-model
        /topic-1
        /topic-2
    /2022-09-20
        /more-topics</code>`}<!-- HTML_TAG_END --></pre></li>
<li><code>projects</code> for misc repos<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">/projects
   /portfolio-site
   /moms-bakery
   /client-1</code>`}<!-- HTML_TAG_END --></pre></li>
<li><code>assignments</code> for repos that contain WBDV assessments to be handed in:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">/cpnt-260
    /assignment-1
    /assignment-2
    /etc
/cpnt-262
    /assignment-1
    /etc</code>`}<!-- HTML_TAG_END --></pre></li></ol>
<h3 id="${"demo-codepen-challenge"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-codepen-challenge"}"><span class="${"icon icon-link"}"></span></a>Demo: Codepen Challenge</h3>
<p><strong>Instructions</strong></p>
<ol><li>Copy and paste the code of <a href="${"https://gist.github.com/acidtone/6871979b4f4b04375edb6312dcdba5b7"}" rel="${"nofollow"}">this empty HTML file</a> into a file named <code>index.html</code>. Place this file inside it’s own repo named <code>codepen-challenge</code>.</li>
<li>Move the code inside the Codepen HTML panel to a <code>&lt;body&gt;</code> element of an empty HTML page named <code>index.html</code>;</li>
<li>Move the code inside the CSS panel to a <code>&lt;style&gt;</code> element inside <code>&lt;head&gt;</code> element of the same HTML page;</li>
<li>Move the code inside the JS panel, if it exists, to a <code>&lt;script&gt;</code> at the bottom of the <code>&lt;body&gt;</code> element of the HTML page;</li>
<li>Confirm the page is working as expected;</li>
<li>Push <code>index.html</code> to a GH repo named <code>codepen-challenge</code> and enable GH Pages;</li></ol>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li><a href="${"/courses/cpnt-201/assessments/assignment-2"}">CPNT 201 - Assignment 2</a></li>
<li><a href="${"/courses/cpnt-260/assessments/assignment-1"}">CPNT 260 - Assignment 1</a></li>
<li><a href="${"/courses/cpnt-260/assessments/achievements-1"}">CPNT 260 - Achievements Round 1</a></li></ul>`;
});

export { _02_day_2 as default, metadata };
