import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/03-day-3.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 3 - Visual Hierarchy and User Flows",
	"excerpt": null,
	"status": "draft"
};

const _03_day_3 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"announcements-and-questions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#announcements-and-questions"}"><span class="${"icon icon-link"}"></span></a>Announcements and Questions</h2>
<ul><li><a href="${"https://discord.gg/AYMbdZjK"}" rel="${"nofollow"}">Dohyeong Kim’s Class Discord Channel</a></li>
<li>Answer Questions about the 1st Assignment</li>
<li>Today we are going to finish early because we ran late yesterday</li></ul>
<h2 id="${"morning-activity-altitude"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#morning-activity-altitude"}"><span class="${"icon icon-link"}"></span></a>Morning Activity: <a href="${"https://gist.github.com/lilyx13/33c2cd47e61ac9467af036754eec4f08"}" rel="${"nofollow"}">Altitude</a></h2>
<ul><li>Time: 20 Minutes</li>
<li>Goal: Think about the ways a user could use a site or app, establish a perceived “intended” use and brainstorm other ways a user might approach the site/app</li></ul>
<h3 id="${"debrief"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ul><li>How many variations did you discover?</li>
<li>Did the presentation of content lead you down any potential rabbit holes?</li>
<li>What was the most suprising revelation about the site/app that your team reviewed?</li></ul>
<h3 id="${"break-15-min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-min"}"><span class="${"icon icon-link"}"></span></a>Break 15 Min</h3>
<h2 id="${"visual-hierarchy"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#visual-hierarchy"}"><span class="${"icon icon-link"}"></span></a>Visual Hierarchy</h2>
<ul><li>Video: <a href="${"https://www.youtube.com/watch?v=qZWDJqY27bw"}" rel="${"nofollow"}">Design Principles - Visual Hierarchy</a> The Freelancers Journey<ul><li>Put yourself in the shoes of your client’s client</li>
<li>Overly complex and cluttered designs are hard to get information from<ul><li>Avoid letting information compete for prominance</li></ul></li></ul></li>
<li>Video: <a href="${"https://www.youtube.com/watch?v=8zhhc5pzE9Y"}" rel="${"nofollow"}">Design Principles - Repetition</a> - The Freelancers Journey<ul><li>Use repeating patterns, sizes, and shapes to communicate meaning, set expectations, and create a pattern which can be <strong>strategically broken</strong></li></ul></li>
<li>Video: <a href="${"https://www.youtube.com/watch?v=9QRIjnMEXw8"}" rel="${"nofollow"}">Design Principles: Grid Spacing and Alignment</a><ul><li>Grids are commonly used in design to organize content<ul><li>If content isn’t balanced in sized, a traditional grid might not be the best way to organize content</li></ul></li></ul></li>
<li>Video: <a href="${"https://www.youtube.com/watch?v=3dESVj7-XzI"}" rel="${"nofollow"}">Design Principles - Space</a><ul><li>Empty space is used to:</li>
</ul><ol><li>create rhythm</li>
<li>establish relationships between content</li>
<li>give elements the ability to breathe</li></ol></li>
<li>Video <a href="${"https://www.youtube.com/watch?v=yom0nogFN3k"}" rel="${"nofollow"}">Design Principles - Typography</a><ul><li>Display and Text typefaces</li>
<li>Typography makes a statement and creates identity</li></ul></li></ul>
<h3 id="${"activity-design-review"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-design-review"}"><span class="${"icon icon-link"}"></span></a>Activity: Design Review</h3>
<ul><li>In the same groups as the first activity, review your website’s use of the following design pattners<ol><li>Visual Hierarchy in general (how is some information made more important than others?)</li>
<li>Reptition (How is it used?)</li>
<li>Grid and Alignment (Is there a grid? or is it more fluid?)</li>
<li>Typography (How are fonts giving character to the design? How are they affecting visual hierarchy?)</li></ol></li></ul>
<h3 id="${"debrief-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief-1"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ul><li>Each group discuss <strong>1</strong> aspect of design from your site</li></ul>
<h3 id="${"break-15-min-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-15-min-1"}"><span class="${"icon icon-link"}"></span></a>Break 15 Min</h3>
<h2 id="${"user-flows"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#user-flows"}"><span class="${"icon icon-link"}"></span></a>User Flows</h2>
<ul><li>Initial Discussion Based on Homework Readings<ul><li>What is our current understanding of users flows based on the readings?</li></ul></li>
<li>Watch <a href="${"https://www.youtube.com/watch?v=TIV1y11xz7k"}" rel="${"nofollow"}">User Flow Tutorial</a></li></ul>
<h3 id="${"types-of-user-flows"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#types-of-user-flows"}"><span class="${"icon icon-link"}"></span></a>Types of User Flows</h3>
<ul><li>Establish an idea of who your users are and and what their goals are</li></ul>
<ol><li>Task Flows (the mental steps and tasks)</li></ol>
<ul><li>Steps that a user goes through to achieve their goal</li></ul>
<ol start="${"2"}"><li>Wireflows (lo-fi rendering of how the tasks are achieved)</li></ol>
<ul><li>Sketch screens that the user will go through</li></ul>
<ol start="${"3"}"><li>Screen flows (hi-fi)</li></ol>
<ul><li>mockup version that shows what the app will actually look like</li></ul>
<h2 id="${"in-class-example"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#in-class-example"}"><span class="${"icon icon-link"}"></span></a>In Class Example</h2>
<ul><li>Ash will walk through creating a user flow</li>
<li><a href="${"https://www.figma.com/file/JSuY5AkMcZZ3UfKI7ntpQS/User-Flow-Example?node-id=0%3A1"}" rel="${"nofollow"}">Link to Figjam File</a></li></ul>
<h3 id="${"break"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break"}"><span class="${"icon icon-link"}"></span></a>Break</h3>
<h2 id="${"activity-create-a-task-flow-30min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-create-a-task-flow-30min"}"><span class="${"icon icon-link"}"></span></a>Activity: Create a Task Flow (30min)</h2>
<ul><li>In same groups at the 1st 2 activities, you will create a user flow for 1-3 aspects of your site</li></ul>
<ol><li>Create a new figjam file for your group’s user flow </li>
<li>Based on your use cases from the 1st activity, outline users and their potential goals</li>
<li>Each team member should be able to create a user flow based on an identified goal</li>
<li>Create a Task flow as demonstrated during the in class example</li>
<li>Pick a user flow to show to class</li></ol>
<h3 id="${"debrief-2"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief-2"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ul><li>Each team will walk through 1 user flow</li></ul>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Work on Assignment 1</li>
<li>1 on 1 Sessions with Ash</li></ul>
<h2 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h2>
<ul><li>Review Visual Hierarchy Videos</li>
<li>Catch up on videos from last class</li>
<li>Read: <a href="${"https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility"}" rel="${"nofollow"}">What is Accessibility</a></li>
<li>Watch: <a href="${"https://www.youtube.com/watch?v=pN92rnO_n5U"}" rel="${"nofollow"}">Wireframe Tutorial</a> 30:00</li></ul>`;
});

export { _03_day_3 as default, metadata };
