import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-264/03-day-3.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Career and Consulting Services",
	"excerpt": null,
	"status": "draft"
};

const _03_day_3 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _03_day_3 as default, metadata };
