import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/03-day-3.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _03_day_3 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Dismissal at lunch time</li>
<li>New Deadlines for Achievements:<ul><li>Round 1: Monday the 12th @ 2pm</li>
<li>Round 2: Thursday the 16th @ 2pm</li></ul></li>
<li>Optional Lab Time from 8-9am starting tomorrow</li></ul>
<hr>
<h2 id="${"1-final-week-checklist"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-final-week-checklist"}"><span class="${"icon icon-link"}"></span></a>1. Final Week Checklist</h2>
<ul><li><strong><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-265/finals-checklist.html"}" rel="${"nofollow"}">Slides</a></strong></li></ul>
<hr>
<h2 id="${"review---github-projects-beta"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#review---github-projects-beta"}"><span class="${"icon icon-link"}"></span></a>Review - GitHub Projects (Beta)</h2>
<h3 id="${"project-to-define"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#project-to-define"}"><span class="${"icon icon-link"}"></span></a>Project to define</h3>
<ul><li><a href="${"https://sait-wbdv.github.io/"}" rel="${"nofollow"}">Presentation page</a> -&gt; Nuxt</li></ul>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>May and Doh - React</li>
<li>Pair-code with Tony?</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<ul><li>Tony: <ul><li>Reverse the Fall 2022 Schedule</li>
<li>Vanilla Vite?</li></ul></li></ul>
<hr>`;
});

export { _03_day_3 as default, metadata };
