import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/03-day-3.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Random numbers and arrays",
	"excerpt": null,
	"status": "draft"
};

const _03_day_3 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Group project submission overview</li>
<li>Draft CPNT 262 Assessments announced after lunch</li></ul>
<hr>
<h2 id="${"1-spoilers"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-spoilers"}"><span class="${"icon icon-link"}"></span></a>1. Spoilers</h2>
<ul><li><a href="${"https://gist.github.com/acidtone/5c13ec3ff2ea53b7f75ae3692ca944d1"}" rel="${"nofollow"}">Sample code and instructions</a></li>
<li><a href="${"https://gist.github.com/acidtone/b9aaf4228a903796a6d8532ffb36d9d7"}" rel="${"nofollow"}">Bug hunt - syntax errors</a></li></ul>
<hr>
<h2 id="${"2-arrays"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-arrays"}"><span class="${"icon icon-link"}"></span></a>2. Arrays</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-arrays.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-arrays.png"}" alt="${"Slides - Javascript arrays"}"></a></p>
<h3 id="${"demo-random-numbers-and-arrays"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-random-numbers-and-arrays"}"><span class="${"icon icon-link"}"></span></a>Demo: Random numbers and arrays</h3>
<ul><li><a href="${"https://gist.github.com/acidtone/2a3cac26a229aa95685e5cf6344f2e4e"}" rel="${"nofollow"}">Find a random item in an Array</a></li></ul>
<hr>
<h2 id="${"3-introduction-to-functions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-introduction-to-functions"}"><span class="${"icon icon-link"}"></span></a>3. Introduction to functions</h2>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li>Gist: <a href="${"https://gist.github.com/acidtone/e3ed5adfcb4f3c02f1b78f78c9c2bf8b"}" rel="${"nofollow"}">Defining functions</a></li>
<li>Gist: <a href="${"https://gist.github.com/acidtone/679b1b07dcaad4491e8696c871e36436"}" rel="${"nofollow"}">Invoking functions</a></li></ul>
<h3 id="${"activity-refactor-into-functions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-refactor-into-functions"}"><span class="${"icon icon-link"}"></span></a>Activity: Refactor into functions</h3>
<ul><li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7"}" rel="${"nofollow"}">Sample code and instructions</a></li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Draft CPNT 262 Assessments announced</li>
<li>Group Projects due tonight!</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"system-requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#system-requirements"}"><span class="${"icon icon-link"}"></span></a>System Requirements</h3>
<ul><li>Node (which you probably already have installed):<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">$ node --version</code>`}<!-- HTML_TAG_END --></pre><ul><li>To install:<ul><li><strong>Easy</strong> - <a href="${"https://nodejs.org/en/download/"}" rel="${"nofollow"}">Binary Installer</a></li>
<li><strong>Maybe Tricky</strong> - <a href="${"https://www.google.com/search?q=nvm+getting+started"}" rel="${"nofollow"}">Try nvm</a> for that pro look.</li></ul></li></ul></li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch List</h3>
<ul><li>Arrays and Functions in <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk"}" rel="${"nofollow"}">JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour</a> by Mosh<ul><li>35:22 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2122s"}" rel="${"nofollow"}">Arrays</a></li>
<li>39:41 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2122s"}" rel="${"nofollow"}">Functions</a></li>
<li>44:22 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2662s"}" rel="${"nofollow"}">Types of Functions</a></li></ul></li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays"}" rel="${"nofollow"}">Arrays</a></li>
<li><a href="${"https://javascript.info/function-expressions"}" rel="${"nofollow"}">Function expressions</a></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“js functions for beginners”</li>
<li>“js random number”</li>
<li>“math builtin object”</li></ul>
<h3 id="${"recommended-exercises"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#recommended-exercises"}"><span class="${"icon icon-link"}"></span></a>Recommended exercises</h3>
<ul><li><a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#basic-javascript"}" rel="${"nofollow"}">Javascript basics</a>: Exercises 9-22<ul><li>Start: <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/add-two-numbers-with-javascript"}" rel="${"nofollow"}">Add Two Numbers with JavaScript</a></li>
<li>Stop (or not): <a href="${"https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/compound-assignment-with-augmented-division"}" rel="${"nofollow"}">Compound Assignment With Augmented Division</a></li></ul></li></ul>`;
});

export { _03_day_3 as default, metadata };
