import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Strings and the DOM",
	"excerpt": null,
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-262/assessments/assignment-1"}">CPNT 262 Assignment 1</a> announced</li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-1"}">More Achievements for Round 1</a> announced after lunch</li>
<li>CPNT 260 Final Project marks released</li></ul>
<hr>
<h2 id="${"1-strings-and-string-methods"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-strings-and-string-methods"}"><span class="${"icon icon-link"}"></span></a>1. Strings and string methods</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-strings.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-strings.png"}" alt="${"Slides - Javascript strings"}"></a></p>
<h3 id="${"activity-string-method-practice"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-string-method-practice"}"><span class="${"icon icon-link"}"></span></a>Activity: String method practice</h3>
<p>In pairs, practice using string methods:</p>
<ol><li>Go to wikipedia and choose a sentence or phrase that interests you (or doesn’t);</li>
<li>In a new <code>client.js</code> file, create a <code>string</code> variable containing your selected phrase;</li>
<li>Try using the following string methods on your phrase:<ul><li>Using <code>String.length</code>, log the sentence “This phrase has [Number] characters”, replacing <code>[Nunber]</code> with the actual number of characters in the <code>string</code>.</li>
<li>Using <code>String.startsWith()</code>, log a <code>true</code> or <code>false</code> based on whether or not the the word “The” (or similar) matches the start of the <code>string</code>.</li>
<li>Using <code>String.endsWith()</code>, log whether or not the <code>string</code> is a question.</li>
<li>Using <code>String.includes()</code>, log a <code>true</code> or <code>false</code> based on whether or not the <code>string</code> contains the word “the” (or similar).</li>
<li>Using <code>String.indexOf()</code>, log the <code>index</code> of the first matching word (i.e. “the”) found in the <code>string</code>.</li>
<li>Add the <code>&lt;textarea&gt;</code> counter back into the starter form.</li>
<li>Using <code>String.split()</code>, log each character in the <code>string</code> as an array.</li></ul></li></ol>
<hr>
<h2 id="${"2-the-document-object-model"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-the-document-object-model"}"><span class="${"icon icon-link"}"></span></a>2. The Document Object Model</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-dom.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-dom.png"}" alt="${"Slides - Document Object Model"}"></a></p>
<h3 id="${"activity-dom-practice"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-dom-practice"}"><span class="${"icon icon-link"}"></span></a>Activity: DOM practice</h3>
<p>In pairs:</p>
<ol><li>Using <code>document.querySelector()</code> and <code>Element.innerHTML</code>, try printing the console logs you created in the previous activity to a <code>&lt;p&gt;</code> element on an HTML page;</li>
<li>Using <code>prompt()</code> print dynamic content to an HTML page using user input.</li></ol>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Complete this morning’s activities (or work on the below achievements for marks instead);</li>
<li>CPNT 262:<ul><li><a href="${"/courses/cpnt-262/assessments/assignment-1"}">Assignment 1</a></li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-1"}">Achievements Round 1</a></li></ul></li>
<li><a href="${"/courses/dsgn-270/assessments/assignment-4"}">DSGN 270 Assignment 4</a></li></ul>
<hr>`;
});

export { _04_day_4 as default, metadata };
