import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-200/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Installing Strapi, Building Types, Relations",
	"excerpt": null,
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-200/assessments/assignment-1"}">Assignment 1 due tonight</a><ul><li>Changes: <a href="${"https://github.com/sait-wbdv/fall-2022/commit/df15ec2cc58682279067581610acbb40569ee118#diff-044bb52f0e2fc379c744fd5f1b9302e8b25f0d3a43a2afcbf4b36f5997c27534"}" rel="${"nofollow"}">added requirements for SiteMap</a></li></ul></li>
<li>Assignment 2 due Friday - announced tomorrow</li></ul>
<hr>
<h2 id="${"1-demo-site-map"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-demo-site-map"}"><span class="${"icon icon-link"}"></span></a>1. Demo: Site Map</h2>
<p>A quick build of a site map in Figma.</p>
<p>Creating labels/colours for:</p>
<ul><li>Single pages (i.e. About, Contact, etc)</li>
<li>List entry pages (i.e. Gallery index page)</li>
<li>Item Collection (i.e. one “page” that represents multiple items in a collection)</li></ul>
<hr>
<h2 id="${"2-demo-strapi-installation-and-content-type-builder"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-demo-strapi-installation-and-content-type-builder"}"><span class="${"icon icon-link"}"></span></a>2. Demo: Strapi Installation and Content-type Builder</h2>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://docs.strapi.io/user-docs/latest/getting-started/introduction.html"}" rel="${"nofollow"}">User Guide</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html"}" rel="${"nofollow"}">Developer Documentation</a></li>
<li>Slides: <a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-200/strapi-content-types.html"}" rel="${"nofollow"}">Strapi Content Types</a></li></ul>
<h3 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h3>
<p>See: <a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html"}" rel="${"nofollow"}">Strapi Quick Start Guide</a></p>
<ol><li><p>Create a new project</p>
<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">$ npx create-strapi-app@latest my-project --quickstart</code>`}<!-- HTML_TAG_END --></pre>
<ul><li>Potential installation problems<ul><li><strong>Port conflict</strong>: for example, Razor keyboards also use port 1337<ul><li>Solution<ol><li>Change Strapi port to 1338 (for exmaple) in <code>.env</code> file;</li>
<li>Rebuild your project<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">$ npm run build</code>`}<!-- HTML_TAG_END --></pre></li>
<li>Run development server<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">$ npm run develop</code>`}<!-- HTML_TAG_END --></pre></li></ol></li></ul></li>
<li>Windows users:<ul><li>Node not installed<ul><li><a href="${"https://nodejs.org/en/download/"}" rel="${"nofollow"}">Binary installer for Node</a></li>
<li>Can also use <a href="${"https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools"}" rel="${"nofollow"}">Visual Studio Build Tools</a><ul><li>Select “Desktop Development with C++”</li></ul></li></ul></li>
<li>Python not installed<ul><li>Install with <a href="${"https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools"}" rel="${"nofollow"}">Visual Studio Build Tools</a>?</li></ul></li></ul></li></ul></li></ul></li></ol>
<ol start="${"2"}"><li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#step-2-register-the-first-administrator-user"}" rel="${"nofollow"}">Register the first administrator user</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#step-1-create-collection-types-with-the-content-type-builder"}" rel="${"nofollow"}">Create collection types with the Content-type Builder</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#step-2-use-the-collection-types-to-create-new-entries"}" rel="${"nofollow"}">Create new entries</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#step-3-set-roles-permissions"}" rel="${"nofollow"}">Set Roles &amp; Permissions</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#step-4-publish-the-content"}" rel="${"nofollow"}">Publish the content</a></li>
<li><a href="${"https://docs.strapi.io/user-docs/latest/settings/managing-global-settings.html#managing-api-tokens"}" rel="${"nofollow"}">Create API token</a><ul><li>Note: you only see the token once. Copy and Paste token somewhere safe, like a <code>.env</code> file in the root of your project:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">API_TOKEN=asdlfandsfj8373nehd93hdk...</code>`}<!-- HTML_TAG_END --></pre></li>
<li>Using your token for requests:<ol><li>Open Postman;</li>
<li>Enter your endpoint URL:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">http://localhost:1337/api/articles</code>`}<!-- HTML_TAG_END --></pre><ul><li>You should get an “UnauthorizedError” because you didn’t supply a token;</li></ul></li>
<li>Go to Authorization in Postman to add your token:<ul><li>Type: Bearer Token;</li>
<li>Token: Paste the token you copied from Strapi;</li></ul></li>
<li>Re-submit request and you should now receive the list of items.</li></ol></li></ul></li></ol>
<hr>
<h2 id="${"3-demo-enumeration-vs-relation-fields"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-demo-enumeration-vs-relation-fields"}"><span class="${"icon icon-link"}"></span></a>3. Demo: Enumeration vs Relation fields</h2>
<h3 id="${"materials-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials-1"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li>Slides: <a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-200/strapi-content-types.html"}" rel="${"nofollow"}">Strapi Content Types</a></li>
<li><a href="${"https://docs.strapi.io/user-docs/latest/content-types-builder/configuring-fields-content-type.html#enumeration"}" rel="${"nofollow"}">Enumeration fields</a></li>
<li>Relation fields<ul><li><a href="${"https://strapi.io/blog/understanding-and-using-relations-in-strapi"}" rel="${"nofollow"}">Understanding and using Relations in Strapi</a></li>
<li><a href="${"https://docs.strapi.io/user-docs/latest/content-manager/managing-relational-fields.html"}" rel="${"nofollow"}">Managing relational fields</a></li></ul></li></ul>
<h3 id="${"notes-and-gotchas"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#notes-and-gotchas"}"><span class="${"icon icon-link"}"></span></a>Notes and gotchas</h3>
<ul><li>If you edit a Relation after Entries have been added, you will need to re-set the Relation values in each Entry. Moral: add the minimum amount of content until you’ve finalized your Model to save you some time.</li>
<li>The Strapi API won’t retrieve Relation data by default. You have to explicitly request the Relations with a <code>populate</code> query parameter:<pre class="${"language-undefined"}"><!-- HTML_TAG_START -->${`<code class="language-undefined">http://localhost:1338/api/resources?populate=*</code>`}<!-- HTML_TAG_END --></pre></li></ul>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<p>Above and Beyond</p>
<ul><li><a href="${"https://stackoverflow.com/questions/71625257/categories-and-sub-categories-for-strapi-collection"}" rel="${"nofollow"}">Categories and Subcategories with self-relation field</a></li>
<li><a href="${"https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html#hosting-provider-guides"}" rel="${"nofollow"}">Testing Deploy Guides</a>: Find a host that has:<ul><li>Free tier</li>
<li>No CC Required</li></ul></li></ul>
<p><strong>Assignments</strong></p>
<ul><li><a href="${"/courses/cpnt-200/assessments/achievements"}">CPNT 200 Content Achievements</a></li>
<li><a href="${"/courses/cpnt-200/assessments/assignment-1"}">CPNT 200 Assignment 1</a></li></ul>`;
});

export { _04_day_4 as default, metadata };
