import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 4 Accessibility, Responsive Design",
	"excerpt": null,
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"assignment-2-visual-report-on-responsive-design-to-be-discussed-at-the-end-of-the-lecture"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignment-2-visual-report-on-responsive-design-to-be-discussed-at-the-end-of-the-lecture"}"><span class="${"icon icon-link"}"></span></a>Assignment 2: Visual Report on Responsive Design (TO BE DISCUSSED AT THE END OF THE LECTURE)</h2>
<ul><li>Due: <strong>Wednesday September 14 @ 11:59PM</strong></li>
<li>Objective: Document Examples of Responsive Design</li>
<li>Outcomes:<ul><li>Inspect how apps and sites change layouts depending on the size of the window</li>
<li>Take notes on specific changes from Desktop to Mobile design</li>
<li>Reinforce knowledge of UI elements by reviewing how they change to be optimized at different screen sizes</li>
<li>Practice Creating visual hierarchy in the layout of your report</li></ul></li></ul>
<h2 id="${"moodboard-examples"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#moodboard-examples"}"><span class="${"icon icon-link"}"></span></a>Moodboard Examples</h2>
<ul><li><p><a href="${"https://www.justinmind.com/blog/mood-board-examples-design-website-app/"}" rel="${"nofollow"}">Inspiring Moodboards</a></p></li>
<li><p>Moodboards are meant to be creative</p>
<ul><li>Experiment with layout, moodboard’s are for planning and organizing ideas, but they can also be playful</li></ul></li>
<li><p>The following visual design principles should be used to make your board visually appealing and easy to navigate:</p></li>
<li><p>visual hierarchy </p></li>
<li><p>whitespace</p></li>
<li><p>repetition</p></li>
<li><p>typography</p></li>
<li><p>grid spacing and alignment</p>
<h2 id="${"morning-activity-empathy-map"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#morning-activity-empathy-map"}"><span class="${"icon icon-link"}"></span></a><a href="${"https://gist.github.com/lilyx13/40e2eb82c580877d48adfe9ff934197c"}" rel="${"nofollow"}">Morning Activity: Empathy Map</a></h2></li>
<li><p>In groups of 4, create an empathy map and fill it out based on the provided template</p></li>
<li><p>Time: 25 minutes</p></li>
<li><p>Goal: Try to get inside the head of a user. Pick a website to focus on</p></li></ul>
<h3 id="${"debrief"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ol><li>Provide a short outline of your user</li>
<li>What were key takeaways that you learned about how they might experience a site/app</li></ol>
<h3 id="${"break"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break"}"><span class="${"icon icon-link"}"></span></a>Break</h3>
<h2 id="${"accessibility"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#accessibility"}"><span class="${"icon icon-link"}"></span></a>Accessibility</h2>
<p>People with different ranges of physical and cognitive ability use the internet everyday. While it’s easy to assume that everyone engages with the web the way that you do, this is far from the truth. As a developer, you are responsible for creating a positive web experience for people with many different ranges of ability.</p>
<h3 id="${"how-accessibility-benefits-everyone"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#how-accessibility-benefits-everyone"}"><span class="${"icon icon-link"}"></span></a>How accessibility Benefits Everyone</h3>
<ul><li>Semantic HTML, which improves accessibility, also improves SEO, making your site more findable.</li>
<li>Caring about accessibility demonstrates good ethics and morals, which improves your public image.</li>
<li>Other good practices that improve accessibility also make your site more usable by other groups, such as mobile phone users or those on low network speed. In fact, everyone can benefit from many such improvements.</li>
<li>Did we mention it is also the law in some places?</li></ul>
<p><em>From <a href="${"https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility"}" rel="${"nofollow"}">MDN Article</a></em></p>
<h3 id="${"types-of-accessibility-issues"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#types-of-accessibility-issues"}"><span class="${"icon icon-link"}"></span></a>Types of Accessibility issues</h3>
<ul><li>Vision Impairment<ul><li><a href="${"https://youtu.be/IK97XMibEws"}" rel="${"nofollow"}">Listen to how visually impared people experience the web with screen readers</a></li>
<li>Use good contrast relatios</li></ul></li>
<li>Hearing Impairment<ul><li>Audio should be captioned</li></ul></li>
<li>Mobility Impairment<ul><li>Have good keyboard controls (like being able to tab through content effectively)</li></ul></li>
<li>Cognitive Impairment<ul><li>Use plain language standards</li>
<li>Minimize distractions</li>
<li>Consistent and easy to use design</li></ul></li></ul>
<h3 id="${"break-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#break-1"}"><span class="${"icon icon-link"}"></span></a>Break</h3>
<h2 id="${"responsive-design"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#responsive-design"}"><span class="${"icon icon-link"}"></span></a>Responsive Design</h2>
<p>There are many things to consider when designing for both mobile and desktop screens but here are the key constraints we will be focusing on in this program:</p>
<ul><li>Layout<ul><li>Navigation and content would never “overflow” the screen, creating a horizontal scroll bar. At narrow screen widths, navigation is often <a href="${"https://codepen.io/acidtone/pen/xxqmWXb"}" rel="${"nofollow"}">replaced with a Hamburger toggle</a>.</li>
<li>Content will often be displayed using the <a href="${"https://rubygarage.org/blog/card-based-design-best-practices"}" rel="${"nofollow"}">card pattern</a>. On mobile, these cards will display in a single column. See: <a href="${"https://codepen.io/acidtone/pen/ZEpgMGL"}" rel="${"nofollow"}">“Gridish” flexbox in this Codepen</a>.</li>
<li>In general, content should not touch the edge of the screen on mobile. There should be a visible “scroll track” letting the user know where to scroll with their finger.</li>
<li>When/if content reaches its maximum page width on desktop screens, the content should be centered. This website is an example.</li></ul></li>
<li>Web Typography<ul><li>Body text line length should not be longer than 95 characters or shorter than 25ch.</li>
<li>Font size should be smaller on mobile than on desktop. This is called fluid typography.</li>
<li>See: <a href="${"https://codepen.io/browsertherapy/pen/RwaJmbx"}" rel="${"nofollow"}">Responsive Text: Max Line Length with Fluid Typography</a></li></ul></li></ul>
<h3 id="${"activity-content-parity-and-emulators"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-content-parity-and-emulators"}"><span class="${"icon icon-link"}"></span></a>Activity: Content Parity and Emulators</h3>
<p>In groups of 3 or 4:</p>
<p>Compare and contrast the visual appearance of your favourite (or non-favourite) mobile websites between:</p>
<ol><li>Desktop,</li>
<li>A real mobile device, and</li>
<li>The virtual mobile simulator in FireFox Dev Tools.</li></ol>
<p><strong>Questions to ask</strong>:</p>
<ul><li>Is there content parity between mobile and desktop versions of the website? What’s missing? What’s changed?</li>
<li>What differences can you find between iOS and Android?</li>
<li>How accurate is the phone simulator in FireFox and Chrome? </li></ul>
<p>Select a representative from each group to present a summary of your findings to the rest of the class.</p>
<hr>
<h2 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h2>
<h3 id="${"design-homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#design-homework"}"><span class="${"icon icon-link"}"></span></a>Design Homework</h3>
<p><em>When we come back to DSGN-270, we will be creating UI wireframes and mockups in <strong>figma</strong>. Take some time to familiarize with these materials</em></p>
<ul><li>Read: <a href="${"https://careerfoundry.com/en/blog/ux-design/user-flows-vs-wireframes/"}" rel="${"nofollow"}">User Flow vs Wireframe</a></li>
<li>Read: <a href="${"https://www.nngroup.com/articles/draw-wireframe-even-if-you-cant-draw/"}" rel="${"nofollow"}">How to draw a wireframe even if you can’t draw</a></li>
<li>Watch: <a href="${"https://www.youtube.com/watch?v=X2CbeBojKVM"}" rel="${"nofollow"}">How to sketch a UI for non-designers</a></li>
<li>Watch <a href="${"https://www.youtube.com/watch?v=jreccgYLfx8"}" rel="${"nofollow"}">Modern Layouts: Getting out of our Ruts - Jen Simmons</a> — 1 hour</li></ul>
<h3 id="${"cpnt-201-prep-homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#cpnt-201-prep-homework"}"><span class="${"icon icon-link"}"></span></a>Cpnt-201 Prep Homework</h3>
<ul><li>Read <a href="${"https://www.atlassian.com/agile/kanban/boards"}" rel="${"nofollow"}">What is a kanban board</a></li>
<li>Watch <a href="${"https://www.youtube.com/watch?v=7tPZM5gwxtE"}" rel="${"nofollow"}">Intro to the Command Line</a></li>
<li>Read <a href="${"https://www.git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F"}" rel="${"nofollow"}">What is Git?</a></li>
<li>Windows users: <a href="${"https://www.atlassian.com/git/tutorials/git-bash"}" rel="${"nofollow"}">Install git bash</a></li>
<li>Everyone: <a href="${"https://code.visualstudio.com/"}" rel="${"nofollow"}">Install VS Code</a></li></ul>`;
});

export { _04_day_4 as default, metadata };
