import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-265/assessments/achievements-2"}">Achievements Round 2</a> Announced</li></ul>
<hr>
<h2 id="${"cool-videos-tony-found"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#cool-videos-tony-found"}"><span class="${"icon icon-link"}"></span></a>Cool Videos Tony Found</h2>
<ul><li><a href="${"https://www.youtube.com/watch?v=LQQ3CR2JTX8"}" rel="${"nofollow"}">Vite 2.0 Crash Course</a><ul><li>Vite is the bundler/web server that runs under Nuxt and VueJS but it can also run React, Svelte and vanilla JS websites. Try adding Vite to your vanilla project for extra nerd points.</li></ul></li></ul>
<hr>
<h2 id="${"proof-of-work-example"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#proof-of-work-example"}"><span class="${"icon icon-link"}"></span></a>Proof of Work Example</h2>
<p>Tony will start a new Nuxt project for the final presentation agenda app and begin working on the cards he created yesterday.</p>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>TBA</li>
<li>TBA</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<ul><li>Open Lab time</li></ul>
<hr>`;
});

export { _04_day_4 as default, metadata };
