import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-264/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Career and Consulting Services",
	"excerpt": null,
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _04_day_4 as default, metadata };
