import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/04-day-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Easy images",
	"excerpt": "In this session, we'll show you how to add images to web pages using Lorem Picsum.",
	"status": "draft"
};

const _04_day_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Update on the Program Schedule<ul><li>Tony now teaching CPNT 200</li>
<li>Ash now teaching CPNT 262 Days 11-22</li></ul></li>
<li><a href="${"/courses/cpnt-260/day-5"}">Show and Tell tomorrow</a></li>
<li>Ash covering afternoon</li>
<li>Afternoon attendance</li>
<li><a href="${"/courses/cpnt-260/assessments/assignment-2"}">CPNT 260 Assignment 2</a></li></ul>
<hr>
<h2 id="${"1-issue-demo"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-issue-demo"}"><span class="${"icon icon-link"}"></span></a>1. Issue Demo</h2>
<ul><li>Font stacks don’t support Linux</li>
<li>23rd and 26th are showing the wrong course</li></ul>
<hr>
<h2 id="${"2-image-formats"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-image-formats"}"><span class="${"icon icon-link"}"></span></a>2. Image formats</h2>
<h3 id="${"slides"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#slides"}"><span class="${"icon icon-link"}"></span></a>Slides</h3>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/html-images.html"}" rel="${"nofollow"}"><img src="${"/images/slides/raster-html-images.png"}" alt="${"Raster Image Slides"}"></a></p>
<h3 id="${"activity-asset-inventory"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-asset-inventory"}"><span class="${"icon icon-link"}"></span></a>Activity: Asset inventory</h3>
<ol><li>Create a Github Project (Beta) labelled “Asset inventory”</li>
<li>Find image assets (file system, online, wherever) that you’d like to use for a project.<ul><li>if you don’t have any images handy, add a Card to your Project labelled “Find some cool images”</li></ul></li>
<li>Categorize your images:<ul><li>Is it a high or low frequency image (on average)?</li>
<li>Would it be better suited to be a JPEG or PNG image?</li>
<li>If your image is in the wrong format, add a Card to your Project labelled “Convert [image-label] to [preferred-format]”</li></ul></li></ol>
<h3 id="${"show-and-tell"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#show-and-tell"}"><span class="${"icon icon-link"}"></span></a>Show and Tell</h3>
<ul><li>Show off your favourite images and talk about them for 2.5-7.5 minutes.<ul><li><strong>10 points</strong>, just sayin’…</li></ul></li></ul>
<hr>
<h2 id="${"3-html-images"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-html-images"}"><span class="${"icon icon-link"}"></span></a>3. HTML Images</h2>
<ul><li><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/html-images.html/#9"}" rel="${"nofollow"}">Slides</a></li></ul>
<h3 id="${"demo-adding-and-html-image-to-a-page"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-adding-and-html-image-to-a-page"}"><span class="${"icon icon-link"}"></span></a>Demo: Adding and HTML image to a page</h3>
<ul><li>Image Generator: <a href="${"https://picsum.photos/"}" rel="${"nofollow"}">Lorem Picsum</a></li></ul>
<h3 id="${"pair-code-with-tony"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#pair-code-with-tony"}"><span class="${"icon icon-link"}"></span></a>Pair-code with Tony</h3>
<p>Tony, with the help of a volunteer, will demo one of the following CSS properties:</p>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit"}" rel="${"nofollow"}"><code>object-fit</code></a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode"}" rel="${"nofollow"}"><code>mix-blend-mode</code></a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path"}" rel="${"nofollow"}"><code>clip-path</code></a></li></ul>
<hr>
<h2 id="${"lab-time-with-ash"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time-with-ash"}"><span class="${"icon icon-link"}"></span></a>Lab Time with Ash!!!</h2>
<ul><li>Ask her about the Squoosh CLI she wants to build!</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li>By Kevin Powell<ul><li><a href="${"https://www.youtube.com/watch?v=0xoztJCHpbQ"}" rel="${"nofollow"}">HTML &amp; CSS for Beginners Part 6: Images</a></li>
<li><a href="${"https://www.youtube.com/watch?v=33IinMVJf-M"}" rel="${"nofollow"}">HTML &amp; CSS for Beginners Part 13: Background Images</a></li></ul></li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML"}" rel="${"nofollow"}">Images in HTML</a></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“html vs css images”</li>
<li>“lorem picsum”</li>
<li>“responsive images”</li></ul>`;
});

export { _04_day_4 as default, metadata };
