import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-200/05-day-5.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Sub categories and Components",
	"excerpt": null,
	"status": "draft"
};

const _05_day_5 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-200/assessments/assignment-2"}">Assignment 2 Draft</a></li></ul>
<hr>
<h2 id="${"1-sub-categories-with-self-relation-fields"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-sub-categories-with-self-relation-fields"}"><span class="${"icon icon-link"}"></span></a>1. Sub-categories with self-relation fields</h2>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://stackoverflow.com/questions/71625257/categories-and-sub-categories-for-strapi-collection"}" rel="${"nofollow"}">Categories and Subcategories with self-relation field</a></li></ul>
<hr>
<h2 id="${"2-re-usable-components"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-re-usable-components"}"><span class="${"icon icon-link"}"></span></a>2. Re-usable components</h2>
<ul><li><a href="${"https://docs.strapi.io/user-docs/latest/content-types-builder/configuring-fields-content-type.html#components"}" rel="${"nofollow"}">Components in the Strapi documentation</a></li></ul>
<hr>
<h2 id="${"3-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-lab-time"}"><span class="${"icon icon-link"}"></span></a>3. Lab Time</h2>
<ul><li><a href="${"/courses/cpnt-200/assessments/achievements"}">CPNT 200 Content Achievements</a></li>
<li><a href="${"/courses/cpnt-200/assessments/assignment-2"}">CPNT 200 Assignment 2</a></li></ul>
<hr>`;
});

export { _05_day_5 as default, metadata };
