import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/05-day-5.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _05_day_5 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Early dismissal at lunch.</li></ul>
<hr>
<h2 id="${"cool-videos-tony-found"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#cool-videos-tony-found"}"><span class="${"icon icon-link"}"></span></a>Cool Videos Tony Found</h2>
<ul><li><a href="${"https://www.youtube.com/watch?v=BwuLxPH8IDs"}" rel="${"nofollow"}">TypeScript Course for Beginners</a><ul><li>Typescript is a superset of Javascript. Watch the beginning of this video to find out what that means.</li>
<li>Typescript is very popular in industry and would be a great skill to learn and show-off in your final project.</li></ul></li></ul>
<hr>
<h2 id="${"nuxt-build-session-contd"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#nuxt-build-session-contd"}"><span class="${"icon icon-link"}"></span></a>Nuxt build session cont’d</h2>
<p>Tony will finish his Nuxt project for the final presentation agenda app (hopefully).</p>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>TBA</li>
<li>TBA</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<ul><li>Early dismissal at lunch</li></ul>
<hr>`;
});

export { _05_day_5 as default, metadata };
