import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/05-day-5.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Buttons and Event listeners",
	"excerpt": null,
	"status": "draft"
};

const _05_day_5 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"1-new-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-new-achievements"}"><span class="${"icon icon-link"}"></span></a>1. New Achievements</h2>
<p>Cordelle has shared this <a href="${"https://www.youtube.com/playlist?list=PLnHJACx3NwAdQElswAscNtHAZLAQYgpDA"}" rel="${"nofollow"}">Playlist of Javascript exercises</a></p>
<ul><li>Can these be used as an Achievement?</li></ul>
<hr>
<h2 id="${"2-functions-and-events"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-functions-and-events"}"><span class="${"icon icon-link"}"></span></a>2. Functions and events</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-callbacks-events.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-functions-events.png"}" alt="${"Slides - Javascript events and callbacks"}"></a></p>
<h3 id="${"demo-refactor-of-yesterdays-demo"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-refactor-of-yesterdays-demo"}"><span class="${"icon icon-link"}"></span></a>Demo: Refactor of yesterday’s demo</h3>
<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-10-18-events-callbacks/01-starter-dom-prompt"}" rel="${"nofollow"}">Starter code: DOM prompt()</a></li></ul>
<h3 id="${"activity"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity"}"><span class="${"icon icon-link"}"></span></a>Activity</h3>
<p>In groups of 2-3, refactor a code example to use an click Listener and callback function so that the code runs only when a button is clicked:</p>
<ol><li>Create an <code>index.html</code> page with embedded or external Javascript;</li>
<li>Add one of the following code examples to your page so that it runs when the page first loads:<ul><li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7"}" rel="${"nofollow"}">Full Activity</a><ul><li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7#file-capitalize-js"}" rel="${"nofollow"}">capitalize.js</a></li>
<li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7#file-gst-calculator-js"}" rel="${"nofollow"}">gst-calculator.js</a></li>
<li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7#file-num-squared-js"}" rel="${"nofollow"}">num-squared.js</a></li>
<li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7#file-tip-calculator-js"}" rel="${"nofollow"}">tip-calculator.js</a></li>
<li><a href="${"https://gist.github.com/acidtone/90355d3bdbcf770be4a642939f58cfd7#file-to-celcius-js"}" rel="${"nofollow"}">to-celcius.js</a></li></ul></li></ul></li>
<li>Move the code into a new function named <code>handleClick</code> so that it no longer runs on page load;</li>
<li>Add an HTML <code>&lt;button&gt;</code> to your HTML page;</li>
<li>Create a <code>button</code> DOM variable using <code>document.querySelector()</code>;</li>
<li>Add a <code>click</code> Event Listener to your button so that it runs <code>handleClick()</code> when the button is clicked;</li>
<li>Bonus: Add a <code>prompt()</code> to your function code to accept user input and present a customized response for your click Event.</li></ol>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Early Dismissal!</li>
<li>Tony will be available for the rest of the afternoon but no attendance will be taken.</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"review"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#review"}"><span class="${"icon icon-link"}"></span></a>Review</h3>
<ul><li>Watch: Functions in <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk"}" rel="${"nofollow"}">JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour</a> by Mosh<ul><li>39:41 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2122s"}" rel="${"nofollow"}">Functions</a></li>
<li>44:22 <a href="${"https://www.youtube.com/watch?v=W6NZfCO5SIk&t=2662s"}" rel="${"nofollow"}">Types of Functions</a></li></ul></li>
<li>Read: <a href="${"https://javascript.info/function-expressions"}" rel="${"nofollow"}">Function expressions</a> on Javascript.info</li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener"}" rel="${"nofollow"}"><code>EventTarget.addEventListener()</code></a><ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/Events"}" rel="${"nofollow"}">Event Reference</a></li></ul></li></ul>
<h2 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h2>
<ul><li><a href="${"https://youtu.be/EaRrmOtPYTM"}" rel="${"nofollow"}">Introduction to JavaScript Event Listeners</a> by Steve Griffith</li></ul>`;
});

export { _05_day_5 as default, metadata };
