import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/05-day-5.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Clickable links",
	"excerpt": "In this session, we'll take default link styles to make obviously clickable buttons.",
	"status": "draft"
};

const _05_day_5 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Catching up on dailies</li></ul>
<hr>
<h2 id="${"1-watch-party"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-watch-party"}"><span class="${"icon icon-link"}"></span></a>1. Watch Party!</h2>
<ul><li><a href="${"https://www.youtube.com/watch?v=UWwNIMHFdW4"}" rel="${"nofollow"}">60-30-10 Color Rule</a> by Jesse Showalter</li></ul>
<hr>
<h2 id="${"2-colour-models-and-you"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-colour-models-and-you"}"><span class="${"icon icon-link"}"></span></a>2. Colour models and you</h2>
<h3 id="${"slides-making-sense-of-web-colour"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#slides-making-sense-of-web-colour"}"><span class="${"icon icon-link"}"></span></a>Slides: Making sense of web colour</h3>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/colour.html"}" rel="${"nofollow"}"><img src="${"/images/slides/web-colours.png"}" alt="${"Web colour slides"}"></a></p>
<hr>
<h2 id="${"3-clickable-links"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-clickable-links"}"><span class="${"icon icon-link"}"></span></a>3. Clickable Links</h2>
<p>See: <a href="${"https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks"}" rel="${"nofollow"}">Creating hyperlinks</a></p>
<h3 id="${"demo-styling-a-links-as-buttons"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-styling-a-links-as-buttons"}"><span class="${"icon icon-link"}"></span></a>Demo: Styling a links as buttons</h3>
<ol><li>Define a colour palette (see below for examples);</li>
<li>Create a simple Call-to-Action card with a paragraph and link;</li>
<li>Remove the underline with <code>text-decoration</code>;</li>
<li>Using the 60-30-10 Rule, set the following with your colour palette:<ul><li>the page background (60%);</li>
<li>the card background (30%);</li>
<li>the link background (10%);</li></ul></li>
<li>Make the link more “buttony” with <code>padding</code>;<ul><li>optional: add a <code>border</code> and/or round the corners with <code>border-radius</code>;</li></ul></li>
<li>Double-check your colour contrast;</li>
<li>Define a complimentary colour for the link <code>:hover</code> state;</li>
<li>Choose a contrasting colour for the link <code>:active</code> state.</li></ol>
<hr>
<h2 id="${"4-show-and-tell--11am"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-show-and-tell--11am"}"><span class="${"icon icon-link"}"></span></a>4. Show and Tell @ 11am</h2>
<ul><li>Eli - project demo</li>
<li>Cordelle - one of two vague options</li>
<li>Sebastian - website demo</li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<h3 id="${"activity-whiteblack-colour-palette"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-whiteblack-colour-palette"}"><span class="${"icon icon-link"}"></span></a>Activity: White/black colour palette</h3>
<p>Create a colour palette for a project:</p>
<ol><li>Start with white and black;</li>
<li>Pick a Call-to-Action colour (10%) from one of your moodboards or from an online resource;</li>
<li>Choose of white or black as your neutral (60%) and primary 30% colours;</li>
<li>Using HSL and colour harmonies, make small tweaks to white and black to create light and dark complimentary colours to match your Call-to-Action colour.</li>
<li>Create a clickable link using your colour palette:<ul><li>Neutral -&gt; background colour</li>
<li>Call-to-action -&gt; link background colour</li>
<li>Primary -&gt; link text</li>
<li>Reverse link and link text colours on <code>:hover</code></li></ul></li>
<li>Add a paragraph with a box (i.e. card) to your link and build from there.</li></ol>
<h3 id="${"activity-screencap-colour-palette"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-screencap-colour-palette"}"><span class="${"icon icon-link"}"></span></a>Activity: Screencap colour palette</h3>
<p>Create a colour palette for a project based on a screencap you like:</p>
<ol><li>Find a tool that creates a colour palette from an image;</li>
<li>Convert a screencap of your favourite movie scene/music video/photograph/etc;</li>
<li>Use the 60-30-10 Rule to choose three colours for your project palette;</li>
<li>Create a clickable link using your colour palette:<ul><li>Neutral -&gt; background colour</li>
<li>Call-to-action -&gt; link background colour</li>
<li>Primary -&gt; link text</li>
<li>Reverse link and link text colours on <code>:hover</code></li></ul></li>
<li>Add a paragraph with a box (i.e. card) to your link and build from there.</li></ol>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li><a href="${"https://www.youtube.com/watch?v=eqZqx6lRPe0"}" rel="${"nofollow"}">Read color hex codes</a> by David DeSandro</li></ul>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading List</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks"}" rel="${"nofollow"}">Creating hyperlinks</a></li>
<li><a href="${"https://www.sarasoueidan.com/blog/hex-rgb-to-hsl/"}" rel="${"nofollow"}">On Switching from HEX &amp; RGB to HSL</a> by Sara Soueidan</li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“60-30-10 rule”</li></ul>`;
});

export { _05_day_5 as default, metadata };
