import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/06-day-6.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Horizontal Navigation with Flexbox",
	"excerpt": "In this session, we'll look at how we can apply Flexbox to a list of link to create a horizontal nav.",
	"status": "draft"
};

const _06_day_6 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Assignment 3: <a href="${"/courses/cpnt-260/assessments/assignment-3"}">404 Page Not Found</a></li>
<li>Achievements Round 2 will be announced tomorrow;</li>
<li>Marks released after lunch:<ul><li>CPNT-201 A2</li>
<li>Achievements Round 1</li></ul></li>
<li>Marks (and spoilers) released Thursday due to deadline extensions:<ul><li>CPNT-260 A1</li>
<li>CPNT-260 A2</li></ul></li></ul>
<hr>
<h2 id="${"1-review-svgs"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-review-svgs"}"><span class="${"icon icon-link"}"></span></a>1. Review: SVGs</h2>
<h3 id="${"code-demo"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#code-demo"}"><span class="${"icon icon-link"}"></span></a>Code Demo</h3>
<p>Let’s build some custom dice!</p>
<h3 id="${"example-king-of-tokyo"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#example-king-of-tokyo"}"><span class="${"icon icon-link"}"></span></a>Example: King of Tokyo</h3>
<p>Tony uses SVGs and Flexbox to display the dice roller in this (work-in-progress) board game:</p>
<ul><li>Live demo: <a href="${"https://browsertherapy.github.io/king-of-tokyo-clone/"}" rel="${"nofollow"}">King of Tokyo</a></li>
<li>Repo: <a href="${"https://github.com/browsertherapy/king-of-tokyo-clone/"}" rel="${"nofollow"}">king-of-tokyo-clone</a></li></ul>
<hr>
<h2 id="${"2-slides-accessible-horizontal-navigation"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-slides-accessible-horizontal-navigation"}"><span class="${"icon icon-link"}"></span></a>2. Slides: Accessible Horizontal Navigation</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/flexbox-nav.html"}" rel="${"nofollow"}"><img src="${"/images/slides/flex-nav.png"}" alt="${"Flex navigation slides"}"></a></p>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://css-tricks.com/snippets/css/a-guide-to-flexbox/"}" rel="${"nofollow"}">Complete Guide to Flexbox</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links#styling_links_as_buttons"}" rel="${"nofollow"}">Styling links as buttons</a></li></ul>
<h3 id="${"activity-create-a-horizontal-nav"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-create-a-horizontal-nav"}"><span class="${"icon icon-link"}"></span></a>Activity: Create a horizontal nav</h3>
<p>Refactor the following navigation with Flexbox to make it horizontal:</p>
<ul><li><a href="${"https://codepen.io/browsertherapy/pen/XWjwJGL"}" rel="${"nofollow"}">Typical vertical navigation menu</a></li></ul>
<p><strong>Spoilers</strong>:</p>
<ul><li><a href="${"https://codepen.io/browsertherapy/pen/YzqdGpR"}" rel="${"nofollow"}">Flexbox Navigation Examples</a></li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<h3 id="${"activity-make-your-own-horizontal-nav-menu"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-make-your-own-horizontal-nav-menu"}"><span class="${"icon icon-link"}"></span></a>Activity: Make your own horizontal nav menu</h3>
<p>Try to duplicate a horizontal navigation menu and banner using the above sample code.</p>
<p>Search for an example of a horizontal navigation menu online that you think you can duplicate.</p>
<ul><li>Which of the “horizontal menu” examples above best fit your selected menu? Are other Flexbox properties required to achieve the desired effect?</li>
<li>How much <code>padding</code> needs to be added to the <code>a</code> element?</li>
<li>What colours are used? How do you find this information? What elements are the colours applied to?</li>
<li>What other design elements are needed? What CSS properties are needed to create clickable links?</li></ul>
<h3 id="${"activity-play-some-learning-games"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-play-some-learning-games"}"><span class="${"icon icon-link"}"></span></a>Activity: Play some learning games!</h3>
<p>Learning games for Flexbox:</p>
<ul><li><a href="${"https://flexboxfroggy.com/"}" rel="${"nofollow"}">Flexbox Froggy</a></li>
<li><a href="${"https://mastery.games/flexboxzombies/"}" rel="${"nofollow"}">Flexbox Zombies</a></li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://css-tricks.com/snippets/css/a-guide-to-flexbox/"}" rel="${"nofollow"}">Complete Guide to Flexbox</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links#styling_links_as_buttons"}" rel="${"nofollow"}">Styling links as buttons</a></li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li><a href="${"https://www.youtube.com/watch?v=u044iM9xsWU"}" rel="${"nofollow"}">Learn flexbox the easy way</a> by Kevin Powell<ul><li>You can stop @11:13 but the rest of the video covers using flexbox with cards and columns;</li></ul></li>
<li><a href="${"https://youtu.be/hs3piaN4b5I"}" rel="${"nofollow"}">Flexbox vs. CSS Grid — Which is Better?</a> by Jenn Simmons</li>
<li><a href="${"https://www.youtube.com/watch?v=vQAvjof1oe4"}" rel="${"nofollow"}">Flexbox design patterns you can use in your projects</a> by Kevin Powell</li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“flexbox patterns”</li></ul>
<h3 id="${"digging-deeper-optional"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#digging-deeper-optional"}"><span class="${"icon icon-link"}"></span></a>Digging deeper (optional)</h3>
<ul><li><a href="${"https://flexbox.io/"}" rel="${"nofollow"}">What the Flexbox!?!</a><ul><li>A 20-video course on Flexbox by Web Bos;</li>
<li>Watch these videos if you want to learn more about Flexbox than what we cover in class.</li></ul></li>
<li>Learning games for Flexbox:<ul><li><a href="${"https://flexboxfroggy.com/"}" rel="${"nofollow"}">Flexbox Froggy</a></li>
<li><a href="${"https://mastery.games/flexboxzombies/"}" rel="${"nofollow"}">Flexbox Zombies</a></li></ul></li></ul>`;
});

export { _06_day_6 as default, metadata };
