import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/06-day-6.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Changing CSS with Javascript",
	"excerpt": null,
	"status": "draft"
};

const _06_day_6 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Assessment announcements<ul><li><a href="${"/courses/cpnt-262/assessments/assignment-2"}">Assignment 2</a><ul><li>Weight: 5%</li>
<li>Due: October 28th</li></ul></li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-2"}">Achievements Round 2</a><ul><li>Weight: 6%</li>
<li>Due: October 31st</li></ul></li></ul></li></ul>
<hr>
<h2 id="${"1-assessment-and-week-8-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-assessment-and-week-8-overview"}"><span class="${"icon icon-link"}"></span></a>1. Assessment and Week 8 overview</h2>
<p><strong>Week 8 Schedule</strong>:</p>
<ul><li>Today - <a href="${"/courses/cpnt-262/day-6"}">Changing CSS with Javascript</a></li>
<li>Tuesday - <a href="${"/courses/cpnt-262/day-7"}">Conditionals and form controls</a></li>
<li>Wednesday - <a href="${"/courses/cpnt-262/day-8"}">Loops!</a></li>
<li>Thursday - <a href="${"/courses/cpnt-262/day-9"}">Objects and JSON</a></li>
<li>Friday - <a href="${"/courses/cpnt-262/day-10"}">Fetching data asynchronously</a></li></ul>
<p><strong>Assessments</strong></p>
<ul><li><a href="${"/courses/cpnt-262/assessments/assignment-2"}">Assignment 2</a></li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-2"}">Achievements Round 2</a></li></ul>
<hr>
<h2 id="${"2-elementclasslist-api"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-elementclasslist-api"}"><span class="${"icon icon-link"}"></span></a>2. <code>Element.classList</code> API</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-changing-css.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-changing-css.png"}" alt="${"Slides - Changing CSS with Javascript"}"></a></p>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/API/Element/classList"}" rel="${"nofollow"}"><code>Element.classList</code></a></li></ul>
<h3 id="${"demo-dark-mode-toggle"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-dark-mode-toggle"}"><span class="${"icon icon-link"}"></span></a>Demo: Dark mode toggle</h3>
<p>Let’s build a checkbox that adds/removes a <code>dark-mode</code> class on the <code>&lt;body&gt;</code> element that changes a page’s <code>color</code> and <code>background-color</code>.</p>
<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-10-24-changing-css/01-starter-classlist"}" rel="${"nofollow"}">Starter code</a></li></ul>
<h3 id="${"activity"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity"}"><span class="${"icon icon-link"}"></span></a>Activity</h3>
<p>In groups of 2-3, create a button or checkbox that:</p>
<ul><li>uses <code>classList</code> to add/remove a <code>hide</code> class on another element;</li>
<li>makes a paragraph (or other page content) disappears and appears when a <code>hide</code> class is added/removed.</li></ul>
<hr>
<h2 id="${"3-css-variables"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-css-variables"}"><span class="${"icon icon-link"}"></span></a>3. CSS Variables</h2>
<h3 id="${"materials-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials-1"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties"}" rel="${"nofollow"}">Using CSS custom properties (variables)</a></li></ul>
<h3 id="${"demo-colour-slider"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-colour-slider"}"><span class="${"icon icon-link"}"></span></a>Demo: Colour slider</h3>
<p>If we have time, let’s add a colour slider that changes the colour angle of both light and dark modes at the same time.</p>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<ul><li><a href="${"/courses/cpnt-262/assessments/assignment-1"}">Assignment 1</a></li>
<li><a href="${"/courses/cpnt-262/assessments/assignment-2"}">Assignment 2</a></li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-2"}">Achievements Round 2</a></li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"css-variables"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#css-variables"}"><span class="${"icon icon-link"}"></span></a>CSS Variables</h3>
<ul><li>Reading list: <ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties"}" rel="${"nofollow"}">Using CSS custom properties (variables)</a><ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#values_in_javascript"}" rel="${"nofollow"}">Values in JavaScript</a></li></ul></li></ul></li>
<li>Watch list:<ul><li><a href="${"https://www.youtube.com/watch?v=NtRmIp4eMjs"}" rel="${"nofollow"}">CSS Variables in 100 Seconds</a> by Fireship</li>
<li><a href="${"https://www.youtube.com/watch?v=PHO6TBq_auI"}" rel="${"nofollow"}">CSS Variables - An introduction to CSS custom properties</a> by Kevin Powell</li></ul></li></ul>
<h3 id="${"elementclasslist"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#elementclasslist"}"><span class="${"icon icon-link"}"></span></a><code>Element.classList</code></h3>
<ul><li>Reading list:<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Web/API/Element/classList"}" rel="${"nofollow"}"><code>Element.classList</code></a></li></ul></li>
<li>Watch list:<ul><li><a href="${"https://www.youtube.com/watch?v=1e9BnA5ZIOk"}" rel="${"nofollow"}">Controlling a CSS ClassList with JavaScript</a> by Steve Griffith</li></ul></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“dark mode css variables”</li></ul>`;
});

export { _06_day_6 as default, metadata };
