import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-264/06-day-6.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Career and Consulting Services",
	"excerpt": null,
	"status": "draft"
};

const _06_day_6 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _06_day_6 as default, metadata };
