import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-200/06-day-6.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Deploying Strapi",
	"excerpt": null,
	"status": "draft"
};

const _06_day_6 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Ash will be covering this afternoon.</li>
<li><a href="${"/courses/cpnt-200/assessments/assignment-2#submission-instructions"}">Assignment 2 Submission Instructions</a> added</li>
<li><a href="${"/courses/cpnt-200/assessments/achievements#submission-instructions"}">README Instructions added to Achievements</a></li></ul>
<hr>
<h2 id="${"1-deployment-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-deployment-overview"}"><span class="${"icon icon-link"}"></span></a>1. Deployment Overview</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-200/strapi-deployment.html"}" rel="${"nofollow"}"><img src="${"/images/slides/deploy-strapi.png"}" alt="${"Slides - Deploy Strapi"}"></a></p>
<hr>
<h2 id="${"2-activity-deploy-strapi-to-rendercom"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-activity-deploy-strapi-to-rendercom"}"><span class="${"icon icon-link"}"></span></a>2. Activity: Deploy Strapi to render.com</h2>
<ul><li><a href="${"https://render.com/"}" rel="${"nofollow"}">render.com</a></li></ul>
<hr>
<h2 id="${"3-troubleshooting-and-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-troubleshooting-and-lab-time"}"><span class="${"icon icon-link"}"></span></a>3. Troubleshooting and Lab Time</h2>
<p>We’ll spend the rest of the day getting Strapi deployed.</p>
<hr>`;
});

export { _06_day_6 as default, metadata };
