import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/06-day-6.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _06_day_6 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>8-9am Open Lab will be available in Slack this week. The Zoom room can be opened if needed. </li>
<li>Today is the deadline for Round 1 Achievements (2pm).</li>
<li><a href="${"https://www.meetup.com/pxandpints/events/289814754/"}" rel="${"nofollow"}">Pixels tomorrow</a></li></ul>
<hr>
<h2 id="${"what-are-your-three-things"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#what-are-your-three-things"}"><span class="${"icon icon-link"}"></span></a>What are your three things?</h2>
<ul><li>Friday’s presentation will be easier to plan if you define three things you’d like to cover.</li></ul>
<p><strong>Tony’s three things:</strong></p>
<ol><li>Vanilla portfolio website deployed with Vite;</li>
<li>Colour pallettes with TailWind CSS;</li>
<li>Dark mode and colour pallette switcher with Typescript;</li></ol>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>Mini-lecture - Eli: 262 Group Project</li>
<li>Mini-lecture - Jesse: Tutorial overview </li>
<li>Mini-lecture - Ashley: Supabase</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<ul><li>Vanilla Vite build session with Tony</li></ul>
<hr>`;
});

export { _06_day_6 as default, metadata };
