import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/07-day-7.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _07_day_7 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Any Stage Work bookings for this morning?</li></ul>
<hr>
<h2 id="${"freelancing-as-a-developer"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#freelancing-as-a-developer"}"><span class="${"icon icon-link"}"></span></a>Freelancing as a Developer</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-265/contracting.html"}" rel="${"nofollow"}"><img src="${"/images/slides/contracting.png"}" alt="${"Slides - Contracting as a web developer"}"></a></p>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>TBA</li>
<li>TBA</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<hr>`;
});

export { _07_day_7 as default, metadata };
