import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-201/07-day-7.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 7 - Tailwind CSS",
	"excerpt": null,
	"status": "draft"
};

const _07_day_7 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"npm-recap"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#npm-recap"}"><span class="${"icon icon-link"}"></span></a>NPM Recap</h2>
<ul><li>NPM stands for “Node Package Manager”<ul><li>it is the package manger for the Node Runtime Environment (Javascript outside the browser)</li></ul></li>
<li>NPM is used to add packages such as javascript libraries to a website or app.</li>
<li>Start an NPM project by running <code>npm init</code><ul><li>this will walk you through setting up a basic project</li></ul></li>
<li>the <code>package.json</code> file is where your dependencies and project info are listed<ul><li><code>scripts</code> are actions that you can run, you set them up in the <code>package.json</code> file<ul><li>ie: <code>dev: &quot;node ./app.js&quot;</code> would mean for you to use the command <code>npm run dev</code> to run the <code>app.js</code> file</li></ul></li></ul></li>
<li><strong>ALWAYS</strong> have a <code>.gitignore</code> file in your project and add <code>node_modules</code> to it</li>
<li>you install packages with the command <code>npm install</code> or <code>npm i</code> <strong>inside your project folder</strong><ul><li>to install a package globally, add the flag <code>-g</code></li>
<li>run <code>npm i</code> in the <strong>root folder of your project</strong></li></ul></li>
<li>the dependencies files are stored in <code>node_modules/</code></li>
<li><strong>Read the documentation for the packages and libraries that you are using</strong></li></ul>
<hr>
<h2 id="${"assignments"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignments"}"><span class="${"icon icon-link"}"></span></a>Assignments</h2>
<h3 id="${"npm-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#npm-achievements"}"><span class="${"icon icon-link"}"></span></a>NPM Achievements</h3>
<ul><li>Due November 10th</li>
<li>Finish 4 Achievements at 5 points each</li></ul>
<h3 id="${"tailwind-assignment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tailwind-assignment"}"><span class="${"icon icon-link"}"></span></a>Tailwind Assignment</h3>
<ul><li>Due November 15</li>
<li>Set up tailwind in a project (install with npm)</li>
<li>Style content using tailwind syntax</li></ul>
<hr>
<h2 id="${"what-is-a-css-framework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#what-is-a-css-framework"}"><span class="${"icon icon-link"}"></span></a>What is a CSS Framework?</h2>
<p>CSS Frameworks are designed to make styling content easier and more maintainable. Technology and design are both fast moving fields and in web development, developers need to be able to respond to changes in branding and design concepts with minimal breaking changes and tech debt.</p>
<p>Frameworks such as tailwind aim to make styling web content easier, there are many different options that you have and they all have different workflows and goals.</p>
<h3 id="${"popular-css-frameworks"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#popular-css-frameworks"}"><span class="${"icon icon-link"}"></span></a>Popular CSS Frameworks</h3>
<ul><li><a href="${"https://tailwindcss.com/"}" rel="${"nofollow"}">Tailwind CSS</a>: Utility first css, highly customizable</li>
<li><a href="${"https://getbootstrap.com/"}" rel="${"nofollow"}">Bootstrap</a>: Component focused, lots of pre-built components, backed by twitter</li>
<li><a href="${"https://bulma.io/"}" rel="${"nofollow"}">Bulma</a>: No Javascript, fairly easy to learn</li>
<li><a href="${"https://getuikit.com/"}" rel="${"nofollow"}">Uikit</a>: Minimalism, not very customizable</li>
<li><a href="${"https://vuetifyjs.com/en/"}" rel="${"nofollow"}">Vuetify</a>: Vue Ui library, material design, vue focused</li></ul>
<h3 id="${"difference-between-a-css-framework-and-css-preprocessors"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#difference-between-a-css-framework-and-css-preprocessors"}"><span class="${"icon icon-link"}"></span></a>Difference Between a CSS Framework and CSS Preprocessors</h3>
<p>You’ll come across these terms often:</p>
<ul><li>SASS</li>
<li>SCSS</li>
<li>LESS</li>
<li>Stylus</li></ul>
<p>These are all css pre-processors and <strong>not</strong> css frameworks. They are used to extend css with additional functionality such as nested classes, mixins, and conditional logic.</p>
<p>While they are not css frameworks, they can be used with frameworks if you so desire. Just remember that more packages means more dependencies and more configuration to make everything work right.</p>
<hr>
<h2 id="${"tailwind-css"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tailwind-css"}"><span class="${"icon icon-link"}"></span></a>Tailwind CSS</h2>
<p>This is a utility class framework which means that the stylesheet is not component focused.</p>
<h3 id="${"basic-concepts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#basic-concepts"}"><span class="${"icon icon-link"}"></span></a>Basic Concepts</h3>
<ul><li><a href="${"https://tailwindcss.com/docs/utility-first"}" rel="${"nofollow"}">Utility First Fundamentals</a><ul><li>utility classes are used to style content</li>
<li>component concepts occur at content level, not stylesheet level</li></ul></li>
<li><a href="${"https://tailwindcss.com/docs/responsive-design"}" rel="${"nofollow"}">Responsive design</a><ul><li>Tailwind is mobile first, so when setting breakpoints, the smallest size is default and you add larger breakpoints for changes</li></ul></li>
<li><a href="${"https://tailwindcss.com/docs/theme"}" rel="${"nofollow"}">Theme Configuration</a><ul><li>Less of a concept and more of a method<ul><li>Tailwind uses a well structured configuration to define utility styles</li>
<li>In your configuration, you set your default sizes, hover shades, colors… mostly everything</li>
<li>You can also use <code>@layer base{}</code> in a css file to generate your own base styles - this is especially helpful for fonts</li></ul></li></ul></li>
<li>Aggressive Reset<ul><li>Tailwind has a pretty intense reset</li>
<li>It removes all base styles so you have complete control</li></ul></li>
<li><strong>When does tailwind excel?</strong><ul><li>When you’re using a templating system or framework where your content code is organized into small reusable <strong>components</strong>. These often have <strong>scoped</strong> styles which means that any css added to them is only relevant inside the component.</li></ul></li></ul>
<h4 id="${"breakout-a-tailwind-experiment-15min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#breakout-a-tailwind-experiment-15min"}"><span class="${"icon icon-link"}"></span></a>Breakout: A Tailwind Experiment [15min]</h4>
<ul><li><a href="${"https://gist.github.com/lilyx13/84400e9d8feb8a1940d5c67044b73077"}" rel="${"nofollow"}">Link to activity</a></li></ul>
<hr>
<h2 id="${"configuring-tailwind"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#configuring-tailwind"}"><span class="${"icon icon-link"}"></span></a>Configuring Tailwind</h2>
<h3 id="${"tailwind-as-an-npm-dependency"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tailwind-as-an-npm-dependency"}"><span class="${"icon icon-link"}"></span></a>Tailwind as an NPM Dependency</h3>
<p>Most npm packages require some level of configuration to make them work in a project. This will vary from package to package and also project to project. The most important takeaway here is to familiarize yourself with using docs to properly set up an npm package in your project - and in a way that enhances our project.</p>
<ul><li>Add tailwind to a project with <code>npm install</code><ul><li><a href="${"https://tailwindcss.com/docs/installation"}" rel="${"nofollow"}">see the docs</a></li></ul></li></ul>
<h4 id="${"breakout-session-tailwind-setup-10min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#breakout-session-tailwind-setup-10min"}"><span class="${"icon icon-link"}"></span></a>Breakout Session: Tailwind Setup (10min)</h4>
<ul><li><a href="${"https://gist.github.com/lilyx13/2ed0c859ce72a24a59f2e1c54c0778d4"}" rel="${"nofollow"}">Activity Link</a></li></ul>
<h4 id="${"tailwind-configuration-10min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tailwind-configuration-10min"}"><span class="${"icon icon-link"}"></span></a>Tailwind Configuration (10min)</h4>
<ul><li>Resources:<ul><li><a href="${"https://tailwindcss.com/docs/configuration"}" rel="${"nofollow"}">Tailwind Docs Configuration Page</a></li>
<li><a href="${"https://tailwindcss.com/docs/functions-and-directives#layer"}" rel="${"nofollow"}">How to use <code>@apply</code> and <code>@layer</code></a></li>
<li><a href="${"https://gist.github.com/lilyx13/f1c82147032f0b11a1ea8e6c36c681f6"}" rel="${"nofollow"}">Ashlyn’s Tailwind Config Gist</a></li></ul></li></ul>
<h3 id="${"useful-links"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#useful-links"}"><span class="${"icon icon-link"}"></span></a>Useful links</h3>
<p>These are a collection of doc pages from tailwind’s website that you will likely find useful.</p>
<ul><li><a href="${"https://tailwindcss.com/docs/hover-focus-and-other-states#disabled"}" rel="${"nofollow"}">Tailwind pseudo class dictionary</a></li>
<li><a href="${"https://tailwindcss.com/docs/dark-mode"}" rel="${"nofollow"}">Tailwind built in dark mode</a></li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li>Main Room: Discuss Mockup Assignment</li>
<li>Activity: Continue experimenting with tailwind in your fork of the provided repo from earlier<ul><li>recommended if you feel like you need a bit more practice</li></ul></li>
<li>Work on Assignments</li></ul>`;
});

export { _07_day_7 as default, metadata };
