import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/07-day-7.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "More Layout Patterns with Flexbox",
	"excerpt": "In this session, we'll dig deeper into Flexbox layout patterns.",
	"status": "draft"
};

const _07_day_7 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-260/assessments/achievements-2"}">Achievements Round 2</a><ul><li>Worth: 15 points</li>
<li>Due: Tuesday, October 4 @ 11:59pm</li></ul></li>
<li>CPNT 260 A2 marks will be returned Monday</li>
<li>Late-start challenge<ul><li>If 20 students submit an achievement by end-of-class tomorrow, we start at 9am on Monday!</li></ul></li></ul>
<hr>
<h2 id="${"1-hack-session-codepen-export-to-github-pages"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-hack-session-codepen-export-to-github-pages"}"><span class="${"icon icon-link"}"></span></a>1. Hack session: Codepen export to GitHub Pages?</h2>
<p>If we can figure out how to easily publish a Codepen to GH Pages, you can submit Pens for Assignments 3 &amp; 4.</p>
<h3 id="${"instructions-for-exporting-a-pen"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions-for-exporting-a-pen"}"><span class="${"icon icon-link"}"></span></a>Instructions for exporting a Pen</h3>
<ol><li>Export Codepen as a ZIP;</li>
<li>Expand the ZIP;</li>
<li>Copy the following files to a new GH repo;<ul><li><code>/dist/index.html</code> -&gt; <code>/index.html</code></li>
<li><code>/dist/style.css</code> -&gt; <code>/css/style.css</code></li>
<li><code>/dist/script.js</code> -&gt; <code>/js/script.js</code>, if applicable</li></ul></li>
<li>Enable GH Pages;</li>
<li>Submit to Brightspace as normal.</li></ol>
<hr>
<h2 id="${"2-slides-flexbox-extras"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-slides-flexbox-extras"}"><span class="${"icon icon-link"}"></span></a>2. Slides: Flexbox Extras</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/flexbox-extras.html"}" rel="${"nofollow"}"><img src="${"/images/slides/flex-nav.png"}" alt="${"Flex Extras slides"}"></a></p>
<h3 id="${"demo-mobile-first-media-queries"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-mobile-first-media-queries"}"><span class="${"icon icon-link"}"></span></a>Demo: Mobile-first media queries</h3>
<p>Let’s build a nav bar that is vertical on mobile and horizontal on desktop.</p>
<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-09-28-more-flex"}" rel="${"nofollow"}">Sample Code</a></li></ul>
<h3 id="${"watch-party"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-party"}"><span class="${"icon icon-link"}"></span></a>Watch party!</h3>
<ul><li><a href="${"https://youtu.be/hs3piaN4b5I"}" rel="${"nofollow"}">Flexbox vs. CSS Grid — Which is Better?</a> by Jenn Simmons</li></ul>
<h3 id="${"activity-horizontal-nav-with-sticky-footers"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-horizontal-nav-with-sticky-footers"}"><span class="${"icon icon-link"}"></span></a>Activity: Horizontal nav with sticky footers</h3>
<ol><li>Try building a sticky footer using code found in the slides;</li>
<li>Add the yesterday’s horizontal nav bar to the layout.</li></ol>
<hr>
<h2 id="${"3-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-lab-time"}"><span class="${"icon icon-link"}"></span></a>3. Lab Time</h2>
<ul><li><a href="${"/courses/cpnt-260/assessments/achievements-2"}">Achievements Round 2</a></li>
<li><a href="${"/courses/cpnt-260/assessments/assignment-3"}">Assignment 3</a></li></ul>
<p><strong>Bonus Demo</strong>: Sticky footers with CSS Grid</p>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure"}" rel="${"nofollow"}">Document and Website Structure</a></li>
<li><a href="${"https://css-tricks.com/snippets/css/complete-guide-grid/"}" rel="${"nofollow"}">Complete Guide to Grid</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids"}" rel="${"nofollow"}">Learning CSS Grid</a> on MDN</li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li><a href="${"https://youtu.be/KOvGeFUHAC0"}" rel="${"nofollow"}">Build a Classic Layout FAST in CSS Grid</a> by Miriam Suzanne<ul><li>You can stop watching @6:05; the rest describes an obscure way of doing the same thing (that you might like better).</li></ul></li>
<li>On <a href="${"https://gridbyexample.com/"}" rel="${"nofollow"}">Grid by Example</a>:<ul><li><a href="${"https://gridbyexample.com/video/series-define-a-grid/"}" rel="${"nofollow"}">Defining a Grid</a></li>
<li><a href="${"https://gridbyexample.com/video/series-the-fr-unit/"}" rel="${"nofollow"}">The <code>fr</code> unit</a></li>
<li><a href="${"https://gridbyexample.com/video/series-minmax/"}" rel="${"nofollow"}">Introducing <code>minmax()</code></a></li></ul></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“page layout patterns”</li></ul>
<h3 id="${"digging-deeper-optional"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#digging-deeper-optional"}"><span class="${"icon icon-link"}"></span></a>Digging deeper (optional)</h3>
<ul><li>Game: <a href="${"https://cssgridgarden.com/"}" rel="${"nofollow"}">Grid Garden</a></li>
<li>Other CSS Grid videos on <a href="${"https://gridbyexample.com/video/"}" rel="${"nofollow"}">Grid by Example</a></li></ul>`;
});

export { _07_day_7 as default, metadata };
