import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-200/07-day-7.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Review and Testing",
	"excerpt": null,
	"status": "draft"
};

const _07_day_7 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>CPNT 200 Assignment 3 Cancelled<ul><li>Assignments 1 &amp; 2 now 30% of final course mark</li></ul></li>
<li>Due dates extended<ul><li>Assignment 2: Due Monday Nov 14th (tonight)</li>
<li>Achievements: Due Thursday, Nov 17th</li></ul></li></ul>
<hr>
<h2 id="${"1-review-content-vs-template"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-review-content-vs-template"}"><span class="${"icon icon-link"}"></span></a>1. Review: Content vs Template</h2>
<ul><li>Template: The code of your website: HTML, CSS, JS</li>
<li>Content: Content-types stored in your Strapi project</li></ul>
<h3 id="${"demo-template-example-with-api"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-template-example-with-api"}"><span class="${"icon icon-link"}"></span></a>Demo: Template example with API</h3>
<ul><li>Starter code<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-11-14-strapi-review/01-starter-hero-example"}" rel="${"nofollow"}">Home page example</a></li>
<li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-11-14-strapi-review/02-fetch-api-example"}" rel="${"nofollow"}">API fetch example</a></li></ul></li></ul>
<h3 id="${"questions-to-ask"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#questions-to-ask"}"><span class="${"icon icon-link"}"></span></a>Questions to ask</h3>
<ul><li><strong>How often does it change?</strong></li>
<li><strong>Do you want to auto-generate it?</strong></li>
<li><strong>Does the client need to update it or add new ones?</strong><ul><li>Yes: Put it in Strapi</li>
<li>No: Put it in your template (i.e. it’s not a part of CPNT 200)</li></ul></li>
<li>Examples:<ul><li><strong>Form fields</strong>: Template</li>
<li><strong>Categories</strong>: Content<ul><li>Relation: if multiple Content-types use the same categories or if the Category has its own description or related Fields</li>
<li>Enumeration: if it’s used for one Content-type and it’s a simple word/phrase with no other information (i.e. blog status)</li></ul></li>
<li><strong>Navigation</strong>: Could go either way (but usually in Template)<ul><li>Template: if the nav is static and does not change very often</li>
<li>Content: if the nav changes often or the client needs to update it themselves</li></ul></li>
<li><strong>Hero images</strong>: Could go either way<ul><li>Template: if the image never changes</li>
<li>Content: if the image needs to be updated by the client or if it’s part of a Content-type (i.e. Blog Post image)</li></ul></li></ul></li></ul>
<hr>
<h2 id="${"2-tests-for-non-deploy-option-for-strapi-submission"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-tests-for-non-deploy-option-for-strapi-submission"}"><span class="${"icon icon-link"}"></span></a>2. Tests for non-deploy option for Strapi Submission</h2>
<h3 id="${"warnings-for-rendercom-deployment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#warnings-for-rendercom-deployment"}"><span class="${"icon icon-link"}"></span></a>Warnings for Render.com deployment</h3>
<ul><li>Render.com will reset your content database any time you update your Content-types (or push any changes to your repo).</li>
<li>Confirm your Content-types and finish uploading content <em>before</em> you begin deploying or you may lose work.</li></ul>
<h3 id="${"testing-help"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#testing-help"}"><span class="${"icon icon-link"}"></span></a>Testing help</h3>
<p>If anyone has their Strapi project ready to submit, please submit it to Brightspace so Tony can test if he can build a local installation if deployment doesn’t work</p>
<p>Submit the following:</p>
<ul><li>A ZIP of your Strapi project files</li>
<li>Your <code>.env</code> file</li>
<li>Your <code>/.tmp/data.db</code> file</li>
<li>A link to your repo</li></ul>
<hr>
<h2 id="${"3-afternoon-strapi-install-review"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-afternoon-strapi-install-review"}"><span class="${"icon icon-link"}"></span></a>3. Afternoon: Strapi install review</h2>
<p>Your last chance to ask any questions to get your Strapi project installed, configured and deployed.</p>
<hr>`;
});

export { _07_day_7 as default, metadata };
