import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/07-day-7.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 7 - Website UI Design I",
	"excerpt": null,
	"status": "draft"
};

const _07_day_7 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"figma-mockup-design"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#figma-mockup-design"}"><span class="${"icon icon-link"}"></span></a>Figma Mockup Design</h2>
<p>This is the next logical step after wireframing. It’s when you design the basics of your layout and apply your design system + add assets such as images.</p>
<p>We will be aiming for medium resolution designs. You can and should create mobile versions for at least one of your pages, especially if you’re attempting any challenging layouts to make sure that they render well. This will also help your development process by giving you a better visual of how your site content needs to flow.</p>
<h3 id="${"what-is-a-mockup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#what-is-a-mockup"}"><span class="${"icon icon-link"}"></span></a>What is a mockup?</h3>
<p>A mockup is a depiction of what something will more or less look like when finished. Generally you’ll put a mockup onto a template of a screen to show it in context.</p>
<h3 id="${"important-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#important-points"}"><span class="${"icon icon-link"}"></span></a>Important Points</h3>
<ul><li>Use the grid</li>
<li>Apply a design system soon after starting</li>
<li>Stick with your design system</li>
<li>Group items logically (and don’t be afraid to ungroup and change things)</li>
<li>Make use of plugins to speed up your process</li>
<li>Look to web pages that you would like to emulate, especially while learning</li></ul>
<h2 id="${"activity-mockup-a-card-design-30min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-mockup-a-card-design-30min"}"><span class="${"icon icon-link"}"></span></a>Activity: Mockup a card design (30min)</h2>
<ul><li>In a new figma file, create a desktop sized artboard</li>
<li>Set up a 12 column grid layout</li>
<li>Create a simple card design that would be able to be duplicated on the 12 column layout<ul><li>follow <a href="${"https://material.io/components/cards"}" rel="${"nofollow"}">material design guidelines</a></li>
<li><strong>or</strong> model it off of a card design from a website that you frequent</li></ul></li></ul>
<hr>
<h2 id="${"components"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#components"}"><span class="${"icon icon-link"}"></span></a>Components</h2>
<p>It’s good to learn how components work by building your own first. However for fast production of mockups, you can use prebuilt component UI libraries. When you get to the development phase, this speed can be continued by using corresponding css frameworks.
o</p>
<ul><li><a href="${"https://help.figma.com/hc/en-us/articles/360038663154"}" rel="${"nofollow"}">Short doc on making a component in figma</a></li></ul>
<h3 id="${"activity-turn-your-card-into-a-component-15min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-turn-your-card-into-a-component-15min"}"><span class="${"icon icon-link"}"></span></a>Activity: Turn your card into a component (15Min)</h3>
<ul><li>Use the card you designed in our first Activity</li>
<li>Turn it into a component</li>
<li>Duplicate the component to make a 3 card pattern</li>
<li>Change the information in the cards so that they are distinct</li></ul>
<hr>
<h2 id="${"ui-kits-to-try"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#ui-kits-to-try"}"><span class="${"icon icon-link"}"></span></a>UI Kits to try</h2>
<p>Keep in mind that many of these will have a limited free version and a premium full version</p>
<ul><li><a href="${"https://www.figma.com/community/file/958383439532195363"}" rel="${"nofollow"}">Official Tailwind CSS for Figma</a></li>
<li><a href="${"https://www.figma.com/community/file/768809027799962739"}" rel="${"nofollow"}">Tailwind CSS UI Kit</a></li>
<li><a href="${"https://www.figma.com/community/file/832800692655327277"}" rel="${"nofollow"}">Bootstrap 4 UI Kit</a></li>
<li><a href="${"https://www.figma.com/community/file/809487622678629513"}" rel="${"nofollow"}">Figma IOS UI Kit</a></li>
<li><a href="${"https://www.figma.com/community/file/880534892514982400"}" rel="${"nofollow"}">Material Design UI Kit</a></li></ul>
<h3 id="${"debrief-discussion"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief-discussion"}"><span class="${"icon icon-link"}"></span></a>Debrief Discussion</h3>
<ul><li>Review work as a group</li>
<li>Discuss UI kit experiences</li>
<li>Make sure everyone can create components</li></ul>
<hr>
<h2 id="${"content-plugins"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#content-plugins"}"><span class="${"icon icon-link"}"></span></a>Content Plugins</h2>
<ul><li><a href="${"https://www.figma.com/community/plugin/791103617505812222/Icons8-Free-Icons"}" rel="${"nofollow"}">Icons8 Icons</a></li>
<li><a href="${"https://www.figma.com/community/plugin/774202616885508874/Font-Awesome-Icons"}" rel="${"nofollow"}">Font Awesome Icons</a></li>
<li><a href="${"https://www.figma.com/community/plugin/809860933081065308/LottieFiles"}" rel="${"nofollow"}">LottieFiles</a></li>
<li><a href="${"https://www.figma.com/community/plugin/738454987945972471/Unsplash"}" rel="${"nofollow"}">Unsplash</a></li>
<li><a href="${"https://www.figma.com/community/plugin/736000994034548392/Lorem-ipsum"}" rel="${"nofollow"}">Lorem Ipsum</a></li></ul>
<hr>
<h2 id="${"homework"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#homework"}"><span class="${"icon icon-link"}"></span></a>Homework</h2>
<ul><li>Explore using different libraries and plugins to speed up your design process</li>
<li>Work on your assignments</li></ul>`;
});

export { _07_day_7 as default, metadata };
