import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/08-day-8.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Day 8 - Website UI Design II",
	"excerpt": null,
	"status": "draft"
};

const _08_day_8 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"assignment-and-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignment-and-achievements"}"><span class="${"icon icon-link"}"></span></a>Assignment and Achievements</h2>
<ul><li>Assignment 4 UI Mockup<ul><li>Due: Monday October 17 @ 11:59PM</li>
<li>Focus: Create a home page mockup with a design system</li></ul></li>
<li>Achievements UI Design<ul><li>Due: Friday October 21 @ 11:59PM</li>
<li>Goal: Complete 4 design achievements</li></ul></li></ul>
<h2 id="${"design-systems"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#design-systems"}"><span class="${"icon icon-link"}"></span></a>Design Systems</h2>
<p>A design system is very useful for creating mockups and prototypes quickly and consistently. A design system is a set of rules regarding visual elements such as: color, typography, spacing, border radius, and pseudo states.</p>
<p>A design system also include commonly used components such as buttons, cards, panels. Just like with the style assets, you can take a very structured approach to your components, or you can set up a minimal system. It depends on the scope of the project.</p>
<p>We are going to create a design system in Figma. These will be applied to both our mockups as well as our actual code. This is possible by using Figma plugins to export stylesheets based on our design systems.</p>
<h3 id="${"important-plugins"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#important-plugins"}"><span class="${"icon icon-link"}"></span></a>Important Plugins</h3>
<ul><li><a href="${"https://www.figma.com/community/plugin/927255248672920500/StyleList-%E2%80%93-text-and-color-styles"}" rel="${"nofollow"}">StyleList</a>: Create text and color styles</li>
<li><a href="${"https://www.figma.com/community/plugin/739475857305927370/Color-Designer"}" rel="${"nofollow"}">Color Designer</a>]: Another color palette generator</li>
<li><a href="${"https://www.figma.com/community/plugin/815841134222084922/Color-Scheme"}" rel="${"nofollow"}">Color Scheme</a>: Similar to StyleList for color generation</li>
<li><a href="${"https://designcode.io/figma-handbook-exporting-css-codes"}" rel="${"nofollow"}">CSS Export</a>: Export Vanilla CSS</li>
<li><a href="${"https://www.figma.com/community/plugin/785619431629077634/Figma-Tailwindcss"}" rel="${"nofollow"}">Figma Tailwind</a>: Export a Tailwind Configuration</li>
<li><a href="${"https://www.figma.com/community/plugin/738806869514947558/Tailwind-CSS"}" rel="${"nofollow"}">Tailwind Import</a>: Import a tailwind configuration file into Figma</li></ul>
<hr>
<h2 id="${"design-system-setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#design-system-setup"}"><span class="${"icon icon-link"}"></span></a>Design System Setup</h2>
<ul><li><a href="${"https://www.figma.com/best-practices/components-styles-and-shared-libraries/"}" rel="${"nofollow"}">Figma Design System Best Practices</a></li></ul>
<ol><li>Pick colors and generate variations</li>
<li>Pick typography and generate variations</li>
<li>Create a couple simple components to generate:<ul><li>border-radius</li>
<li>effect styles</li></ul></li></ol>
<h3 id="${"activity-create-a-color-scheme-for-your-design-system-15min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-create-a-color-scheme-for-your-design-system-15min"}"><span class="${"icon icon-link"}"></span></a>Activity: Create a color scheme for your design system (15min)</h3>
<ul><li>Use one of the above specified, or any other color palette generator</li>
<li>Create a color palette that includes<ul><li>a primary color</li>
<li>a secondary color</li>
<li>grayscale shades</li></ul></li>
<li>Set between 5 - 10 variations</li></ul>
<h3 id="${"activity-create-a-typography-scheme-for-your-design-system-15min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-create-a-typography-scheme-for-your-design-system-15min"}"><span class="${"icon icon-link"}"></span></a>Activity: Create a Typography Scheme for your design system (15min)</h3>
<ul><li><a href="${"https://www.figma.com/resources/learn-design/typography/"}" rel="${"nofollow"}">Extra Reading: Typography</a></li>
<li>Choose 2 fonts<ul><li>Heading</li>
<li>Body Text</li></ul></li>
<li>Set up all of your font variations<ul><li>Label them based on html font names or based on utility class styles</li></ul></li></ul>
<h3 id="${"debrief"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief"}"><span class="${"icon icon-link"}"></span></a>Debrief</h3>
<ul><li>Show off your work</li>
<li>Ask questions</li>
<li>Learn from one another</li></ul>
<hr>
<h2 id="${"prototyping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prototyping"}"><span class="${"icon icon-link"}"></span></a>Prototyping</h2>
<p>Protoyping adds functionality to your design. This includes navigation between pages, navigation on pages, animations and movement of elements</p>
<h3 id="${"prototyping-basics"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prototyping-basics"}"><span class="${"icon icon-link"}"></span></a>Prototyping Basics</h3>
<ul><li>In the left panel, select <code>Prototype</code></li>
<li>From here you’ll be able to set prototype features onto your pages</li>
<li>To create good prototypes, you’ll be duplicating your frames to set before and after states for your various prototype features</li>
<li>Be really happy with your mockup before you do too much prototyping (links get copied and this can get messy)</li>
<li>clean up your design</li></ul>
<h4 id="${"main-steps-in-prototyping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#main-steps-in-prototyping"}"><span class="${"icon icon-link"}"></span></a>Main steps in prototyping</h4>
<ul><li>Group your frames based on the type of prototypes you’re doing</li>
<li>Set up your before and after states</li>
<li>Make sure that you’re on the prototype setting</li>
<li>Link the state changes</li>
<li>Set the interaction details<ul><li>animation type</li>
<li>interaction</li>
<li>destination</li>
<li>time</li></ul></li></ul>
<h4 id="${"things-to-prototype"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#things-to-prototype"}"><span class="${"icon icon-link"}"></span></a>Things to prototype</h4>
<ul><li>top bar navigation</li>
<li>mobile menu slide in</li>
<li>hover states (buttons)</li>
<li>image carosel</li>
<li>anchor links</li></ul>
<h3 id="${"activity-test-out-prototyping-20min"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-test-out-prototyping-20min"}"><span class="${"icon icon-link"}"></span></a>Activity: Test out Prototyping (20min)</h3>
<ul><li>Duplicate your mockup</li>
<li>Change something on it (pick something that you would like to animate)</li>
<li>Set up the animation to work as discussed</li></ul>
<h4 id="${"debrief-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#debrief-1"}"><span class="${"icon icon-link"}"></span></a>Debrief</h4>
<ul><li>Show off your prototype’s behaviour</li></ul>
<hr>`;
});

export { _08_day_8 as default, metadata };
