import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/08-day-8.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _08_day_8 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"https://sait-ca.zoom.us/j/88183669794?pwd=WmZCODd0RUZuWHZwLytlb3ArVzYzZz09"}" rel="${"nofollow"}">Zoom room for Final Presentations</a><ul><li>Friday at 10am</li>
<li>We’ll meet in our regular Zoom room at 9am to cover any last minute prep and cheer leading.</li></ul></li>
<li>Don’t forget to book a slot in the <a href="${"/courses/cpnt-265/day-10"}">Friday agenda</a></li></ul>
<hr>
<h2 id="${"flex-session"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#flex-session"}"><span class="${"icon icon-link"}"></span></a>Flex Session</h2>
<hr>
<h2 id="${"1030am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1030am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10:30am - Stage Work Achievements</h2>
<ol><li>Mini-lecture - Rustu: Firebase</li>
<li>TBA</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<hr>`;
});

export { _08_day_8 as default, metadata };
