import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/08-day-8.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Loops!",
	"excerpt": null,
	"status": "draft"
};

const _08_day_8 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Late start challenge for a 9am start tomorrow - Submit either:<ul><li>a solution to one of these <a href="${"https://avantutor.com/blog/10-simple-javascript-for-loop-exercises/"}" rel="${"nofollow"}"><code>for</code> loop exercises</a>, OR;</li>
<li>an <a href="${"/courses/cpnt-262/assessments/achievements-2"}">Achievement for Round 2</a>.</li></ul></li>
<li>Achievements Round 1 marks returned after lunch</li></ul>
<hr>
<h2 id="${"1-phrase-generator-setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-phrase-generator-setup"}"><span class="${"icon icon-link"}"></span></a>1. Phrase Generator Setup</h2>
<p>Today we’ll build a form that generates a multi-word phrase similar to Tony’s <a href="${"https://acidtone.github.io/namor"}" rel="${"nofollow"}">Random Band Generator</a>.</p>
<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-10-26-for-loops/01-phrase-generator-starter"}" rel="${"nofollow"}">Starter code</a></li>
<li><a href="${"https://gist.github.com/acidtone/2a3cac26a229aa95685e5cf6344f2e4e"}" rel="${"nofollow"}">Random Array Items</a></li></ul>
<hr>
<h2 id="${"2-for-loop"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-for-loop"}"><span class="${"icon icon-link"}"></span></a>2. <code>for</code> Loop</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-for-loops.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-for-loops.png"}" alt="${"Slides - for Loops"}"></a></p>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration#for_statement"}" rel="${"nofollow"}"><code>for</code> statement</a></li></ul>
<h3 id="${"demo-output-1-100-as-a-bulleted-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-output-1-100-as-a-bulleted-list"}"><span class="${"icon icon-link"}"></span></a>Demo: Output 1-100 as a bulleted list</h3>
<ul><li>Starter Code: <a href="${"https://gist.github.com/acidtone/e87aa5564ae1b286beca66b07d52550f"}" rel="${"nofollow"}">Print 1-to-100 with a <code>for</code> Loop</a></li></ul>
<h3 id="${"activity-loop-exercises"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-loop-exercises"}"><span class="${"icon icon-link"}"></span></a>Activity: Loop exercises</h3>
<p>Practice loops with the exercises listed in this article:</p>
<ul><li><a href="${"https://avantutor.com/blog/10-simple-javascript-for-loop-exercises/"}" rel="${"nofollow"}">10 Simple Javascript For-Loop Exercises</a></li></ul>
<hr>
<h2 id="${"3-demo-phrase-generator"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-demo-phrase-generator"}"><span class="${"icon icon-link"}"></span></a>3. Demo: Phrase Generator</h2>
<p>Let’s finish off our Phrase Generator using our knowledge of <code>for</code> loops.</p>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<ul><li>Late start challenge</li>
<li><a href="${"/courses/cpnt-262/assessments/assignment-2"}">Assignment 2</a></li>
<li><a href="${"/courses/cpnt-262/assessments/achievements-2"}">Achievements Round 2</a></li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration#for_statement"}" rel="${"nofollow"}"><code>for</code> statement</a><ul><li>Note: there are a lot of ways to loop; we’ll stick with <code>for</code> for now;</li></ul></li>
<li>Gist: <a href="${"https://gist.github.com/acidtone/e87aa5564ae1b286beca66b07d52550f"}" rel="${"nofollow"}">Print 1-to-100 with a <code>for</code> Loop</a></li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li>Video: <a href="${"https://www.youtube.com/watch?v=s9wW2PpJsmQ"}" rel="${"nofollow"}"><code>for</code> Loop</a> by Mosh Hamedani</li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“beginner js for loop exercises”</li></ul>`;
});

export { _08_day_8 as default, metadata };
