import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/08-day-8.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Hero Sections and CTAs",
	"excerpt": "In this session, we'll talk about the home page and how it differs from internal pages - the Hero section.",
	"status": "draft"
};

const _08_day_8 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/achievements-2"}" rel="${"nofollow"}">Achievements Round 2</a> dropbox opened in Brightspace</li>
<li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/assignment-1"}" rel="${"nofollow"}">CNT 260 Assignment 1</a> marks will be released later this morning</li>
<li>Late-start challenge<ul><li>If 18 students submit an achievement by end-of-class tomorrow, we start at 9am on Monday!</li></ul></li></ul>
<hr>
<h2 id="${"slides-heros-and-banners-with-flexbox"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#slides-heros-and-banners-with-flexbox"}"><span class="${"icon icon-link"}"></span></a>Slides: Heros and Banners with Flexbox</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/heros-banners.html"}" rel="${"nofollow"}"><img src="${"/images/slides/heros-banners.png"}" alt="${"Heros and banners slides"}"></a></p>
<hr>
<h2 id="${"demos"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demos"}"><span class="${"icon icon-link"}"></span></a>Demos</h2>
<ul><li>Banners with nested flexbox</li>
<li>Hero sections</li></ul>
<h2 id="${"activity-hero-section"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-hero-section"}"><span class="${"icon icon-link"}"></span></a>Activity: Hero Section</h2>
<p>Create your own full-viewport hero section:</p>
<ol><li>Select an large-format image on your file system or on Lorem Picsum for your background image;</li>
<li>Create a full-viewport <code>&lt;header&gt;</code> with a height of <code>100vh</code>;</li>
<li>Add a CSS background image using the image you selected;</li>
<li>Add HTML content of your choice to the <code>&lt;header&gt;</code>;</li>
<li>Using Flexbox (of Grid), position your content over top your background image so that it’s pretty and readable.</li></ol>
<hr>
<h2 id="${"assignment-1-solution-review"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#assignment-1-solution-review"}"><span class="${"icon icon-link"}"></span></a>Assignment 1 Solution Review</h2>
<ul><li>TBA: Assignment example solution</li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<h3 id="${"late-start-challenge"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#late-start-challenge"}"><span class="${"icon icon-link"}"></span></a>Late-start challenge</h3>
<p>If 18 students submit an achievement by end-of-class tomorrow, we start at 9am on Monday!</p>
<p>Submit your project to Achievements Round 2 in Brightspace.</p>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Backgrounds_and_borders"}" rel="${"nofollow"}">Backgrounds and Borders</a></li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li>Layout Land by Jen Simmons<ul><li><a href="${"https://youtu.be/_sgF8I-Q1Gs"}" rel="${"nofollow"}">Introduction to Viewport Units</a></li>
<li><a href="${"https://www.youtube.com/watch?v=0X6zrW2QW8Q"}" rel="${"nofollow"}">Unlocking the Power of CSS Overrides</a><ul><li>This is Part 4 of a 7-part series. Parts 1-3 are listed below as optional (but recommended) background theory.</li></ul></li></ul></li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“best hero sections”</li>
<li>“hero section css”</li>
<li>“call to action css”</li></ul>
<h3 id="${"digging-deeper-optional"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#digging-deeper-optional"}"><span class="${"icon icon-link"}"></span></a>Digging Deeper (optional)</h3>
<ul><li>Resilient CSS by Jen Simmons<ul><li>Part 1: <a href="${"https://www.youtube.com/watch?v=u00FY9vADfQ"}" rel="${"nofollow"}">Introduction to Resilient CSS</a></li>
<li>Part 2: <a href="${"https://www.youtube.com/watch?v=WM_cKHH7bZ0"}" rel="${"nofollow"}">The Secrets of “Can I Use”</a></li>
<li>Part 3: <a href="${"https://www.youtube.com/watch?v=NJjlzxud4_M"}" rel="${"nofollow"}">How Browsers Handle Errors in CSS</a></li></ul></li></ul>`;
});

export { _08_day_8 as default, metadata };
