import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-201/08-day-8.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "To Be Announced",
	"excerpt": null,
	"status": "draft"
};

const _08_day_8 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _08_day_8 as default, metadata };
