import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/09-day-9.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Objects and JSON",
	"excerpt": null,
	"status": "draft"
};

const _09_day_9 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"1-for-loop-spoilers"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-for-loop-spoilers"}"><span class="${"icon icon-link"}"></span></a>1. <code>for</code> Loop Spoilers</h2>
<h3 id="${"materials"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#materials"}"><span class="${"icon icon-link"}"></span></a>Materials</h3>
<ul><li><a href="${"https://avantutor.com/blog/10-simple-javascript-for-loop-exercises/"}" rel="${"nofollow"}">10 Simple Javascript For-Loop Exercises</a></li>
<li><a href="${"https://dev.to/lukeshiru/shortest-fizzbuzz-4goa"}" rel="${"nofollow"}">Shortest FizzBuzz</a></li></ul>
<hr>
<h2 id="${"2-conditional-code"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-conditional-code"}"><span class="${"icon icon-link"}"></span></a>2. Conditional Code</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-262/js-conditional-code.html"}" rel="${"nofollow"}"><img src="${"/images/slides/js-conditional-code.png"}" alt="${"Slides - Conditional code"}"></a></p>
<h3 id="${"is-javscript-broken"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#is-javscript-broken"}"><span class="${"icon icon-link"}"></span></a>Is Javscript broken?</h3>
<ul><li>Question: Why does <code>3 &gt; 2 &gt; 1</code> evaluate to <code>false</code>?</li></ul>
<hr>
<h2 id="${"3-activity-object-oriented-treasure-hunt"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-activity-object-oriented-treasure-hunt"}"><span class="${"icon icon-link"}"></span></a>3. Activity: Object-oriented Treasure Hunt</h2>
<ul><li>Gist: <a href="${"https://gist.github.com/acidtone/f4ff695f2db428344549e1ae045e0439"}" rel="${"nofollow"}">Instructions and Sample code</a></li></ul>
<hr>
<h2 id="${"4-lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-lab-time"}"><span class="${"icon icon-link"}"></span></a>4. Lab Time</h2>
<ul><li>Early dismissal</li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"objects"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#objects"}"><span class="${"icon icon-link"}"></span></a>Objects</h3>
<ul><li>Reading list (MDN): <ul><li><a href="${"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics"}" rel="${"nofollow"}">Object basics</a></li>
<li><a href="${"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects"}" rel="${"nofollow"}">Working_with_Objects</a></li></ul></li></ul>
<h3 id="${"json"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#json"}"><span class="${"icon icon-link"}"></span></a>JSON</h3>
<ul><li>Reading list:<ul><li>MDN: <a href="${"https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON"}" rel="${"nofollow"}">Working with JSON data</a></li></ul></li></ul>`;
});

export { _09_day_9 as default, metadata };
