import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/09-day-9.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Galleries and columns",
	"excerpt": "In this session, we'll continue our discussion on Flexbox when creating galleries, plus a responsive grid gallery technique.",
	"status": "draft"
};

const _09_day_9 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li>Schedule update:<ul><li>Wednesday and Thursday -&gt; CPNT 201</li>
<li>Friday and Tuesday -&gt; DSGN 270</li></ul></li>
<li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/assignment-4"}" rel="${"nofollow"}">Assignment 4</a></li>
<li>Final Project will be announced tomorrow<ul><li>Due date: Friday, Oct 14th @ 11:59pm</li>
<li>This will be a group project</li>
<li>Weight:<ul><li>Peer Evaluation: 10%</li>
<li>Project: 20%</li></ul></li></ul></li>
<li>Comments and changes to <a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/achievements-2"}" rel="${"nofollow"}">Achievements Round 2</a></li></ul>
<hr>
<h2 id="${"1-assignment-2-solution-review"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-assignment-2-solution-review"}"><span class="${"icon icon-link"}"></span></a>1. Assignment 2 Solution Review</h2>
<p>Marks for Assignment 2 will be released after lunch but here is how Tony did it:</p>
<ul><li><a href="${"https://github.com/sait-wbdv/f22-spoilers-cpnt260-a2"}" rel="${"nofollow"}">GitHub repo</a></li>
<li><a href="${"https://sait-wbdv.github.io/f22-spoilers-cpnt260-a2/"}" rel="${"nofollow"}">Live Site</a></li></ul>
<hr>
<h2 id="${"2-slides-flexbox-galleries"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-slides-flexbox-galleries"}"><span class="${"icon icon-link"}"></span></a>2. Slides: Flexbox galleries</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-260/flexbox-intermediate.html"}" rel="${"nofollow"}"><img src="${"/images/slides/flexbox-intermediate.png"}" alt="${"Intermediate Flexbox slides"}"></a></p>
<h3 id="${"demo-course-gallery-page"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-course-gallery-page"}"><span class="${"icon icon-link"}"></span></a>Demo: Course gallery page</h3>
<ul><li><a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-10-03-galleries/01-course-page-starter"}" rel="${"nofollow"}">starter code</a></li></ul>
<h3 id="${"activity-card-gallery"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#activity-card-gallery"}"><span class="${"icon icon-link"}"></span></a>Activity: Card gallery</h3>
<p>Create a list of cards and display them as a gallery:</p>
<ol><li>Take your card assignment, the <a href="${"https://github.com/sait-wbdv/f22-spoilers-cpnt260-a2"}" rel="${"nofollow"}">answer solution to 260-a2</a>, <a href="${"https://github.com/sait-wbdv/dailies-f22/tree/main/2022-10-03-galleries/04-activity-flex-gallery-starter"}" rel="${"nofollow"}">this starter gallery</a> or build a new list of at least 6 cards;</li>
<li>Wrap your cards in a container such as a <code>&lt;section&gt;</code> element;<ul><li>Create a flex container with <code>display: flex;</code></li>
<li>Wrap your items with <code>flex-wrap: wrap;</code></li>
<li>Centre your items with <code>justify-content: center;</code></li>
<li>Space out your items with <code>gap: 1rem;</code> (or similar length);</li></ul></li>
<li>Using your choice of <code>flex</code> values (and optional media queries), style a responsive gallery that:<ul><li>has 3 or more columns on wide screens;</li>
<li>has only one column on mobile screens.</li></ul></li></ol>
<p><strong>Questions to consider</strong>:</p>
<ul><li>How wide should the items be?</li>
<li>Should they grow when there’s extra space?</li>
<li>What happens if you set the width with <code>width</code> or the “Flex-way” with <code>flex-basis</code>?</li></ul>
<hr>
<h2 id="${"1x3-card-block"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1x3-card-block"}"><span class="${"icon icon-link"}"></span></a>1x3 Card block?</h2>
<p>If we have time, we’ll take a look at how you can use Flexbox to create a responsive row of 3 cards.</p>
<ul><li><a href="${"https://www.youtube.com/watch?v=vQAvjof1oe4"}" rel="${"nofollow"}">Flexbox design patterns you can use in your projects</a> by Kevin Powell</li>
<li><a href="${"https://codepen.io/acidtone/pen/JjvpOKR"}" rel="${"nofollow"}">Example Flexbox layouts</a></li>
<li><a href="${"https://css-tricks.com/equal-columns-with-flexbox-its-more-complicated-than-you-might-think/"}" rel="${"nofollow"}">Equal Columns With Flexbox</a> on CSS Tricks</li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<ul><li><a href="${"/courses/dsgn-270/assessments/assignment-3"}">DSGN 270 Assignment 3</a></li>
<li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/assignment-4"}" rel="${"nofollow"}">CPNT 260 Assignment 4</a></li>
<li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/achievements-2"}" rel="${"nofollow"}">Achievements Round 2</a></li></ul>
<hr>
<h2 id="${"prep"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#prep"}"><span class="${"icon icon-link"}"></span></a>Prep</h2>
<h3 id="${"reading-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#reading-list"}"><span class="${"icon icon-link"}"></span></a>Reading list</h3>
<ul><li><a href="${"https://css-tricks.com/snippets/css/a-guide-to-flexbox/"}" rel="${"nofollow"}">Complete Guide to Flexbox</a></li>
<li><a href="${"https://css-tricks.com/snippets/css/complete-guide-grid/"}" rel="${"nofollow"}">Complete Guide to Grid</a></li></ul>
<h3 id="${"watch-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#watch-list"}"><span class="${"icon icon-link"}"></span></a>Watch list</h3>
<ul><li><a href="${"https://youtu.be/tFKrK4eAiUQ"}" rel="${"nofollow"}">Incredibly Easy Layouts with CSS Grid</a> by Jenn Simmons</li>
<li><a href="${"https://www.youtube.com/watch?v=u044iM9xsWU"}" rel="${"nofollow"}">Learn flexbox the easy way</a> by Kevin Powell</li></ul>
<h3 id="${"search-list"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#search-list"}"><span class="${"icon icon-link"}"></span></a>Search list</h3>
<ul><li>“galleries css grid”</li>
<li>“css grid masonry”</li>
<li>“galleries flexbox”</li></ul>`;
});

export { _09_day_9 as default, metadata };
