import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/09-day-9.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Flex Day",
	"excerpt": null,
	"status": "draft"
};

const _09_day_9 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"housekeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#housekeeping"}"><span class="${"icon icon-link"}"></span></a>Housekeeping</h2>
<ul><li><a href="${"/courses/cpnt-265/assessments"}">Course Assessments</a><ul><li><a href="${"/courses/cpnt-265/assessments/final-project/"}">Final Project presentation</a><ul><li>Weight: 30% of final course mark</li>
<li>We’ll be meeting at 9am in our regular room for prep and cheer leading</li>
<li>Presentations start @ 10am in <a href="${"https://sait-ca.zoom.us/j/88183669794?pwd=WmZCODd0RUZuWHZwLytlb3ArVzYzZz09"}" rel="${"nofollow"}">this room</a></li></ul></li></ul></li>
<li>Deadline to submit Achievements is today at 2pm!<ul><li>Don’t forget to submit Roster Card info; it’s an easy 5 points and really helps out Tony.</li></ul></li>
<li>It’s time to claim a spot in the agenda tomorrow (first come, first served):<ul><li>Time slot?</li>
<li>Presentation name?</li>
<li>Preferred display name?</li></ul></li></ul>
<hr>
<h2 id="${"badges-and-trophies"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#badges-and-trophies"}"><span class="${"icon icon-link"}"></span></a>Badges and Trophies</h2>
<ul><li>Trophies<ul><li>MVP: Eli<ul><li>5 points toward CPNT 265</li></ul></li></ul></li>
<li>Badges<ul><li>“Perfect” attendance<ul><li>Darryl</li>
<li>Rustu</li>
<li>Ashley</li></ul></li>
<li>Code Warrior<ul><li>Jesse</li>
<li>Ashley</li>
<li>May</li>
<li>Myka</li></ul></li></ul></li></ul>
<hr>
<h2 id="${"review-final-week-checklist"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#review-final-week-checklist"}"><span class="${"icon icon-link"}"></span></a>Review: Final week checklist</h2>
<p><a href="${"https://sait-wbdv.github.io/slides/w23/cpnt-265/finals-checklist.html"}" rel="${"nofollow"}"><img src="${"/images/slides/final-week-checklist.png"}" alt="${"Slides - Final week checklist"}"></a></p>
<hr>
<h2 id="${"10am---stage-work-achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#10am---stage-work-achievements"}"><span class="${"icon icon-link"}"></span></a>10am - Stage Work Achievements</h2>
<ol><li>Myka - Shopify</li>
<li>TBA</li>
<li>TBA</li></ol>
<hr>
<h2 id="${"afternoon"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#afternoon"}"><span class="${"icon icon-link"}"></span></a>Afternoon</h2>
<ul><li>Lab time</li>
<li>Proof of work sessions</li></ul>
<hr>`;
});

export { _09_day_9 as default, metadata };
