import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/dsgn-270/09-day-9.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "To Be Announced",
	"excerpt": null,
	"status": "draft"
};

const _09_day_9 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _09_day_9 as default, metadata };
