import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/10-day-10.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Review and Lab Day",
	"excerpt": "Last day of HTML and CSS! Let's get ready for the Final Project.",
	"status": "draft"
};

const _10_day_10 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"houskeeping"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#houskeeping"}"><span class="${"icon icon-link"}"></span></a>Houskeeping</h2>
<ul><li>New Achievements:<ul><li>Plugin Away: <ul><li><a href="${"https://bulma.io/documentation/overview/start/"}" rel="${"nofollow"}">Bulma CSS Framework</a></li>
<li><a href="${"https://revealjs.com/"}" rel="${"nofollow"}">RevealJS HTML Presentation Framework</a></li></ul></li>
<li>Build Session: <a href="${"https://www.youtube.com/watch?v=flItyHiDm7E"}" rel="${"nofollow"}">JavaScript - How to Create a Responsive Hamburger Menu with HTML, CSS, &amp; JavaScript</a></li></ul></li></ul>
<hr>
<h2 id="${"1-final-project-overview"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-final-project-overview"}"><span class="${"icon icon-link"}"></span></a>1. Final Project Overview</h2>
<ul><li><a href="${"/courses/cpnt-260/assessments/final-project"}">Final Project Details</a></li>
<li>Team assignments: will be sent as a DM in Slack over the first break;</li></ul>
<hr>
<h2 id="${"2-first-team-meeting"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-first-team-meeting"}"><span class="${"icon icon-link"}"></span></a>2. First team meeting</h2>
<ol><li>Choose a project topic;<ul><li>this should be different (but can be related to) past assignment submission topics;</li></ul></li>
<li>Decide on a team name;<ul><li>Make it safe for work, please.</li></ul></li>
<li>Are there any non-trivial items you’d like added to Above and Beyond?<ul><li>This does not have to be code related but should add value to the project.</li></ul></li></ol>
<hr>
<h2 id="${"3-finalizing-fp-requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-finalizing-fp-requirements"}"><span class="${"icon icon-link"}"></span></a>3. Finalizing FP Requirements</h2>
<ul><li>Slack DM to Tony:<ul><li>Team names</li>
<li>Team lead/liaison</li>
<li>Friday: GitHub Project link</li></ul></li>
<li>Any requests for Above and Beyond?</li>
<li>Questions and clarifications.</li></ul>
<hr>
<h2 id="${"lab-time"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#lab-time"}"><span class="${"icon icon-link"}"></span></a>Lab Time</h2>
<h3 id="${"final-project"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#final-project"}"><span class="${"icon icon-link"}"></span></a>Final Project</h3>
<ol><li>Choose an owner for your project repo;</li>
<li>Add your team members as Collaborators;</li>
<li>Create a Project Board for your Group Charter;</li></ol>
<h3 id="${"the-other-things"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#the-other-things"}"><span class="${"icon icon-link"}"></span></a>The other things</h3>
<ul><li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/assignment-4"}" rel="${"nofollow"}">CPNT 260 Assignment 4</a></li>
<li><a href="${"https://sait-wbdv-f22.netlify.app/courses/cpnt-260/assessments/achievements-2"}" rel="${"nofollow"}">Achievements Round 2</a></li></ul>`;
});

export { _10_day_10 as default, metadata };
