import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-265/11-day-11.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Final Project Presentations",
	"excerpt": null,
	"status": "draft"
};

const _11_day_11 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"presentations---round-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#presentations---round-1"}"><span class="${"icon icon-link"}"></span></a>Presentations - Round 1</h2>
<ol><li></li>
<li></li>
<li></li>
<li></li>
<li></li></ol>
<h2 id="${"presentations---round-2"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#presentations---round-2"}"><span class="${"icon icon-link"}"></span></a>Presentations - Round 2</h2>
<ol><li></li>
<li></li>
<li></li>
<li></li>
<li></li></ol>`;
});

export { _11_day_11 as default, metadata };
