import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/16-day-16.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Hackathon Day",
	"excerpt": null,
	"status": "draft"
};

const _16_day_16 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"morning-check-in"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#morning-check-in"}"><span class="${"icon icon-link"}"></span></a>Morning Check in</h2>
<ul><li>How are we doing?</li>
<li>What can we change/adjust to help people catch up?</li></ul>
<h2 id="${"objectives"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#objectives"}"><span class="${"icon icon-link"}"></span></a>Objective(s)</h2>
<ul><li>Get caught up on 262 Content</li>
<li>Practice and Debug</li>
<li>Finish content for 262 Assignment 3</li>
<li>Explore ideas for your final project</li>
<li>Get some 262 bonus marks (5)<ul><li>262-a3 content not for bonus marks</li></ul></li>
<li>(optional) mini presentations/walk-throughs of work done today</li></ul>
<h3 id="${"hackathon-ideas"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#hackathon-ideas"}"><span class="${"icon icon-link"}"></span></a>Hackathon Ideas</h3>
<ul><li>Make 2 pages that reuse the same components<ul><li>ie: Home and About pages</li></ul></li>
<li>Create a navbar with a mobile toggle</li>
<li>Build a gallery page</li>
<li>Sandbox Practice</li></ul>
<h2 id="${"mini-presentations"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#mini-presentations"}"><span class="${"icon icon-link"}"></span></a>Mini Presentations</h2>
<ul><li>Show what you built/tried to build</li>
<li>Discuss aha moments</li>
<li>Discuss any bugs or problems that you ran into</li>
<li>Get feedback</li></ul>`;
});

export { _16_day_16 as default, metadata };
