import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/17-day-17.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Review Day",
	"excerpt": null,
	"status": "draft"
};

const _17_day_17 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { _17_day_17 as default, metadata };
