import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/19-day-19.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Nuxt Config and Site Deployment",
	"excerpt": null,
	"status": "draft"
};

const _19_day_19 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p>Assignment 4 - Page Buildng in Vue/Nuxt</p>
<ul><li>15% of your 262 Mark</li>
<li>Build Two pages using components<ul><li>ui, layout, utility (min 5)</li></ul></li>
<li>Due: Tuesday November 29th</li></ul>
<h2 id="${"card-component-optimization"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#card-component-optimization"}"><span class="${"icon icon-link"}"></span></a>Card Component Optimization</h2>
<ul><li>Use objects for grouped props (colors, info, link)</li>
<li>Cannot use template literals for tailwind classes (would work for vanilla css)</li></ul>
<h3 id="${"migrate-and-optimize-list-component"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#migrate-and-optimize-list-component"}"><span class="${"icon icon-link"}"></span></a>Migrate and Optimize List Component</h3>
<ul><li>Copy the list component from our vue activity into your nuxt repo</li>
<li>Set up support for an ordered list and definition list using Boolean values</li>
<li>Optimize list item and remove v-for in AppList</li></ul>
<h2 id="${"metadata-and-configuration"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#metadata-and-configuration"}"><span class="${"icon icon-link"}"></span></a>Metadata and Configuration</h2>
<ul><li><a href="${"https://nuxt.com/docs/api/configuration/nuxt-config/#head"}" rel="${"nofollow"}"><code>nuxt.config.ts</code></a>: global head content, import fonts, viewport etc</li>
<li><a href="${"https://nuxt.com/docs/getting-started/seo-meta"}" rel="${"nofollow"}"><code>useHead()</code></a> can be used for page level metadata</li>
<li><a href="${"https://tailwindcss.com/docs/configuration"}" rel="${"nofollow"}">Add fonts to tailwind</a><ul><li>additions to your tailwind config will overwrite the default</li></ul></li></ul>
<h3 id="${"important-modules"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#important-modules"}"><span class="${"icon icon-link"}"></span></a>Important Modules</h3>
<ul><li><a href="${"https://nuxt.com/modules/image"}" rel="${"nofollow"}">Nuxt Image</a><ul><li>Automatically optimize images</li></ul></li>
<li><a href="${"https://nuxt.com/modules/icon"}" rel="${"nofollow"}">Nuxt Icon</a><ul><li>don’t be limited by FontAwesome!</li></ul></li></ul>
<h4 id="${"nuxt-img-usage"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#nuxt-img-usage"}"><span class="${"icon icon-link"}"></span></a>Nuxt Img Usage</h4>
<ul><li>Add Images to the public or assets directories<ul><li>nuxt-img will autoload from public</li></ul></li>
<li>Load the images onto your About Page using the Nuxt Image Module (everything except for src is optional)<ul><li><code>&lt;NuxtImg src=&quot;path-to-img/&quot; format=&quot;webp&quot; height=&quot;100&quot; width=&quot;200&quot; quality=&quot;80&quot; /&gt;</code></li></ul></li>
<li><a href="${"https://v1.image.nuxtjs.org/components/nuxt-img"}" rel="${"nofollow"}">Nuxt Image Syntax Notes</a></li>
<li><a href="${"https://nuxt.com/docs/getting-started/assets#assets"}" rel="${"nofollow"}">Assets directory documentation</a> (covers assets and publi directories)</li></ul>
<h4 id="${"nuxt-icon-usage"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#nuxt-icon-usage"}"><span class="${"icon icon-link"}"></span></a>Nuxt Icon Usage</h4>
<ul><li><a href="${"https://marketplace.visualstudio.com/items?itemName=antfu.iconify"}" rel="${"nofollow"}">vscode plugin</a> for syntax highlighting</li>
<li><a href="${"https://nuxt.com/modules/icon"}" rel="${"nofollow"}">module instructions</a></li>
<li><a href="${"https://icones.js.org/"}" rel="${"nofollow"}">browse available icons</a></li>
<li>syntax:<ul><li><code>&lt;Icon name=fa6-solid:bars&quot; /&gt;</code></li></ul></li>
<li>set icon default size in <code>app.config.js</code> (see docs)</li></ul>
<h2 id="${"deployment-to-netlify"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#deployment-to-netlify"}"><span class="${"icon icon-link"}"></span></a>Deployment to Netlify</h2>
<ul><li><a href="${"https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/"}" rel="${"nofollow"}">Set Up, Authorize, and Publish a Website</a></li>
<li><a href="${"https://nuxt.com/docs/getting-started/deployment#supported-hosting-providers"}" rel="${"nofollow"}">Nuxt 3 Deployment</a></li></ul>`;
});

export { _19_day_19 as default, metadata };
