import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/dsgn-270/achievements-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "UI Design Achievements",
	"type": "assignment",
	"points": 20
};

const Achievements_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<ul><li>For all achievements, submit a viewable link to brightspace.</li>
<li>Each submission will be marked out of 5</li></ul>
<h2 id="${"hi-resolution-card-design"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#hi-resolution-card-design"}"><span class="${"icon icon-link"}"></span></a>Hi Resolution Card Design</h2>
<ul><li>Emulate a card from a website that you like or from the specs of a design system</li>
<li>Create a card in figma</li>
<li>Use a custom color and typography set</li>
<li>Design on a grid</li>
<li>Display it in a 3 up desktop layout</li>
<li>Display a mobile version on a phone layout</li></ul>
<h2 id="${"blog-post-mockup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#blog-post-mockup"}"><span class="${"icon icon-link"}"></span></a>Blog Post Mockup</h2>
<ul><li>Create a mockup for a blog post</li>
<li>Hi resolution (blog text can be lorem ipsum)</li>
<li>Include at least 1 image</li>
<li>Content to include:<ul><li>Title section</li>
<li>Blog text</li>
<li>1 other section (comments, tags, sidenav…)</li></ul></li></ul>
<h2 id="${"hero-section-mockup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#hero-section-mockup"}"><span class="${"icon icon-link"}"></span></a>Hero Section Mockup</h2>
<ul><li>Create a visually appealing hero section</li>
<li>Feature 1 to 2 buttons</li>
<li>A large background image or well placed foreground image</li>
<li>Headline</li>
<li>Subheadline</li></ul>
<h2 id="${"mobile-first-design"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#mobile-first-design"}"><span class="${"icon icon-link"}"></span></a>Mobile First Design</h2>
<ul><li>Create any of the above 3 design elements</li>
<li>Design it in high resolution for mobile first</li>
<li>Create a minimal wireframe to show how it would translate to desktop</li></ul>
<h2 id="${"set-up-a-design-system"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#set-up-a-design-system"}"><span class="${"icon icon-link"}"></span></a>Set up a Design System</h2>
<ul><li>Use one of your moodboards to create a design system</li>
<li>Include:<ul><li>Colors (primary, secondary, black, white)</li>
<li>Fonts (heading, text, display)</li>
<li>Desktop and Mobile Default Frames (with columns configured)</li>
<li>3 reusable UI component elements</li></ul></li></ul>
<h2 id="${"button-with-a-hover-state"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#button-with-a-hover-state"}"><span class="${"icon icon-link"}"></span></a>Button with a Hover State</h2>
<ul><li>Design a button</li>
<li>Set up a functional hover state</li></ul>
<h2 id="${"card-hover-call-to-action"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#card-hover-call-to-action"}"><span class="${"icon icon-link"}"></span></a>Card Hover Call to Action</h2>
<ul><li>You can duplicate either your in class or other achievements for this (but must duplicate and rename)</li>
<li>Create a hover state for either a CTA button or make the whole card clickable</li>
<li>Make the CTA take the user to a different frame<ul><li>Frame should have minimal content and a functional back button to get back to the card</li></ul></li></ul>
<h2 id="${"navigation-prototype"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#navigation-prototype"}"><span class="${"icon icon-link"}"></span></a>Navigation Prototype</h2>
<ul><li>Create a navigation bar design<ul><li>Full marks for it being positioned in relation to a header or other section of content</li></ul></li>
<li>Do one of the following:<ul><li>Mobile navigation with slide out or drop down click on hamburger</li>
<li>Desktop navigation with drop down menus</li>
<li>Desktop hero navigation</li></ul></li></ul>`;
});

export { Achievements_1 as default, metadata };
