import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-200/achievements.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Achievements - Content",
	"type": "achievements",
	"points": 40
};

const Achievements = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p>The content achievements represent the content responsibilities in a project. Normally this would be a client task but, since we have no real clients, you’ll be responsible for creating content for your CMS.</p>
<h2 id="${"content-topic-and-quality"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#content-topic-and-quality"}"><span class="${"icon icon-link"}"></span></a>Content Topic and Quality</h2>
<ul><li>All content must be either created by you or be openly-sourced;</li>
<li>Content must fit with your chosen client profile.</li>
<li>Ask your instructor if you’d like to change the minimums/maximums of a given Achievement.</li></ul>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission instructions</h2>
<ul><li>Add the relevant content to your Strapi project;</li>
<li>In the README of your Strapi project, include:<ul><li>Course title</li>
<li>Assessment title</li>
<li>Author</li>
<li>Attributions</li></ul></li>
<li>Deploy your project;</li>
<li>As a comment in your submission, include an admin-level login for your instructor to mark your achievements:<ul><li>Name: Tony Grimes</li>
<li>Email: <a href="${"mailto:tony.grimes@sait.ca"}">tony.grimes@sait.ca</a></li>
<li>Password: P4ssword</li></ul></li></ul>
<hr>
<h2 id="${"1-media-images"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-media-images"}"><span class="${"icon icon-link"}"></span></a>1. Media: Images</h2>
<ul><li>Weight: 1 point per image</li>
<li>Max: 10 images</li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Collect image assets that relate to your project;</li>
<li>Upload to the Media library in your Strapi installation, either directly or using the Content Builder.</li></ol>
<p><strong>Requirements</strong></p>
<ul><li>Images must be open-source or your own;</li>
<li>Images must be used in your Content. For example:<ul><li>Item image/thumbnail</li>
<li>Blog post/article illustration</li>
<li>Single page illustration</li></ul></li></ul>
<hr>
<h2 id="${"2-collection-items"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-collection-items"}"><span class="${"icon icon-link"}"></span></a>2. Collection: Items</h2>
<ul><li>Weight: 1 point per item</li>
<li>Minimum: 5 items</li>
<li>Maximum: 15 items</li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Create a Collection-type for your item in the Content-Type Builder (as part of Assignment 2);</li>
<li>Enter the desired number of items as content in the Content Builder.</li></ol>
<p><strong>Item examples:</strong></p>
<ul><li>Restaurant menu items</li>
<li>Shopping cart items</li>
<li>Calendar events</li></ul>
<p><strong>Requirements:</strong></p>
<ul><li>Multiple collections can be used;</li>
<li>Items must incorporate least 3 non-image fields/components;</li>
<li>Using an image as a field counts as a Media achievement.</li></ul>
<hr>
<h2 id="${"3-collection-blog-postsarticles"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-collection-blog-postsarticles"}"><span class="${"icon icon-link"}"></span></a>3. Collection: Blog posts/articles</h2>
<ul><li>Weight: 3 points per item</li>
<li>Max: 5 posts</li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Create a Collection-type for your posts in the Content-Type Builder (as part of Assignment 2);</li>
<li>Enter the desired number of posts as content in the Content Builder.</li></ol>
<p><strong>Examples</strong></p>
<ul><li>Personal blog posts</li>
<li>News articles</li>
<li>How-to articles</li>
<li>Movie reviews</li></ul>
<p><strong>Requirements</strong></p>
<ul><li>Posts must include at least 350 words;</li>
<li>Posts should have high visual hierarchy using headings, lists, imagery (optional), etc;</li>
<li>Posts must incorporate rich text field;</li>
<li>Post must make sense and fit with your chosen client topic.</li></ul>
<hr>
<h2 id="${"4-single-site-pages"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-single-site-pages"}"><span class="${"icon icon-link"}"></span></a>4. Single: Site Pages</h2>
<ul><li>Weight: 3 points per page</li>
<li>Minimum: 2 pages</li>
<li>Maximum: 4 pages</li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Create a Single-type for your page in the Content-Type Builder (as part of Assignment 2);</li>
<li>Enter the content for each page in the Content Builder.</li></ol>
<p><strong>Examples</strong></p>
<ul><li>Home page</li>
<li>About page</li>
<li>Contact page</li>
<li>Products and services page</li></ul>
<p><strong>Requirements</strong></p>
<ul><li>Pages must include at least one image (as part of the Media achievement);</li>
<li>Pages must incorporate rich text field;</li>
<li>Each Page must be at least 200 words;</li>
<li>Pages should have high visual hierarchy using headings, lists, imagery (optional), etc.</li></ul>`;
});

export { Achievements as default, metadata };
