import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-262/achievements-3.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Achievements Round 3",
	"type": "achievements",
	"points": 10
};

const Achievements_3 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<p>Pick 2 of the following achievements to complete. They are worth 5 points each. Submit a separate repo or add notes to the relevant files for each achievement in your submission.</p>
<h3 id="${"components-and-class-bindings"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#components-and-class-bindings"}"><span class="${"icon icon-link"}"></span></a>Components and Class Bindings</h3>
<ul><li>Create 3 components</li>
<li>Use class bindings for colors and text</li>
<li>bind data and set up default values</li>
<li>Apply them to a page</li></ul>
<h3 id="${"nuxt-modules"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#nuxt-modules"}"><span class="${"icon icon-link"}"></span></a>Nuxt Modules</h3>
<ul><li><a href="${"https://nuxt.com/modules"}" rel="${"nofollow"}">Nuxt Modules</a></li>
<li>Pick a nuxt module that is not (google-fonts, tailwindcss, strapi, or pinia) and add it to a project</li>
<li>Set up the module and demonstrate what it does</li>
<li>Discuss the benefits of this module briefly in your README</li>
<li>Note relevant files and lines of code</li></ul>
<h3 id="${"vue-directives-deep-dive"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#vue-directives-deep-dive"}"><span class="${"icon icon-link"}"></span></a>Vue Directives Deep Dive</h3>
<ul><li>Use some of the advanced features offered by vue directives in either a vue 3 or nuxt 3 project</li>
<li><a href="${"https://vuejs.org/api/built-in-directives.html"}" rel="${"nofollow"}">Vue Directive List</a></li>
<li>2 examples required</li>
<li>Discuss what is useful about each example that you have created in your README</li></ul>
<h3 id="${"nuxt-3-server-side-routing"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#nuxt-3-server-side-routing"}"><span class="${"icon icon-link"}"></span></a>Nuxt 3 Server Side Routing</h3>
<ul><li>Create a server route that passes data to a page</li>
<li><a href="${"https://nuxt.com/docs/guide/directory-structure/server#server-directory"}" rel="${"nofollow"}">Documentation</a></li>
<li><a href="${"https://www.youtube.com/watch?v=usxvXJ_XeiU"}" rel="${"nofollow"}">Tutorial</a></li>
<li>Discuss what you might use this for briefly in your README</li></ul>
<h3 id="${"pinia-store"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#pinia-store"}"><span class="${"icon icon-link"}"></span></a>Pinia Store</h3>
<ul><li>Set up a pinia store in Vue 3 or Nuxt 3</li>
<li>Use state management for a variable</li>
<li><a href="${"https://www.youtube.com/watch?v=Ok6vO98RV_Q"}" rel="${"nofollow"}">Tutorial</a></li>
<li>Discuss what you might use this for briefly in your README</li></ul>`;
});

export { Achievements_3 as default, metadata };
