import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-260/achievements-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Achievements Round 2",
	"type": "achievements",
	"points": 15
};

const Achievements_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>Same as <a href="${"achievements-1"}">Round 1</a>, except:</p>
<ul><li>Submissions for Achievements Round 2 will close Tuesday, October 4th @ 11:59pm;</li>
<li>Achievements from Round 1 are <strong>not eligible</strong> for this Round.</li></ul>
<hr>
<h2 id="${"achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#achievements"}"><span class="${"icon icon-link"}"></span></a>Achievements</h2>
<p>Submission Instructions:</p>
<ol><li>In Brightspace: submit a ZIP of relevant files to <em>Round 2</em>; </li>
<li>As a comment: share links to make it easy for the instructor to quickly evaluate your work:<ul><li>GH repos, Pages, Projects (Beta), etc.</li>
<li>Codepens, Figma, FigJam, etc.</li></ul></li>
<li>Double check the Achievement for specific instructions.</li>
<li>Submit Achievements as you finish them; your Instructor will try to keep up!</li></ol>
<hr>
<h3 id="${"tutorial-build-session"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tutorial-build-session"}"><span class="${"icon icon-link"}"></span></a>Tutorial build session</h3>
<p>Watch/read one of the below tutorials and recreate the [thingy] with your own content.</p>
<ul><li><a href="${"https://www.youtube.com/watch?v=tFKrK4eAiUQ"}" rel="${"nofollow"}">Responsive image gallery with CSS Grid</a> by Jen Simmons<ul><li>You may use Lorem Picsum for this tutorial;</li></ul></li>
<li>Responsive hamburger menu - follow ONE of the following tutorials<ul><li><a href="${"http://www.ashleysheridan.co.uk/blog/Making+an+Accessible+Hamburger+Menu"}" rel="${"nofollow"}">Making an Accessible Hamburger Menu</a> by Ashley Sheridan<ul><li>You can stop when she starts adding Javascript</li></ul></li>
<li><a href="${"https://www.youtube.com/watch?v=At4B7A4GOPg"}" rel="${"nofollow"}">Responsive Navbar Tutorial</a> by Web Dev Simplified</li>
<li><a href="${"https://www.youtube.com/watch?v=flItyHiDm7E"}" rel="${"nofollow"}">How to Create a Responsive Hamburger Menu with HTML, CSS, &amp; JavaScript</a> by Codefoxx</li></ul></li>
<li><strong>[more here]</strong></li></ul>
<p><strong>Submissions needed</strong>
Got a good tutorial you’d like to submit for marks? Ask your Instructor about adding it onto the list.</p>
<ul><li><strong>Bonus: 5 points</strong> for anyone who finds and adequate tutorial to add to the list.</li></ul>
<p><strong>Bonus</strong></p>
<ul><li>You can do two Build Session in Round 1 for a total of 10 points!</li></ul>
<hr>
<h2 id="${"plugin-away"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#plugin-away"}"><span class="${"icon icon-link"}"></span></a>Plugin Away</h2>
<p>3rd-party plugin/library implementation. Show that you’ve installed and implemented a 3rd party plugin or service from the following list:</p>
<ul><li><strong>Contact form</strong> using <a href="${"https://formspree.io/"}" rel="${"nofollow"}">formspree.io</a> or similar<ul><li>Add a working contact form on your website that emails you submissions;</li></ul></li>
<li><a href="${"https://bulma.io/documentation/overview/start/"}" rel="${"nofollow"}">Bulma CSS Framework</a></li>
<li><a href="${"https://revealjs.com/"}" rel="${"nofollow"}">RevealJS HTML Presentation Framework</a></li>
<li><strong>[more here]</strong></li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Create your project in a <code>index.html</code> file with a <code>README.md</code>, including;<ul><li>a title for your demo as a level 1 heading;</li>
<li>instructions on how to use the demo, if needed;</li>
<li>all Attributions used to create <code>index.html</code> including sample code, tutorials, etc.</li></ul></li>
<li>Name your repo after the technology you used;</li></ol>
<p><strong>Submissions needed</strong>
Submissions needed Got a good tutorial you’d like to submit for marks? Ask your Instructor about adding it onto the list.</p>
<ul><li><strong>Bonus: 5 points</strong> for anyone who finds and adequate plugin to add to the list.</li></ul>
<p><strong>Bonus</strong></p>
<ul><li>You can do two Above and Beyonds in Round 1 for a total of 10 points!</li></ul>
<hr>
<h3 id="${"project-board"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#project-board"}"><span class="${"icon icon-link"}"></span></a>Project Board</h3>
<p>Create a 5-card GH Project (Beta) Board containing action items that you need to complete for one of your upcoming assignments or achievements.</p>
<p><strong>Requirements</strong>
Submit a direct link to a Project (with screencap), with:</p>
<ul><li>Columns: Backlog (or To Do), In Progress (or Doing), Done;</li>
<li>Card descriptions: each card should have a Definition of Done (DoD), such as:<ul><li>a sentence that explicitly states when the card can be moved to the Done column, and/or.</li>
<li>a checklist (<code>- [ ]</code> in markdown) of todos;</li></ul></li></ul>
<p><strong>Bonus</strong></p>
<ul><li>Double points if your DoD is a written as a UX User Story.</li></ul>
<hr>
<h3 id="${"show-and-tell"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#show-and-tell"}"><span class="${"icon icon-link"}"></span></a>Show and Tell</h3>
<p>Do a 5-minute talk on a topic related to the course. It could be:</p>
<ul><li>A demo of something you built;</li>
<li>A tutorial on how to use a tool;</li>
<li>An awesome [thing here] you found online.</li>
<li>etc, etc.</li></ul>
<p><strong>Restrictions</strong></p>
<ul><li>The length of your talk must be 5 minutes +/- 2 minutes;</li></ul>
<p><strong>Instructions</strong></p>
<ol><li>Book a time slot with your Instructor at least a day in advance;</li>
<li>Build, prepare, etc</li>
<li>Show and tell when the time comes!</li></ol>
<p><strong>Bonus</strong>
Double points for your first show and tell!</p>
<hr>
<h3 id="${"devops"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#devops"}"><span class="${"icon icon-link"}"></span></a>Devops</h3>
<p>Complete one of the following tasks:</p>
<ul><li><strong>Custom Domain on HTTPS: <em>5 points</em></strong><ul><li>Deploy a web site or app with a custom domain<ul><li>Sign up for the <a href="${"https://education.github.com/pack"}" rel="${"nofollow"}">GitHub Student Developer Pack</a> to get a free domain with NameCheap</li></ul></li>
<li>Must be deployed to a live server such as GH Pages, Heroku or similar</li>
<li>Security certificate must be used to deploy domain on HTTPS</li></ul></li></ul>`;
});

export { Achievements_2 as default, metadata };
