import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-201/achievements-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Achievements Round 1 Git",
	"type": "achievements",
	"points": 10
};

const Achievements_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>Achievements will be marked differently than other Assignments in Brightspace:</p>
<ul><li><strong>You will be graded for 2 5-point mini-assignments</strong> (Achievements) that will be due on Friday October 14</li>
<li>In Brightspace, you will receive points for Achievements Round 1 as you submit individual Achievements;</li>
<li>You can choose from any of the following Achievements for this Round;</li>
<li>You will be graded according to the Requirements of the Achievement you’ve submitted;</li></ul>
<hr>
<h2 id="${"achievements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#achievements"}"><span class="${"icon icon-link"}"></span></a>Achievements</h2>
<hr>
<h3 id="${"resolve-multiple-merge-conflicts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#resolve-multiple-merge-conflicts"}"><span class="${"icon icon-link"}"></span></a>Resolve Multiple Merge Conflicts</h3>
<p>Practice resolving merge conflicts. These can be from actual instances in projects or you can create them on your own in a dedicated repo.</p>
<h4 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h4>
<p>To receive marks you must:</p>
<ol><li>Pick at least 1 repo where you resolved merge conflicts (starting on october 6th and it cannot be your CPNT-201-A3 repo)</li>
<li>Resolve 5 merge conflicts following the instructions from class and assignment 3.</li>
<li>In Brightspace submit links to all the merge conflicts commits along with a brief description of the commit.</li>
<li>Submit a link to your repo</li></ol>
<h3 id="${"merge-work-from-a-development-branch-into-main"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#merge-work-from-a-development-branch-into-main"}"><span class="${"icon icon-link"}"></span></a>Merge work from a “development” branch into main</h3>
<p>It is often good practice to open pull requests to move code to a main branch. Practice opening pull requests to move code into your main branch. Make use of the <strong>squash and merge</strong> option where appropriate.</p>
<ul><li>This must include 5 commits in 1 or more pull requests</li></ul>
<h4 id="${"instructions-1"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions-1"}"><span class="${"icon icon-link"}"></span></a>Instructions</h4>
<ol><li>Open up a new branch with <code>git checkout -b branch-name</code> and make changes to your code in it</li>
<li>Push the changes to the remote branch</li>
<li>Open a pull request and merge the code into your main branch</li>
<li>In your brightspace submission, add a link to your pull request</li></ol>
<h3 id="${"use-git-revert-git-reset-and-git-rm"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#use-git-revert-git-reset-and-git-rm"}"><span class="${"icon icon-link"}"></span></a>Use git revert, git reset, and git rm</h3>
<ul><li><a href="${"https://www.atlassian.com/git/tutorials/undoing-changes/git-revert"}" rel="${"nofollow"}">Tutorials</a></li>
<li>Remove a file with git rm</li>
<li>Use git revert to undo changes</li>
<li>Use git reset to undo changes</li>
<li>Add a list with the commit history of the relevant changes<ul><li>Bonus point if the changes are tracked in a Pull Request</li></ul></li></ul>
<h3 id="${"do-any-of-the-above-achievements-with-a-partner"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#do-any-of-the-above-achievements-with-a-partner"}"><span class="${"icon icon-link"}"></span></a>Do any of the above achievements with a partner</h3>
<ul><li>Both of you will submit relevant information just like cpnt-201-a3.</li>
<li><strong>You cannot do the same achievement twice</strong></li></ul>`;
});

export { Achievements_1 as default, metadata };
