import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-200/assignment-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 1 - Client site profile",
	"type": "assignment",
	"points": 30
};

const Assignment_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p>In this assignment, you will choose a company website to critique, analyze and adapt for your own Strapi project.</p>
<p>The company should be similar to the hypothetical client you will build a CMS for in the other assessments of this course. For example, the company could be:</p>
<ul><li>A bar, pub or restaurant;</li>
<li>An online store;</li>
<li>Service-focused (i.e. web developer, law office, hair-stylist, etc).</li></ul>
<hr>
<h2 id="${"general-requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#general-requirements"}"><span class="${"icon icon-link"}"></span></a>General Requirements</h2>
<p>Your chosen website should be of appropriate complexity to study the content types needed in this course (see <a href="${"achievements"}">Content Achievements</a> for examples).</p>
<ul><li>There should be an example of:<ul><li>A Collection-type;</li>
<li>Multiple single pages</li>
<li>Images</li></ul></li>
<li>The company industry should be related to the topic of your Strapi project;</li>
<li>Format your documents in a professional manner. You should feel comfortable submitting this to a real client.</li></ul>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Write your summary, critique and Content Types in a format of your choice. For example:<ul><li>As a markdown file,</li>
<li>Google Doc</li>
<li>PDF</li></ul></li>
<li>Link to support assets, such as Figma/FigJam share links from your main document.</li></ol>
<hr>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>Each of the following requirements will a total of 20 points.</p>
<h3 id="${"1-client-summary-3-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-client-summary-3-points"}"><span class="${"icon icon-link"}"></span></a>1. Client Summary: 3 points</h3>
<p>Summarize the company you’ve chosen:</p>
<ul><li>Company name</li>
<li>Company industry</li>
<li>Website URL</li>
<li>Target audience/customer</li>
<li>What is their value proposition?<ul><li>What problem do they solve?</li>
<li>What do they sell, if anything?</li></ul></li></ul>
<p>The summary should be 150-200 words and have high visual hierarchy.</p>
<h3 id="${"2-sitemap-7-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-sitemap-7-points"}"><span class="${"icon icon-link"}"></span></a>2. Sitemap: 7 points</h3>
<p>Using Figma, FigJam or similar software, reverse engineer the sitemap with a top level view of how pages are connected to one another.</p>
<p>For the purposes of this assignment, limit your Sitemap to a 3-level depth</p>
<p>Include labels/colours for:</p>
<ul><li>Single pages (i.e. About, Contact, etc)</li>
<li>List entry pages (i.e. Gallery index page)</li>
<li>Item Collection (i.e. one “page” that represents multiple items in a collection)</li></ul>
<h3 id="${"3-content-type-definitions-7-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-content-type-definitions-7-points"}"><span class="${"icon icon-link"}"></span></a>3. Content type definitions: 7 points</h3>
<p>Analyze the content used on the website, focusing on the types of content it incorporates.</p>
<ul><li>Include screencaps of each type of website content and include them in your document;</li>
<li>Try to include examples of at least 5 different field types in total;</li>
<li>List the names of each Single Type<ul><li>Are there any Collection-types included on Single pages?</li></ul></li>
<li>Define at least 3 Collection Types (you do not have to go more than 1-level deep):<ul><li>What fields are used?</li>
<li>For each field, what type will it be?</li>
<li>Are any Content-types connected with a Relation field? Is it one-to-many, one-to-many or many-to-many?</li>
<li>Are any Components needed?<ul><li>What fields would be included in the component?</li></ul></li></ul></li></ul>
<h3 id="${"4-adapt-and-critique-3-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-adapt-and-critique-3-points"}"><span class="${"icon icon-link"}"></span></a>4. Adapt and critique: 3 points</h3>
<p>This section should be 150-200 words and have high visual hierarchy.</p>
<ul><li>Is this site well structured?</li>
<li>What could be improved?</li>
<li>Why would someone choose this company over their competition?</li>
<li>How will this website relate to your Strapi project?</li></ul>
<hr>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission instructions</h2>
<ul><li>Push this assignment to a GitHub repo named <code>cpnt200-a1</code> and enable GitHub Pages, if applicable;</li>
<li>ZIP all files related to your assignment and submit them to Brightspace;</li></ul>`;
});

export { Assignment_1 as default, metadata };
