import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-201/assignment-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 4 - NPM Tailwind Assignment",
	"type": "assignment",
	"points": 20
};

const Assignment_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<p>Use tailwindcss to style a web page. You can use the code from a previous assignment or write new code, either is acceptable. Practice using this utility class framework to either recreate the styles that you made in vanilla css or try building content from scratch.</p>
<p><strong>If you use code from a previous assignment, it must be copied into a new repo for this assignment</strong></p>
<p>For this assignment you <strong>cannot</strong> add tailwind via a cdn, you must set up a tailwind.config.js file.</p>
<h3 id="${"resources"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#resources"}"><span class="${"icon icon-link"}"></span></a>Resources</h3>
<ul><li><a href="${"https://tailwindcss.com/"}" rel="${"nofollow"}">Tailwind Documentation</a></li>
<li><a href="${"https://tailwindcss.com/docs/utility-first"}" rel="${"nofollow"}">Tailwind Utility First Fundamentals</a></li>
<li><a href="${"https://tailwindcss.com/docs/installation"}" rel="${"nofollow"}">Tailwind Setup Guide</a></li></ul>
<hr>
<h2 id="${"rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#rubric"}"><span class="${"icon icon-link"}"></span></a>Rubric</h2>
<p>Review the following categories on how this assignment will be graded.</p>
<h3 id="${"tailwind-configuration-5pts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#tailwind-configuration-5pts"}"><span class="${"icon icon-link"}"></span></a>Tailwind Configuration (5pts)</h3>
<ul><li><code>tailwind.config.js</code> file added to project</li>
<li>at least the following present in your tailwind config.<ul><li>colors</li>
<li>fonts</li>
<li>screen size breakpoints</li>
<li>spacing</li></ul></li>
<li><code>assets/css/main.css</code> contains tailwind imports</li></ul>
<h3 id="${"layout-styling-5pts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#layout-styling-5pts"}"><span class="${"icon icon-link"}"></span></a>Layout Styling (5pts)</h3>
<ul><li>Use of flexbox and/or grid effectively</li>
<li>Breakpoints are used on containing elements</li>
<li>Design is responsive and mobile first</li>
<li>margin, padding, width, and height are all used correctly to enhance your design</li></ul>
<h3 id="${"content-styling-5pts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#content-styling-5pts"}"><span class="${"icon icon-link"}"></span></a>Content Styling (5pts)</h3>
<ul><li>Use of breakpoints on fonts</li>
<li>foreground and background images are responsive</li>
<li>Use of tailwind default colors and/or your own custom colors</li>
<li>hover and active states are set up in a navigation bar and/or on buttons</li></ul>
<h3 id="${"general-requirements-5pts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#general-requirements-5pts"}"><span class="${"icon icon-link"}"></span></a>General Requirements (5pts)</h3>
<h4 id="${"setup"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#setup"}"><span class="${"icon icon-link"}"></span></a>Setup</h4>
<ul><li>Properly configured <code>package.json</code></li>
<li><code>node_modules/</code> added to <code>.gitignore</code></li>
<li>add a tailwind build command to the <code>scripts</code></li>
<li>Project is in a github repo named <code>cpnt201-a5</code></li></ul>
<h4 id="${"documentation"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#documentation"}"><span class="${"icon icon-link"}"></span></a>Documentation</h4>
<ul><li>Add a <code>README.md</code> file to the root of your project<ul><li>Readme contains:<ul><li>your name</li>
<li>course and assignment number</li>
<li>link to deployed github page</li>
<li>link to github repo</li>
<li>attributions to assets</li></ul></li></ul></li></ul>
<hr>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission Instructions</h2>
<ul><li>Submit the zipped folder to brightspace</li>
<li>Submit your live page and repo link in the text area of your submission.</li></ul>`;
});

export { Assignment_4 as default, metadata };
