import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/dsgn-270/assignment-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 1 - Moodboard",
	"type": "assignment",
	"points": 20
};

const Assignment_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p><strong>Due: Friday September 9th @ 11:59pm</strong></p>
<h2 id="${"scenario"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#scenario"}"><span class="${"icon icon-link"}"></span></a>Scenario</h2>
<p>You are starting out a new web development project and need to do some initial planning on what the look and feel of the site is going to be. Your client (client could be yourself) was very vague with their description of the design of their site and they did not give you any specific colors, fonts, or ui ideas. </p>
<p>Your job is to build a mood board based on a vague description (which you will define yourself). The mood board is used to gather examples and ideas organically. Add structure and group content with notes so that you or a hypothetical colleague could look at this later and understand it.</p>
<h3 id="${"content-to-gather-on-your-moodboard"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#content-to-gather-on-your-moodboard"}"><span class="${"icon icon-link"}"></span></a>Content To Gather on your Moodboard</h3>
<ul><li>Color pallettes (3-5 colors per pallete)</li>
<li>Typography (2-3 type faces per group)</li>
<li>Screenshots of user interface (ui) elements on at least 3 other websites<ul><li>headers and hero sections</li>
<li>navigation</li>
<li>lists</li>
<li>cards</li>
<li>call to action</li>
<li>1 section of content that shows good visual hierarchy</li></ul></li></ul>
<h3 id="${"resources"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#resources"}"><span class="${"icon icon-link"}"></span></a>Resources</h3>
<ul><li><a href="${"https://ui-patterns.com/"}" rel="${"nofollow"}">UI Patterns</a>: Examples and descriptions of specific ui elements</li>
<li><a href="${"https://material.io/"}" rel="${"nofollow"}">Material Design Manual</a>: Google’s Material Design Guide contains examples of UI elements that you can look for</li>
<li><a href="${"https://fonts.google.com/"}" rel="${"nofollow"}">Google Fonts</a></li></ul>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Create a mood board in Figjam and add the vague description to the top of the board in large text</li>
<li>Set up areas in your moodboard for grouping the required content</li>
<li>Add content to the moodboard</li></ol>
<ul><li>See the <strong>rubric</strong> for how many variations are needed of each content type</li>
<li>Images of websites should be clickable links so that you can navigate back to the original site when needed</li></ul>
<ol start="${"4"}"><li>Add brief sticky notes to your moodboard as makes sense to you, there needs to be a minimum of 1 note per content type (8 sticky notes minimum)</li>
<li>Export your mood board as a PDF</li></ol>
<ul><li>Make sure that it is easy to scan and look at in pdf format</li></ul>
<ol start="${"6"}"><li>Follow Submission guidelines below</li></ol>
<hr>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>This assignment will be marked out of 20 points.</p>
<h3 id="${"concept-and-notes-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#concept-and-notes-5-points"}"><span class="${"icon icon-link"}"></span></a>Concept and Notes: 5 points</h3>
<ul><li>Leading idea and description is present and visible on the board</li>
<li>Leading idea is <strong>not</strong> written with any tech jargon, it <strong>is</strong> thematic or conceptual</li>
<li>There are a minimum of 8 notes </li>
<li>Notes describe how the content relates/connects to the leading idea/description</li></ul>
<h3 id="${"visual-hierarchy-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#visual-hierarchy-5-points"}"><span class="${"icon icon-link"}"></span></a>Visual Hierarchy: 5 points</h3>
<ul><li>Your moodboard uses visual hierarchy to group content</li>
<li>Typography in screenshots reflects good visual hierarchy</li>
<li>Layout and design of UI elements in screenshots reflect good visual hierarchy</li>
<li>Critique visual hierarchy in screenshots</li></ul>
<h3 id="${"color-and-typography-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#color-and-typography-5-points"}"><span class="${"icon icon-link"}"></span></a>Color and Typography: 5 points</h3>
<ul><li>3 distinct color pallettes</li>
<li>2 different groups of type faces</li></ul>
<h3 id="${"screenshots-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#screenshots-5-points"}"><span class="${"icon icon-link"}"></span></a>Screenshots: 5 points</h3>
<ul><li>Screenshots depict distinct variations of the same UI element</li>
<li>Screenshots are specific and easy to understand</li>
<li>Screenshots link to original sources in moodboard</li></ul>
<hr>
<h2 id="${"submitting-your-assignment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submitting-your-assignment"}"><span class="${"icon icon-link"}"></span></a>Submitting Your Assignment</h2>
<p>In order to receive a grade, you must:</p>
<ol><li>Export your moodboard to a pdf</li>
<li>Get a viewable link to your moodboard and paste the link in the text box of your submission (do not send an email invite)</li>
<li>Zip the pdf of your moodboard</li>
<li>Submit the PDF along with the link to your active moodboard</li></ol>`;
});

export { Assignment_1 as default, metadata };
