import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/dsgn-270/assignment-4.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 4 - Website Mockup",
	"type": "assignment",
	"points": 20
};

const Assignment_4 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"scenario"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#scenario"}"><span class="${"icon icon-link"}"></span></a>Scenario</h2>
<p>You have been hired to build a website and need to do a quick mockup of the homepage to provide a proof of concept to your client. The mockup will allow you to get feedback and make design changes prior to getting into any code.</p>
<p>When building mockups, you can save a lot on design and development time by creating a design system, for this assignment, you will also be required to establish a basic design system (colors and fonts etc).</p>
<h3 id="${"requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#requirements"}"><span class="${"icon icon-link"}"></span></a>Requirements</h3>
<ul><li>Desktop mockup artboard should be either 1280px or 1920px wide</li>
<li>Desktop mockup uses a 12 column grid</li>
<li>Mobile wireframe artboard can use any of the phone presets in Figma</li>
<li>Mobile wireframe uses a 4 or 5 column grid</li></ul>
<h3 id="${"notes"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#notes"}"><span class="${"icon icon-link"}"></span></a>Notes</h3>
<ul><li>As the client is hypothetical, this is a great opportunity to challenge your own ideas about design and website layouts. Try using a color pallette that you wouldn’t normally choose or experiment with UI design patterns that you haven’t worked with before - Remember it’s much easier to be bold with design on a mockup than it is when you’re at the development stage.</li>
<li>For your design system, you can work off of one generated by a plugin, but it <strong>must</strong> be customized for your design, points will be deducted if stock colors and typefaces are submitted</li>
<li><em>you can be your own client</em></li></ul>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Create a design system for your mockup (use a separate page in your design file)</li></ol>
<ul><li>Colors</li>
<li>Fonts</li>
<li>One other field (ie: shadow)</li></ul>
<ol start="${"2"}"><li>Create a mockup that makes use of UI components</li></ol>
<ul><li>Components should be created in the same page as your design system</li>
<li>UI elements that <strong>must</strong> be componentized:<ul><li>elements that would be used on other web pages of the same site(header, footer, nav)</li>
<li>elements that are repeated on your landing page</li></ul></li></ul>
<ol start="${"3"}"><li>Create a low res mobile wireframe of your mockup</li></ol>
<ul><li>Demonstrate how the design would resize onto a mobile device</li>
<li>This is a minimal design, placeholder text for long form text and shapes for images, but use the correct titles to make it easy to follow</li></ul>
<ol start="${"4"}"><li>Export your files:</li></ol>
<ul><li>Pngs or pdfs for your design files (desktop and mobile)</li>
<li>Make sure the file naming conventions are appropriate for sending to a client (for the mockups) or using in a project (for the stylesheets)</li></ul>
<hr>
<h2 id="${"marking-criteria"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-criteria"}"><span class="${"icon icon-link"}"></span></a>Marking Criteria</h2>
<p>This assignment will be marked out of 20 points, which will be given for each of the following:</p>
<h3 id="${"mockup-design-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#mockup-design-5-points"}"><span class="${"icon icon-link"}"></span></a>Mockup Design: 5 points</h3>
<ul><li>Use of a grid to organize content</li>
<li>Effective visual hierarchy</li>
<li>Good use of contrast and spacing</li>
<li>5 sections of content (header, footer, nav, and two others)</li>
<li>Uses 1920 or 1280 px artboard</li></ul>
<h3 id="${"mockup-usability-5pts"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#mockup-usability-5pts"}"><span class="${"icon icon-link"}"></span></a>Mockup Usability: 5pts</h3>
<ul><li>Layout is easy to navigate and understand</li>
<li>UI elements are consistent</li>
<li>At least 1 call to action</li>
<li>UI elements reflect good design convention (or challenge convention effectively and without sacrificing usability)</li></ul>
<h3 id="${"design-system-and-components-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#design-system-and-components-5-points"}"><span class="${"icon icon-link"}"></span></a>Design System and Components: 5 points</h3>
<ul><li>All colors and fonts are <strong>applied</strong> using the design sytem</li>
<li>Design system and components are in a separate page in the same workspace</li>
<li>Components are applied correctly (so that if you change the primary component, the applied component will reflect those changes)</li>
<li>Exported stylesheet is usable</li>
<li>Reusable elements have been converted into components</li></ul>
<h3 id="${"mobile-wireframe-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#mobile-wireframe-5-points"}"><span class="${"icon icon-link"}"></span></a>Mobile Wireframe: 5 points</h3>
<ul><li>All content from the desktop mockup is accounted for</li>
<li>low resolution for content but approprately considers spacing and layout</li>
<li>Realistically relates to the desktop variant</li>
<li>Uses grid</li>
<li>Uses one of the phone default screen sizes</li></ul>
<hr>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission Instructions</h2>
<p>In order to receive a grade:</p>
<ol><li>Zip all your exported files into a single zip folder named <code>dsgn270-a4</code>, with:<ul><li>Exported pdfs or pngs of your design’s artboards saved in a folder called <code>mockups/</code></li>
<li>Exported design system files inside <code>styles/</code></li>
<li>A <code>README.md</code> file with:</li>
<li>The title of this assignment</li>
<li>Your name</li>
<li>A brief description of the client and what the website is for (2-5 sentences)</li>
<li>If you’ve chosen to challenge design conventions and principles, a paragraph that explains your concept and reasoning.</li></ul></li>
<li>Submit your Zip file to brightspace in the appropriate dropbox</li></ol>
<ul><li><strong>IMPORTANT</strong> In the text box of your submission:<ul><li>submit a viewable (read-only) link to your design (do not add your instructor to the project with an email from Figma)</li></ul></li></ul>`;
});

export { Assignment_4 as default, metadata };
