import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-201/assignment-1.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 1 - GitHub Project Board",
	"type": "assignment",
	"points": 20
};

const Assignment_1 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"details"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#details"}"><span class="${"icon icon-link"}"></span></a>Details</h2>
<p>In this assignment, you will track action items and to-dos in a GitHub Project (Beta) Board. It is comprised of all the tasks that were done in the Kanban Pizza Party activity. You will be able to make use of the skills practiced in this assignment in many of your future assignments. This is also an opportunity to work on your markdown syntax.</p>
<p>Practice organizing a project board based on a job that you are already familiar with. This entire assignment can be done within github, no code is necessary.</p>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Create a project in your account, also name it <code>CPNT-201-A1</code></li>
<li>Set up a new repository and name it <code>CPNT-201-A1</code></li>
<li>In the repository create a <code>README.md</code> (you can do this when you set up the repository)</li>
<li>In your <code>README.md</code> add the following information:<ul><li>Your name</li>
<li>The job title</li>
<li>A brief general description of the job.</li>
<li>An unordered list (3-5 items) of general responsibilities<ul><li>put this under a level 2 heading called “Responsibilities”</li></ul></li></ul></li>
<li>In your project board, name the columns as relevant status’ or categories of tasks (3+ columns)<ul><li>A Kanban can be used to just group things and not need to move tasks through todo states</li>
<li>For example: does the job have prep, action, cleanup  tasks? Design the board to fit the job</li></ul></li>
<li>Create 5 project cards and organize them on your board<ul><li>Tasks should include:<ul><li>A “Context” or “Description” (level 3 heading with paragraph text below it): 1-4 sentences</li>
<li>A “Definition of Done”: Use markdown checkboxes with at least 1 item</li></ul></li>
<li>Tasks need to be made into issues and added to the repository</li></ul></li></ol>
<hr>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>This assignment will be marked out of 20 points.</p>
<h3 id="${"project-board-and-repo-configuration-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#project-board-and-repo-configuration-5-points"}"><span class="${"icon icon-link"}"></span></a>Project Board and Repo Configuration: 5 points</h3>
<ul><li>Board and Repo connected</li>
<li>Columns setup</li></ul>
<h3 id="${"readme-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#readme-5-points"}"><span class="${"icon icon-link"}"></span></a>Readme: 5 points</h3>
<ul><li>Name</li>
<li>Description</li>
<li>Responsibilities list</li></ul>
<h3 id="${"5-project-cards-10-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#5-project-cards-10-points"}"><span class="${"icon icon-link"}"></span></a>5 Project cards: 10 points</h3>
<ul><li>Context/description</li>
<li>Definition of Done.</li>
<li>Task list</li>
<li>Converted to Issue</li></ul>
<hr>
<h2 id="${"submitting-your-assignment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submitting-your-assignment"}"><span class="${"icon icon-link"}"></span></a>Submitting Your Assignment</h2>
<p>In order to receive a grade, you must:</p>
<ol><li>Submit a link to your Repository as a comment in Brightspace.<ul><li>Make sure your board is public so your instructors can access it.</li></ul></li>
<li>Along with the link, zip a screenshot of the project board in it’s ready state and submit that as well</li></ol>`;
});

export { Assignment_1 as default, metadata };
