import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-201/assignment-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 2 - Three Deployed HTML5 Templates",
	"type": "assignment",
	"points": 20
};

const Assignment_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"details"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#details"}"><span class="${"icon icon-link"}"></span></a>Details</h2>
<p>In this assignment, you will deploy three <em>distinct</em> static website templates that could be customized for a fictitious business of your choice.</p>
<p><strong>Scenario</strong>: You have landed a new client! They want to choose a template for their new website at the next meeting. You want to impress them with three websites that are:</p>
<ul><li>deployed (i.e. published) on GH Pages</li>
<li>visually distinct with respect to UX/UI</li>
<li>customized with the company name and logo<ul><li>the name can be made up</li>
<li>the logo can be an icon from Font Awesome or similar source</li></ul></li></ul>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Search online for three <em>distinct</em> static website templates that could be customized for your selected client;</li>
<li>Deploy each template to GH Pages, naming each repo “cpnt201-a2-[template-name]“;</li>
<li>Make at least three customizations to <em>each</em> template <strong>as separate commits</strong>.<ul><li>At the end of this assignment, you should have made at least 12 commits; three for each of the three customizations, plus your initial commits (which are not counted for marks).</li></ul></li></ol>
<hr>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>This assignment will be marked out of 20 points.</p>
<h3 id="${"github-setup-4-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#github-setup-4-points"}"><span class="${"icon icon-link"}"></span></a>GitHub Setup: 4 points</h3>
<ul><li>Local name and email address set correctly in your config</li>
<li>GitHub Profile updated with:<ul><li>Profile photo</li>
<li>Bio</li>
<li>Location</li>
<li>Optional: website, Twitter, etc</li></ul></li></ul>
<h3 id="${"distinctiveness-4-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#distinctiveness-4-points"}"><span class="${"icon icon-link"}"></span></a>Distinctiveness: 4 points</h3>
<p>The three templates will collectively be scored on their visual distinctiveness according to the criteria listed above. Each template should offer a diverse choice for the client by:</p>
<ul><li>being visually distinct from the other two templates;</li>
<li>representing, collectively, a wide variety of layout elements (cards, sliders, gallery, etc).</li></ul>
<h3 id="${"each-template-4-points-12-points-total"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#each-template-4-points-12-points-total"}"><span class="${"icon icon-link"}"></span></a>Each Template: 4 points (12 points total)</h3>
<p>Each individual template will be marked according to the following criteria.</p>
<ol><li>Functionality:<ul><li>Each template should be responsive, and</li>
<li>have the potential to be a multi-page site.</li></ul></li>
<li>Deployment:<ul><li>Each template should be deployed using GitHub Pages (<em>not</em> with a GH theme) and be viewable on a mobile device.</li></ul></li>
<li>Committed Changes:<ul><li>Your initial commit for each template should be the base template with no modifications. The commit message should be “Initial commit”.</li>
<li>There should be at least three additional commits (in addition to commit 1, your initial commit) that customize content or code. For example:<ul><li>page titles and headings (commit 2),</li>
<li>page logo/icon (commit 3),</li>
<li>primary navigation (commit 4).</li></ul></li>
<li>Each change should have a descriptive commit message (i.e. NOT “updated page”).</li>
<li>The changes themselves cannot break the design.</li></ul></li></ol>
<p>Please include a link to the original template source, either in the project README or as a comment to your Brightspace submission.</p>
<hr>
<h2 id="${"submitting-your-assignment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submitting-your-assignment"}"><span class="${"icon icon-link"}"></span></a>Submitting Your Assignment</h2>
<p>In order to receive a grade, you must:</p>
<ol><li>Deploy each template to a separate GitHub Pages repository named “cpnt201-a2-[template-name]“.</li>
<li>Zip your projects/repos and submit them to Brightspace.</li>
<li>Include links to each GitHub repo <em>and</em> GH Pages site as a comment with your Brightspace submission. You should have six links total. Points will be deducted for missing links.</li></ol>`;
});

export { Assignment_2 as default, metadata };
