import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-200/assignment-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 2 - Strapi Project and Model",
	"type": "assignment",
	"points": 30
};

const Assignment_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<p>In this assignment, you will create a Strapi project and define a Model for an app/website of your choice.</p>
<p>For example, the app/website could be:</p>
<ul><li>A bar, pub or restaurant;</li>
<li>An online store;</li>
<li>Service-focused (i.e. web developer, law office, hair-stylist, etc).</li></ul>
<p>This project model should match and represent the content you are building for the Content Achievements. You will enter for Content entries into this project to receive marks for your achievements.</p>
<h2 id="${"general-requirements"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#general-requirements"}"><span class="${"icon icon-link"}"></span></a>General Requirements</h2>
<ol><li>Collectively, your Collection and Page Content-types must incorporate at least one of the following field types:<ul><li>Text (short or long);</li>
<li>Rich text</li>
<li>Number or Date</li>
<li>Boolean</li>
<li>Media image or video</li></ul></li>
<li>Each Content-type should have one example Entry in the Content Manager to illustrate its use.</li></ol>
<hr>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>Each of the following will be worth 4 points for a total of 20 points.</p>
<h2 id="${"1-project-topic"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#1-project-topic"}"><span class="${"icon icon-link"}"></span></a>1. Project Topic</h2>
<p>Replace the default README file with a description of your project topic, including:</p>
<ul><li>A descriptive project title.</li>
<li>A project description defining a hypothetical client or your own company/website/app. The description should be 150-250 words.</li>
<li>A potential Sitemap that your project would have on the frontend.</li></ul>
<h2 id="${"2-collection-types"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#2-collection-types"}"><span class="${"icon icon-link"}"></span></a>2. Collection Types</h2>
<p>Define the models for at least two Collection Types that match the content you create for your Content Achievements.</p>
<p>Collectively, these Collections(s) must include examples of the following fields:</p>
<ul><li>A title or name;</li>
<li>At least three other fields that fulfill the General Requirements above.</li></ul>
<h2 id="${"3-single-types"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#3-single-types"}"><span class="${"icon icon-link"}"></span></a>3. Single Types</h2>
<p>Define the models for 2-4 Single Types that match the content you create for your Content Achievements. </p>
<p>These pages must include:</p>
<ul><li>A page title;</li>
<li>A rich text field for page content.</li>
<li>At least one other field that fulfills the General Requirements above.</li></ul>
<h2 id="${"4-extras"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#4-extras"}"><span class="${"icon icon-link"}"></span></a>4. Extras</h2>
<p>Include at least one example of each of the following:</p>
<ul><li>An appropriate bi-directional relation between two Content-types, logically labelled;</li>
<li>A re-usable component that is used in one or more Content-types;</li></ul>
<p>In your README, provide some details of where the Relation and Components can be found in your project and how they are used.</p>
<h2 id="${"5-api-token"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#5-api-token"}"><span class="${"icon icon-link"}"></span></a>5. API Token</h2>
<p>Create a read-only Bearer token for your project and include it as a comment in your Brightspace submission.</p>
<hr>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission Instructions</h2>
<ul><li>If possible: <a href="${"https://sait-wbdv.github.io/slides/f22/cpnt-200/strapi-deployment.html"}" rel="${"nofollow"}">Deploy your project</a> to <a href="${"https://render.com"}" rel="${"nofollow"}">render.com</a></li>
<li>Submit the following files:<ul><li>A ZIP of your project (without the <code>node-modules</code> directory)</li>
<li>The <code>.env</code> file of your project</li>
<li>The <code>data.db</code> file located in the <code>.tmp</code> directory of your project</li></ul></li>
<li>As a comment in your Brightspace submission, include:<ul><li>A GitHub repo link</li>
<li>If available: The URL of your deployed Strapi project</li>
<li>The login information for a Super-user (either yours or an invite link)</li></ul></li></ul>`;
});

export { Assignment_2 as default, metadata };
