import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/dsgn-270/assignment-2.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Assignment 2 - Responsive Design Visual Report",
	"type": "assignment",
	"points": 20
};

const Assignment_2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"background"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#background"}"><span class="${"icon icon-link"}"></span></a>Background</h2>
<p>Responsive Design, and in particular, mobile first design have become important concepts in modern web development. As more and more people use mobile devices to navigate websites and use web applications, it is essential that your websites are responsive and mobile friendly. This assignment is to research how responsive design works from an end user perspective.</p>
<h3 id="${"task"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#task"}"><span class="${"icon icon-link"}"></span></a>Task</h3>
<p>This is very similar to the moodboarding that you did in assignment 1. However the structure of your content should be less exploratory and more analytical/critical. This is like a visual book report.</p>
<p>You will create this in figjam, you are welcome to use one of the figjam templates to structure your report, or you can work from scratch. Find examples of the UI elements listed below, take screenshots of them at their different breakpoints to show how content is reorganized to fit different sizes of screens.</p>
<h3 id="${"ui-elements-to-screenshot"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#ui-elements-to-screenshot"}"><span class="${"icon icon-link"}"></span></a>UI Elements to screenshot</h3>
<ul><li>Navbar &amp; Navigation links</li>
<li>Header or Footer</li>
<li>Gallery</li>
<li>Section with a large image and text</li></ul>
<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<ol><li>Find examples of the above UI elements </li>
<li>Test the breakpoints by resizing the browser window</li>
<li>Screenshot examples of good and bad responsive design</li>
<li>Add the images to your report</li>
<li>Write your analysis of why each example that you show represents good or bad design </li></ol>
<ul><li>between 2-10 sentences each</li>
<li>Analysis and Images need to be positioned using good visual hierarchy</li></ul>
<ol start="${"6"}"><li>Export your figjam file to PDF</li></ol>
<h2 id="${"marking-rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#marking-rubric"}"><span class="${"icon icon-link"}"></span></a>Marking Rubric</h2>
<p>This assignment will be marked out of 20 points.</p>
<h3 id="${"navbar--navigation-links-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#navbar--navigation-links-5-points"}"><span class="${"icon icon-link"}"></span></a>Navbar &amp; Navigation Links: 5 points</h3>
<ul><li>Images for each breakpoint (make sure to include a screenshot of the mobile menu) <strong>2pts</strong></li>
<li>reflection notes and critiques <strong>3pts</strong></li></ul>
<h3 id="${"header-or-footer-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#header-or-footer-5-points"}"><span class="${"icon icon-link"}"></span></a>Header or Footer: 5 points</h3>
<ul><li>Images for each breakpoint <strong>2pts</strong></li>
<li>reflection notes and critiques <strong>3pts</strong></li></ul>
<h3 id="${"gallery-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#gallery-5-points"}"><span class="${"icon icon-link"}"></span></a>Gallery: 5 points</h3>
<ul><li>Images for each breakpoint <strong>2pts</strong></li>
<li>reflection notes and critiques <strong>3pts</strong></li></ul>
<h3 id="${"-image-and-text-section-5-points"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#-image-and-text-section-5-points"}"><span class="${"icon icon-link"}"></span></a>: Image and Text Section: 5 points</h3>
<ul><li>Images for each breakpoint <strong>2pts</strong></li>
<li>reflection notes and critiques  <strong>3pts</strong></li></ul>
<hr>
<h2 id="${"submitting-your-assignment"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submitting-your-assignment"}"><span class="${"icon icon-link"}"></span></a>Submitting Your Assignment</h2>
<p>In order to receive a grade, you must:</p>
<ol><li>Export your report to a pdf</li>
<li>Get a viewable link to your report and paste the link in the text box of your submission (do not send an email invite)</li>
<li>Zip the pdf of your report</li>
<li>Submit the PDF along with the link to your active report</li></ol>`;
});

export { Assignment_2 as default, metadata };
