import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-260/drafts/labs.md generated by Svelte v3.55.0 */

const Labs = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h3 id="${"wrapper-refactor"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#wrapper-refactor"}"><span class="${"icon icon-link"}"></span></a>Wrapper refactor</h3>
<ol><li>Pick one of you to fork the relevant codepen to your account;</li>
<li>While logged into Codepen, navigate to your cloned Pen and copy the Collab link in the Change View menu;</li>
<li>Paste this link into the Zoom chat so your partner can open the same Pen in collab mode;</li>
<li>Complete the exercise while following the pair programming Dos and Donts!</li></ol>
<h3 id="${"color-cascade"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#color-cascade"}"><span class="${"icon icon-link"}"></span></a>Color cascade</h3>
<h3 id="${"links-more-clickable"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#links-more-clickable"}"><span class="${"icon icon-link"}"></span></a>Links more clickable</h3>`;
});

export { Labs as default };
