import { c as create_ssr_component } from './index.js';

/* src/lib/content/courses/cpnt-262/drafts/reveal-js.md generated by Svelte v3.55.0 */

const Reveal_js = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"demo-html-presentation-slides"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#demo-html-presentation-slides"}"><span class="${"icon icon-link"}"></span></a>Demo: HTML presentation slides</h2>
<p>We’ll be using <a href="${"https://revealjs.com/"}" rel="${"nofollow"}">RevealJS</a> to create HTML presentations. Feel free to <a href="${"https://revealjs.com/installation/"}" rel="${"nofollow"}">install it early</a> and play around with it.</p>
<ul><li><a href="${"https://revealjs.com/demo/"}" rel="${"nofollow"}">Live Demo</a></li>
<li><a href="${"https://revealjs.com/markup/"}" rel="${"nofollow"}">Marking up Slides</a></li>
<li><a href="${"https://revealjs.com/config/"}" rel="${"nofollow"}">Config Options</a></li></ul>`;
});

export { Reveal_js as default };
