import { c as create_ssr_component } from './index.js';

/* src/lib/content/assessments/cpnt-262/team-project.md generated by Svelte v3.55.0 */

const metadata = {
	"title": "Team Project - Multipage Website",
	"type": "assignment",
	"points": 25
};

const Team_project = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<h2 id="${"instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#instructions"}"><span class="${"icon icon-link"}"></span></a>Instructions</h2>
<p>In teams of 2-3 you will make a multipage Nuxt 3 Website that pulls data from an api (your own strapi implementation from 200 or a public api).</p>
<p>This assignment is meant for you to put together the skills that you’ve learned throughout this course to create a modern website and hone your skills for your Course Final Project.</p>
<h3 id="${"specifications"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#specifications"}"><span class="${"icon icon-link"}"></span></a>Specifications</h3>
<ul><li>4 Pages<ul><li>Home</li>
<li>About</li>
<li>Services/Products/Blog Collection Page</li>
<li>Service/Product/Post page (dynamic)</li></ul></li>
<li>Components (minimum 8, grouped at developer descretion)<ul><li>ui: nav bar, footer, sidebar…</li>
<li>layout: headers, sections, banners, cards…</li>
<li>utilities: buttons, display text, lists, links…</li></ul></li>
<li>Data (choose 1)<ul><li>Strapi API (from a 200 assignment)</li>
<li>Public API</li>
<li>Nuxt Content Module (local blog)</li></ul></li>
<li>Design<ul><li>Use vanilla CSS <strong>or</strong> TailwindCSS</li></ul></li></ul>
<h3 id="${"team-work"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#team-work"}"><span class="${"icon icon-link"}"></span></a>Team Work</h3>
<ul><li><p>Divide the work to fit your strengths</p></li>
<li><p>Document your team member’s agreed upon responsibilities in the README (changes are fine but this needs to be documented early on)</p></li>
<li><p>Use of Pull Requests to track work and follow each others progress</p></li>
<li><p>Do code reviews when needed to improve your work</p></li>
<li><p><strong>Communicate regularly</strong></p></li></ul>
<h2 id="${"rubric"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#rubric"}"><span class="${"icon icon-link"}"></span></a>Rubric</h2>
<h3 id="${"components-5"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#components-5"}"><span class="${"icon icon-link"}"></span></a>Components 5</h3>
<ul><li>Properly defined props and slots</li>
<li>class bindings used in page header for greater distinction</li>
<li>v-bind and moustache syntax used correctly</li>
<li>Components imported and rendered correctly</li></ul>
<h3 id="${"data-fetching-and-modules-5"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#data-fetching-and-modules-5"}"><span class="${"icon icon-link"}"></span></a>Data Fetching and Modules 5</h3>
<ul><li>Data from api or nuxt content used</li>
<li>Nuxt Modules or other plugins used when needed (ie: google fonts, tailwind, strapi…)</li></ul>
<h3 id="${"page-templating"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#page-templating"}"><span class="${"icon icon-link"}"></span></a>Page Templating</h3>
<ul><li>Pages have minimal to no repeating code (use of components and v-for)</li>
<li>Content renders</li>
<li>Hierarchy of layout - page - component followed</li>
<li>Data passed with Props</li></ul>
<h3 id="${"page-design-5"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#page-design-5"}"><span class="${"icon icon-link"}"></span></a>Page Design 5</h3>
<ul><li>Consistent design scheme</li>
<li>Uses scoped css or tailwind</li>
<li>Responsive design</li></ul>
<h3 id="${"project-organization-5"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#project-organization-5"}"><span class="${"icon icon-link"}"></span></a>Project Organization 5</h3>
<ul><li>Site is Deployed to Netlify</li>
<li>Pull Requests used to merge from dev branch(es) to main</li>
<li>Clear commit messages</li>
<li>Attributions</li>
<li>README outlines team member responsibilities</li></ul>
<h2 id="${"submission-instructions"}"><a aria-hidden="${"true"}" tabindex="${"-1"}" href="${"#submission-instructions"}"><span class="${"icon icon-link"}"></span></a>Submission Instructions</h2>
<ul><li>One submission per group required</li>
<li>Submit github repo and link to deployed Netlify Site</li>
<li>No node_modules in remote repo or zip file</li></ul>`;
});

export { Team_project as default, metadata };
